// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ExBaseCmd.proto
// Protobuf C++ Version: 5.27.0

#include "ExBaseCmd.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_ExBaseCmd_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_ExBaseCmd_2eproto = nullptr;
const ::uint32_t TableStruct_ExBaseCmd_2eproto::offsets[1] = {};
static constexpr ::_pbi::MigrationSchema* schemas = nullptr;
static constexpr ::_pb::Message* const* file_default_instances = nullptr;
const char descriptor_table_protodef_ExBaseCmd_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\017ExBaseCmd.proto*\212\002\n\rENUM_BASE_CMD\022\026\n\022C"
    "2S_DceGetNetDelay\020\003\022\022\n\016C2S_DceSetMark\020\007\022"
    "\030\n\024C2S_DceGetServerTime\020\t\022\024\n\020C2S_DceEcho"
    "Trace\020\013\022\023\n\017S2C_DseSyncTime\020\002\022\026\n\022S2C_DseG"
    "etNetDelay\020\004\022\024\n\020S2C_DseErrorCode\020\006\022\022\n\016S2"
    "C_DseSetMark\020\010\022\030\n\024S2C_DseGetServerTime\020\n"
    "\022\024\n\020S2C_DseEchoTrace\020\014\022\026\n\022S2C_DseKickOut"
    "Gate\020\016"
};
static ::absl::once_flag descriptor_table_ExBaseCmd_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_ExBaseCmd_2eproto = {
    false,
    false,
    286,
    descriptor_table_protodef_ExBaseCmd_2eproto,
    "ExBaseCmd.proto",
    &descriptor_table_ExBaseCmd_2eproto_once,
    nullptr,
    0,
    0,
    schemas,
    file_default_instances,
    TableStruct_ExBaseCmd_2eproto::offsets,
    file_level_enum_descriptors_ExBaseCmd_2eproto,
    file_level_service_descriptors_ExBaseCmd_2eproto,
};
const ::google::protobuf::EnumDescriptor* ENUM_BASE_CMD_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_ExBaseCmd_2eproto);
  return file_level_enum_descriptors_ExBaseCmd_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t ENUM_BASE_CMD_internal_data_[] = {
    196610u, 32u, 766u, };
bool ENUM_BASE_CMD_IsValid(int value) {
  return 0 <= value && value <= 14 && ((24540u >> value) & 1) != 0;
}
// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_ExBaseCmd_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
