// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ExBaseCmd.proto
// Protobuf C++ Version: 5.27.0

#ifndef GOOGLE_PROTOBUF_INCLUDED_ExBaseCmd_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_ExBaseCmd_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5027000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_ExBaseCmd_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_ExBaseCmd_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_ExBaseCmd_2eproto;
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

enum ENUM_BASE_CMD : int {
  C2S_DceGetNetDelay = 3,
  C2S_DceSetMark = 7,
  C2S_DceGetServerTime = 9,
  C2S_DceEchoTrace = 11,
  S2C_DseSyncTime = 2,
  S2C_DseGetNetDelay = 4,
  S2C_DseErrorCode = 6,
  S2C_DseSetMark = 8,
  S2C_DseGetServerTime = 10,
  S2C_DseEchoTrace = 12,
  S2C_DseKickOutGate = 14,
};

bool ENUM_BASE_CMD_IsValid(int value);
extern const uint32_t ENUM_BASE_CMD_internal_data_[];
constexpr ENUM_BASE_CMD ENUM_BASE_CMD_MIN = static_cast<ENUM_BASE_CMD>(2);
constexpr ENUM_BASE_CMD ENUM_BASE_CMD_MAX = static_cast<ENUM_BASE_CMD>(14);
constexpr int ENUM_BASE_CMD_ARRAYSIZE = 14 + 1;
const ::google::protobuf::EnumDescriptor*
ENUM_BASE_CMD_descriptor();
template <typename T>
const std::string& ENUM_BASE_CMD_Name(T value) {
  static_assert(std::is_same<T, ENUM_BASE_CMD>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to ENUM_BASE_CMD_Name().");
  return ENUM_BASE_CMD_Name(static_cast<ENUM_BASE_CMD>(value));
}
template <>
inline const std::string& ENUM_BASE_CMD_Name(ENUM_BASE_CMD value) {
  return ::google::protobuf::internal::NameOfDenseEnum<ENUM_BASE_CMD_descriptor,
                                                 2, 14>(
      static_cast<int>(value));
}
inline bool ENUM_BASE_CMD_Parse(absl::string_view name, ENUM_BASE_CMD* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ENUM_BASE_CMD>(
      ENUM_BASE_CMD_descriptor(), name, value);
}

// ===================================================================



// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::ENUM_BASE_CMD> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::ENUM_BASE_CMD>() {
  return ::ENUM_BASE_CMD_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_ExBaseCmd_2eproto_2epb_2eh
