// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ExFriendMsg.proto
// Protobuf C++ Version: 5.27.0

#include "ExFriendMsg.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_ExFriendMsg_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_ExFriendMsg_2eproto = nullptr;
const ::uint32_t TableStruct_ExFriendMsg_2eproto::offsets[1] = {};
static constexpr ::_pbi::MigrationSchema* schemas = nullptr;
static constexpr ::_pb::Message* const* file_default_instances = nullptr;
const char descriptor_table_protodef_ExFriendMsg_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\021ExFriendMsg.proto*R\n\017ENUM_FRIEND_CMD\022\034"
    "\n\027S2C_DseFriendChatNotice\020\310~\022!\n\034S2C_DseF"
    "riendBeApplyedNotice\020\312~"
};
static ::absl::once_flag descriptor_table_ExFriendMsg_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_ExFriendMsg_2eproto = {
    false,
    false,
    103,
    descriptor_table_protodef_ExFriendMsg_2eproto,
    "ExFriendMsg.proto",
    &descriptor_table_ExFriendMsg_2eproto_once,
    nullptr,
    0,
    0,
    schemas,
    file_default_instances,
    TableStruct_ExFriendMsg_2eproto::offsets,
    file_level_enum_descriptors_ExFriendMsg_2eproto,
    file_level_service_descriptors_ExFriendMsg_2eproto,
};
const ::google::protobuf::EnumDescriptor* ENUM_FRIEND_CMD_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_ExFriendMsg_2eproto);
  return file_level_enum_descriptors_ExFriendMsg_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t ENUM_FRIEND_CMD_internal_data_[] = {
    81736u, 32u, 2u, };
bool ENUM_FRIEND_CMD_IsValid(int value) {
  return ::_pbi::ValidateEnum(value, ENUM_FRIEND_CMD_internal_data_);
}
// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_ExFriendMsg_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
