// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ExGameSetData.proto
// Protobuf C++ Version: 5.27.0

#include "ExGameSetData.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;

inline constexpr ExGameSet::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        pb_v_tuple_int_{},
        pb_v_tuple_str_{},
        pb_v_tuple_float_{},
        pb_key_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        pb_desc_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        pb_v_str_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        pb_id_{0},
        pb_type_{0},
        pb_v_int_{0},
        pb_v_float_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ExGameSet::ExGameSet(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct ExGameSetDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ExGameSetDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ExGameSetDefaultTypeInternal() {}
  union {
    ExGameSet _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ExGameSetDefaultTypeInternal _ExGameSet_default_instance_;

inline constexpr ExGameSetTable::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        pb_tlist_{},
        pb_tname_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()) {}

template <typename>
PROTOBUF_CONSTEXPR ExGameSetTable::ExGameSetTable(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct ExGameSetTableDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ExGameSetTableDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ExGameSetTableDefaultTypeInternal() {}
  union {
    ExGameSetTable _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ExGameSetTableDefaultTypeInternal _ExGameSetTable_default_instance_;
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_ExGameSetData_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_ExGameSetData_2eproto = nullptr;
const ::uint32_t
    TableStruct_ExGameSetData_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        PROTOBUF_FIELD_OFFSET(::ExGameSet, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::ExGameSet, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::ExGameSet, _impl_.pb_id_),
        PROTOBUF_FIELD_OFFSET(::ExGameSet, _impl_.pb_type_),
        PROTOBUF_FIELD_OFFSET(::ExGameSet, _impl_.pb_key_),
        PROTOBUF_FIELD_OFFSET(::ExGameSet, _impl_.pb_desc_),
        PROTOBUF_FIELD_OFFSET(::ExGameSet, _impl_.pb_v_int_),
        PROTOBUF_FIELD_OFFSET(::ExGameSet, _impl_.pb_v_str_),
        PROTOBUF_FIELD_OFFSET(::ExGameSet, _impl_.pb_v_float_),
        PROTOBUF_FIELD_OFFSET(::ExGameSet, _impl_.pb_v_tuple_int_),
        PROTOBUF_FIELD_OFFSET(::ExGameSet, _impl_.pb_v_tuple_str_),
        PROTOBUF_FIELD_OFFSET(::ExGameSet, _impl_.pb_v_tuple_float_),
        3,
        4,
        0,
        1,
        5,
        2,
        6,
        ~0u,
        ~0u,
        ~0u,
        PROTOBUF_FIELD_OFFSET(::ExGameSetTable, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::ExGameSetTable, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::ExGameSetTable, _impl_.pb_tname_),
        PROTOBUF_FIELD_OFFSET(::ExGameSetTable, _impl_.pb_tlist_),
        0,
        ~0u,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, 18, -1, sizeof(::ExGameSet)},
        {28, 38, -1, sizeof(::ExGameSetTable)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::_ExGameSet_default_instance_._instance,
    &::_ExGameSetTable_default_instance_._instance,
};
const char descriptor_table_protodef_ExGameSetData_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\023ExGameSetData.proto\"\316\001\n\tExGameSet\022\r\n\005p"
    "b_id\030\001 \002(\005\022\017\n\007pb_type\030\002 \001(\005\022\016\n\006pb_key\030\003 "
    "\001(\t\022\017\n\007pb_desc\030\004 \001(\t\022\020\n\010pb_v_int\030\005 \001(\005\022\020"
    "\n\010pb_v_str\030\006 \001(\t\022\022\n\npb_v_float\030\007 \001(\002\022\026\n\016"
    "pb_v_tuple_int\030\010 \003(\005\022\026\n\016pb_v_tuple_str\030\t"
    " \003(\t\022\030\n\020pb_v_tuple_float\030\n \003(\002\"@\n\016ExGame"
    "SetTable\022\020\n\010pb_tname\030\001 \001(\t\022\034\n\010pb_tlist\030\002"
    " \003(\0132\n.ExGameSet"
};
static ::absl::once_flag descriptor_table_ExGameSetData_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_ExGameSetData_2eproto = {
    false,
    false,
    296,
    descriptor_table_protodef_ExGameSetData_2eproto,
    "ExGameSetData.proto",
    &descriptor_table_ExGameSetData_2eproto_once,
    nullptr,
    0,
    2,
    schemas,
    file_default_instances,
    TableStruct_ExGameSetData_2eproto::offsets,
    file_level_enum_descriptors_ExGameSetData_2eproto,
    file_level_service_descriptors_ExGameSetData_2eproto,
};
// ===================================================================

class ExGameSet::_Internal {
 public:
  using HasBits =
      decltype(std::declval<ExGameSet>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(ExGameSet, _impl_._has_bits_);
  static bool MissingRequiredFields(const HasBits& has_bits) {
    return ((has_bits[0] & 0x00000008) ^ 0x00000008) != 0;
  }
};

ExGameSet::ExGameSet(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:ExGameSet)
}
inline PROTOBUF_NDEBUG_INLINE ExGameSet::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::ExGameSet& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        pb_v_tuple_int_{visibility, arena, from.pb_v_tuple_int_},
        pb_v_tuple_str_{visibility, arena, from.pb_v_tuple_str_},
        pb_v_tuple_float_{visibility, arena, from.pb_v_tuple_float_},
        pb_key_(arena, from.pb_key_),
        pb_desc_(arena, from.pb_desc_),
        pb_v_str_(arena, from.pb_v_str_) {}

ExGameSet::ExGameSet(
    ::google::protobuf::Arena* arena,
    const ExGameSet& from)
    : ::google::protobuf::Message(arena) {
  ExGameSet* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, pb_id_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, pb_id_),
           offsetof(Impl_, pb_v_float_) -
               offsetof(Impl_, pb_id_) +
               sizeof(Impl_::pb_v_float_));

  // @@protoc_insertion_point(copy_constructor:ExGameSet)
}
inline PROTOBUF_NDEBUG_INLINE ExGameSet::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        pb_v_tuple_int_{visibility, arena},
        pb_v_tuple_str_{visibility, arena},
        pb_v_tuple_float_{visibility, arena},
        pb_key_(arena),
        pb_desc_(arena),
        pb_v_str_(arena) {}

inline void ExGameSet::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, pb_id_),
           0,
           offsetof(Impl_, pb_v_float_) -
               offsetof(Impl_, pb_id_) +
               sizeof(Impl_::pb_v_float_));
}
ExGameSet::~ExGameSet() {
  // @@protoc_insertion_point(destructor:ExGameSet)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void ExGameSet::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.pb_key_.Destroy();
  _impl_.pb_desc_.Destroy();
  _impl_.pb_v_str_.Destroy();
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
ExGameSet::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              ExGameSet::IsInitializedImpl,
              PROTOBUF_FIELD_OFFSET(ExGameSet, _impl_._cached_size_),
              false,
          },
          &ExGameSet::MergeImpl,
          &ExGameSet::kDescriptorMethods,
          &descriptor_table_ExGameSetData_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<4, 10, 0, 61, 2> ExGameSet::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(ExGameSet, _impl_._has_bits_),
    0, // no _extensions_
    10, 120,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294966272,  // skipmap
    offsetof(decltype(_table_), field_entries),
    10,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_ExGameSet_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::ExGameSet>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // required int32 pb_id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ExGameSet, _impl_.pb_id_), 3>(),
     {8, 3, 0, PROTOBUF_FIELD_OFFSET(ExGameSet, _impl_.pb_id_)}},
    // optional int32 pb_type = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ExGameSet, _impl_.pb_type_), 4>(),
     {16, 4, 0, PROTOBUF_FIELD_OFFSET(ExGameSet, _impl_.pb_type_)}},
    // optional string pb_key = 3;
    {::_pbi::TcParser::FastSS1,
     {26, 0, 0, PROTOBUF_FIELD_OFFSET(ExGameSet, _impl_.pb_key_)}},
    // optional string pb_desc = 4;
    {::_pbi::TcParser::FastSS1,
     {34, 1, 0, PROTOBUF_FIELD_OFFSET(ExGameSet, _impl_.pb_desc_)}},
    // optional int32 pb_v_int = 5;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ExGameSet, _impl_.pb_v_int_), 5>(),
     {40, 5, 0, PROTOBUF_FIELD_OFFSET(ExGameSet, _impl_.pb_v_int_)}},
    // optional string pb_v_str = 6;
    {::_pbi::TcParser::FastSS1,
     {50, 2, 0, PROTOBUF_FIELD_OFFSET(ExGameSet, _impl_.pb_v_str_)}},
    // optional float pb_v_float = 7;
    {::_pbi::TcParser::FastF32S1,
     {61, 6, 0, PROTOBUF_FIELD_OFFSET(ExGameSet, _impl_.pb_v_float_)}},
    // repeated int32 pb_v_tuple_int = 8;
    {::_pbi::TcParser::FastV32R1,
     {64, 63, 0, PROTOBUF_FIELD_OFFSET(ExGameSet, _impl_.pb_v_tuple_int_)}},
    // repeated string pb_v_tuple_str = 9;
    {::_pbi::TcParser::FastSR1,
     {74, 63, 0, PROTOBUF_FIELD_OFFSET(ExGameSet, _impl_.pb_v_tuple_str_)}},
    // repeated float pb_v_tuple_float = 10;
    {::_pbi::TcParser::FastF32R1,
     {85, 63, 0, PROTOBUF_FIELD_OFFSET(ExGameSet, _impl_.pb_v_tuple_float_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // required int32 pb_id = 1;
    {PROTOBUF_FIELD_OFFSET(ExGameSet, _impl_.pb_id_), _Internal::kHasBitsOffset + 3, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // optional int32 pb_type = 2;
    {PROTOBUF_FIELD_OFFSET(ExGameSet, _impl_.pb_type_), _Internal::kHasBitsOffset + 4, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // optional string pb_key = 3;
    {PROTOBUF_FIELD_OFFSET(ExGameSet, _impl_.pb_key_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kRawString | ::_fl::kRepAString)},
    // optional string pb_desc = 4;
    {PROTOBUF_FIELD_OFFSET(ExGameSet, _impl_.pb_desc_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kRawString | ::_fl::kRepAString)},
    // optional int32 pb_v_int = 5;
    {PROTOBUF_FIELD_OFFSET(ExGameSet, _impl_.pb_v_int_), _Internal::kHasBitsOffset + 5, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // optional string pb_v_str = 6;
    {PROTOBUF_FIELD_OFFSET(ExGameSet, _impl_.pb_v_str_), _Internal::kHasBitsOffset + 2, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kRawString | ::_fl::kRepAString)},
    // optional float pb_v_float = 7;
    {PROTOBUF_FIELD_OFFSET(ExGameSet, _impl_.pb_v_float_), _Internal::kHasBitsOffset + 6, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kFloat)},
    // repeated int32 pb_v_tuple_int = 8;
    {PROTOBUF_FIELD_OFFSET(ExGameSet, _impl_.pb_v_tuple_int_), -1, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kInt32)},
    // repeated string pb_v_tuple_str = 9;
    {PROTOBUF_FIELD_OFFSET(ExGameSet, _impl_.pb_v_tuple_str_), -1, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kRawString | ::_fl::kRepSString)},
    // repeated float pb_v_tuple_float = 10;
    {PROTOBUF_FIELD_OFFSET(ExGameSet, _impl_.pb_v_tuple_float_), -1, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kFloat)},
  }},
  // no aux_entries
  {{
    "\11\0\0\6\7\0\10\0\0\16\0\0\0\0\0\0"
    "ExGameSet"
    "pb_key"
    "pb_desc"
    "pb_v_str"
    "pb_v_tuple_str"
  }},
};

PROTOBUF_NOINLINE void ExGameSet::Clear() {
// @@protoc_insertion_point(message_clear_start:ExGameSet)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.pb_v_tuple_int_.Clear();
  _impl_.pb_v_tuple_str_.Clear();
  _impl_.pb_v_tuple_float_.Clear();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    if (cached_has_bits & 0x00000001u) {
      _impl_.pb_key_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000002u) {
      _impl_.pb_desc_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000004u) {
      _impl_.pb_v_str_.ClearNonDefaultToEmpty();
    }
  }
  if (cached_has_bits & 0x00000078u) {
    ::memset(&_impl_.pb_id_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.pb_v_float_) -
        reinterpret_cast<char*>(&_impl_.pb_id_)) + sizeof(_impl_.pb_v_float_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* ExGameSet::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ExGameSet)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // required int32 pb_id = 1;
  if (cached_has_bits & 0x00000008u) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<1>(
            stream, this->_internal_pb_id(), target);
  }

  // optional int32 pb_type = 2;
  if (cached_has_bits & 0x00000010u) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<2>(
            stream, this->_internal_pb_type(), target);
  }

  // optional string pb_key = 3;
  if (cached_has_bits & 0x00000001u) {
    const std::string& _s = this->_internal_pb_key();
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(_s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormat::SERIALIZE,
                                "ExGameSet.pb_key");
    target = stream->WriteStringMaybeAliased(3, _s, target);
  }

  // optional string pb_desc = 4;
  if (cached_has_bits & 0x00000002u) {
    const std::string& _s = this->_internal_pb_desc();
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(_s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormat::SERIALIZE,
                                "ExGameSet.pb_desc");
    target = stream->WriteStringMaybeAliased(4, _s, target);
  }

  // optional int32 pb_v_int = 5;
  if (cached_has_bits & 0x00000020u) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<5>(
            stream, this->_internal_pb_v_int(), target);
  }

  // optional string pb_v_str = 6;
  if (cached_has_bits & 0x00000004u) {
    const std::string& _s = this->_internal_pb_v_str();
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(_s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormat::SERIALIZE,
                                "ExGameSet.pb_v_str");
    target = stream->WriteStringMaybeAliased(6, _s, target);
  }

  // optional float pb_v_float = 7;
  if (cached_has_bits & 0x00000040u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        7, this->_internal_pb_v_float(), target);
  }

  // repeated int32 pb_v_tuple_int = 8;
  for (int i = 0, n = this->_internal_pb_v_tuple_int_size(); i < n; ++i) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(
        8, this->_internal_pb_v_tuple_int().Get(i), target);
  }

  // repeated string pb_v_tuple_str = 9;
  for (int i = 0, n = this->_internal_pb_v_tuple_str_size(); i < n; ++i) {
    const auto& s = this->_internal_pb_v_tuple_str().Get(i);
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(s.data(), static_cast<int>(s.length()), ::google::protobuf::internal::WireFormat::SERIALIZE,
                                "ExGameSet.pb_v_tuple_str");
    target = stream->WriteString(9, s, target);
  }

  // repeated float pb_v_tuple_float = 10;
  for (int i = 0, n = this->_internal_pb_v_tuple_float_size(); i < n; ++i) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        10, this->_internal_pb_v_tuple_float().Get(i), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ExGameSet)
  return target;
}

::size_t ExGameSet::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ExGameSet)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(reinterpret_cast<const void*>(this));
  // repeated int32 pb_v_tuple_int = 8;
  {
    std::size_t data_size = ::_pbi::WireFormatLite::Int32Size(
        this->_internal_pb_v_tuple_int())
    ;
    std::size_t tag_size = std::size_t{1} *
        ::_pbi::FromIntSize(this->_internal_pb_v_tuple_int_size());
    ;
    total_size += tag_size + data_size;
  }
  // repeated string pb_v_tuple_str = 9;
  total_size += 1 * ::google::protobuf::internal::FromIntSize(_internal_pb_v_tuple_str().size());
  for (int i = 0, n = _internal_pb_v_tuple_str().size(); i < n; ++i) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
        _internal_pb_v_tuple_str().Get(i));
  }
  // repeated float pb_v_tuple_float = 10;
  {
    std::size_t data_size = std::size_t{4} *
        ::_pbi::FromIntSize(this->_internal_pb_v_tuple_float_size())
    ;
    std::size_t tag_size = std::size_t{1} *
        ::_pbi::FromIntSize(this->_internal_pb_v_tuple_float_size());
    ;
    total_size += tag_size + data_size;
  }
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    // optional string pb_key = 3;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this->_internal_pb_key());
    }

    // optional string pb_desc = 4;
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this->_internal_pb_desc());
    }

    // optional string pb_v_str = 6;
    if (cached_has_bits & 0x00000004u) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this->_internal_pb_v_str());
    }

  }
  // required int32 pb_id = 1;
  if (cached_has_bits & 0x00000008u) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_pb_id());
  }

  if (cached_has_bits & 0x00000070u) {
    // optional int32 pb_type = 2;
    if (cached_has_bits & 0x00000010u) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
          this->_internal_pb_type());
    }

    // optional int32 pb_v_int = 5;
    if (cached_has_bits & 0x00000020u) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
          this->_internal_pb_v_int());
    }

    // optional float pb_v_float = 7;
    if (cached_has_bits & 0x00000040u) {
      total_size += 5;
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void ExGameSet::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ExGameSet*>(&to_msg);
  auto& from = static_cast<const ExGameSet&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ExGameSet)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_pb_v_tuple_int()->MergeFrom(from._internal_pb_v_tuple_int());
  _this->_internal_mutable_pb_v_tuple_str()->MergeFrom(from._internal_pb_v_tuple_str());
  _this->_internal_mutable_pb_v_tuple_float()->MergeFrom(from._internal_pb_v_tuple_float());
  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x0000007fu) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_set_pb_key(from._internal_pb_key());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_internal_set_pb_desc(from._internal_pb_desc());
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_internal_set_pb_v_str(from._internal_pb_v_str());
    }
    if (cached_has_bits & 0x00000008u) {
      _this->_impl_.pb_id_ = from._impl_.pb_id_;
    }
    if (cached_has_bits & 0x00000010u) {
      _this->_impl_.pb_type_ = from._impl_.pb_type_;
    }
    if (cached_has_bits & 0x00000020u) {
      _this->_impl_.pb_v_int_ = from._impl_.pb_v_int_;
    }
    if (cached_has_bits & 0x00000040u) {
      _this->_impl_.pb_v_float_ = from._impl_.pb_v_float_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ExGameSet::CopyFrom(const ExGameSet& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ExGameSet)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool ExGameSet::IsInitializedImpl(
    const MessageLite& msg) {
  auto& this_ = static_cast<const ExGameSet&>(msg);
  if (_Internal::MissingRequiredFields(this_._impl_._has_bits_)) {
    return false;
  }
  return true;
}

void ExGameSet::InternalSwap(ExGameSet* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.pb_v_tuple_int_.InternalSwap(&other->_impl_.pb_v_tuple_int_);
  _impl_.pb_v_tuple_str_.InternalSwap(&other->_impl_.pb_v_tuple_str_);
  _impl_.pb_v_tuple_float_.InternalSwap(&other->_impl_.pb_v_tuple_float_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.pb_key_, &other->_impl_.pb_key_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.pb_desc_, &other->_impl_.pb_desc_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.pb_v_str_, &other->_impl_.pb_v_str_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ExGameSet, _impl_.pb_v_float_)
      + sizeof(ExGameSet::_impl_.pb_v_float_)
      - PROTOBUF_FIELD_OFFSET(ExGameSet, _impl_.pb_id_)>(
          reinterpret_cast<char*>(&_impl_.pb_id_),
          reinterpret_cast<char*>(&other->_impl_.pb_id_));
}

::google::protobuf::Metadata ExGameSet::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class ExGameSetTable::_Internal {
 public:
  using HasBits =
      decltype(std::declval<ExGameSetTable>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(ExGameSetTable, _impl_._has_bits_);
};

ExGameSetTable::ExGameSetTable(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:ExGameSetTable)
}
inline PROTOBUF_NDEBUG_INLINE ExGameSetTable::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::ExGameSetTable& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        pb_tlist_{visibility, arena, from.pb_tlist_},
        pb_tname_(arena, from.pb_tname_) {}

ExGameSetTable::ExGameSetTable(
    ::google::protobuf::Arena* arena,
    const ExGameSetTable& from)
    : ::google::protobuf::Message(arena) {
  ExGameSetTable* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:ExGameSetTable)
}
inline PROTOBUF_NDEBUG_INLINE ExGameSetTable::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        pb_tlist_{visibility, arena},
        pb_tname_(arena) {}

inline void ExGameSetTable::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
ExGameSetTable::~ExGameSetTable() {
  // @@protoc_insertion_point(destructor:ExGameSetTable)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void ExGameSetTable::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.pb_tname_.Destroy();
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
ExGameSetTable::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              ExGameSetTable::IsInitializedImpl,
              PROTOBUF_FIELD_OFFSET(ExGameSetTable, _impl_._cached_size_),
              false,
          },
          &ExGameSetTable::MergeImpl,
          &ExGameSetTable::kDescriptorMethods,
          &descriptor_table_ExGameSetData_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 1, 31, 2> ExGameSetTable::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(ExGameSetTable, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_ExGameSetTable_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::ExGameSetTable>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated .ExGameSet pb_tlist = 2;
    {::_pbi::TcParser::FastMtR1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(ExGameSetTable, _impl_.pb_tlist_)}},
    // optional string pb_tname = 1;
    {::_pbi::TcParser::FastSS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(ExGameSetTable, _impl_.pb_tname_)}},
  }}, {{
    65535, 65535
  }}, {{
    // optional string pb_tname = 1;
    {PROTOBUF_FIELD_OFFSET(ExGameSetTable, _impl_.pb_tname_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kRawString | ::_fl::kRepAString)},
    // repeated .ExGameSet pb_tlist = 2;
    {PROTOBUF_FIELD_OFFSET(ExGameSetTable, _impl_.pb_tlist_), -1, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::ExGameSet>()},
  }}, {{
    "\16\10\0\0\0\0\0\0"
    "ExGameSetTable"
    "pb_tname"
  }},
};

PROTOBUF_NOINLINE void ExGameSetTable::Clear() {
// @@protoc_insertion_point(message_clear_start:ExGameSetTable)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.pb_tlist_.Clear();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    _impl_.pb_tname_.ClearNonDefaultToEmpty();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* ExGameSetTable::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ExGameSetTable)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // optional string pb_tname = 1;
  if (cached_has_bits & 0x00000001u) {
    const std::string& _s = this->_internal_pb_tname();
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(_s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormat::SERIALIZE,
                                "ExGameSetTable.pb_tname");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // repeated .ExGameSet pb_tlist = 2;
  for (unsigned i = 0, n = static_cast<unsigned>(
                           this->_internal_pb_tlist_size());
       i < n; i++) {
    const auto& repfield = this->_internal_pb_tlist().Get(i);
    target =
        ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
            2, repfield, repfield.GetCachedSize(),
            target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ExGameSetTable)
  return target;
}

::size_t ExGameSetTable::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ExGameSetTable)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(reinterpret_cast<const void*>(this));
  // repeated .ExGameSet pb_tlist = 2;
  total_size += 1UL * this->_internal_pb_tlist_size();
  for (const auto& msg : this->_internal_pb_tlist()) {
    total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
  }
  // optional string pb_tname = 1;
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_pb_tname());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void ExGameSetTable::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ExGameSetTable*>(&to_msg);
  auto& from = static_cast<const ExGameSetTable&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ExGameSetTable)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_pb_tlist()->MergeFrom(
      from._internal_pb_tlist());
  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    _this->_internal_set_pb_tname(from._internal_pb_tname());
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ExGameSetTable::CopyFrom(const ExGameSetTable& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ExGameSetTable)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool ExGameSetTable::IsInitializedImpl(
    const MessageLite& msg) {
  auto& this_ = static_cast<const ExGameSetTable&>(msg);
  if (!::google::protobuf::internal::AllAreInitialized(this_._internal_pb_tlist()))
    return false;
  return true;
}

void ExGameSetTable::InternalSwap(ExGameSetTable* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.pb_tlist_.InternalSwap(&other->_impl_.pb_tlist_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.pb_tname_, &other->_impl_.pb_tname_, arena);
}

::google::protobuf::Metadata ExGameSetTable::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_ExGameSetData_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
