// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ExGameSetData.proto
// Protobuf C++ Version: 5.27.0

#ifndef GOOGLE_PROTOBUF_INCLUDED_ExGameSetData_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_ExGameSetData_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5027000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_ExGameSetData_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_ExGameSetData_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_ExGameSetData_2eproto;
class ExGameSet;
struct ExGameSetDefaultTypeInternal;
extern ExGameSetDefaultTypeInternal _ExGameSet_default_instance_;
class ExGameSetTable;
struct ExGameSetTableDefaultTypeInternal;
extern ExGameSetTableDefaultTypeInternal _ExGameSetTable_default_instance_;
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google


// ===================================================================


// -------------------------------------------------------------------

class ExGameSet final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:ExGameSet) */ {
 public:
  inline ExGameSet() : ExGameSet(nullptr) {}
  ~ExGameSet() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ExGameSet(
      ::google::protobuf::internal::ConstantInitialized);

  inline ExGameSet(const ExGameSet& from) : ExGameSet(nullptr, from) {}
  inline ExGameSet(ExGameSet&& from) noexcept
      : ExGameSet(nullptr, std::move(from)) {}
  inline ExGameSet& operator=(const ExGameSet& from) {
    CopyFrom(from);
    return *this;
  }
  inline ExGameSet& operator=(ExGameSet&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ExGameSet& default_instance() {
    return *internal_default_instance();
  }
  static inline const ExGameSet* internal_default_instance() {
    return reinterpret_cast<const ExGameSet*>(
        &_ExGameSet_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(ExGameSet& a, ExGameSet& b) { a.Swap(&b); }
  inline void Swap(ExGameSet* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ExGameSet* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ExGameSet* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::Message::DefaultConstruct<ExGameSet>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ExGameSet& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const ExGameSet& from) { ExGameSet::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return IsInitializedImpl(*this);
  }

  private:
  static bool IsInitializedImpl(const MessageLite& msg);

  public:
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(ExGameSet* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "ExGameSet"; }

 protected:
  explicit ExGameSet(::google::protobuf::Arena* arena);
  ExGameSet(::google::protobuf::Arena* arena, const ExGameSet& from);
  ExGameSet(::google::protobuf::Arena* arena, ExGameSet&& from) noexcept
      : ExGameSet(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const final;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kPbVTupleIntFieldNumber = 8,
    kPbVTupleStrFieldNumber = 9,
    kPbVTupleFloatFieldNumber = 10,
    kPbKeyFieldNumber = 3,
    kPbDescFieldNumber = 4,
    kPbVStrFieldNumber = 6,
    kPbIdFieldNumber = 1,
    kPbTypeFieldNumber = 2,
    kPbVIntFieldNumber = 5,
    kPbVFloatFieldNumber = 7,
  };
  // repeated int32 pb_v_tuple_int = 8;
  int pb_v_tuple_int_size() const;
  private:
  int _internal_pb_v_tuple_int_size() const;

  public:
  void clear_pb_v_tuple_int() ;
  ::int32_t pb_v_tuple_int(int index) const;
  void set_pb_v_tuple_int(int index, ::int32_t value);
  void add_pb_v_tuple_int(::int32_t value);
  const ::google::protobuf::RepeatedField<::int32_t>& pb_v_tuple_int() const;
  ::google::protobuf::RepeatedField<::int32_t>* mutable_pb_v_tuple_int();

  private:
  const ::google::protobuf::RepeatedField<::int32_t>& _internal_pb_v_tuple_int() const;
  ::google::protobuf::RepeatedField<::int32_t>* _internal_mutable_pb_v_tuple_int();

  public:
  // repeated string pb_v_tuple_str = 9;
  int pb_v_tuple_str_size() const;
  private:
  int _internal_pb_v_tuple_str_size() const;

  public:
  void clear_pb_v_tuple_str() ;
  const std::string& pb_v_tuple_str(int index) const;
  std::string* mutable_pb_v_tuple_str(int index);
  void set_pb_v_tuple_str(int index, const std::string& value);
  void set_pb_v_tuple_str(int index, std::string&& value);
  void set_pb_v_tuple_str(int index, const char* value);
  void set_pb_v_tuple_str(int index, const char* value, std::size_t size);
  void set_pb_v_tuple_str(int index, absl::string_view value);
  std::string* add_pb_v_tuple_str();
  void add_pb_v_tuple_str(const std::string& value);
  void add_pb_v_tuple_str(std::string&& value);
  void add_pb_v_tuple_str(const char* value);
  void add_pb_v_tuple_str(const char* value, std::size_t size);
  void add_pb_v_tuple_str(absl::string_view value);
  const ::google::protobuf::RepeatedPtrField<std::string>& pb_v_tuple_str() const;
  ::google::protobuf::RepeatedPtrField<std::string>* mutable_pb_v_tuple_str();

  private:
  const ::google::protobuf::RepeatedPtrField<std::string>& _internal_pb_v_tuple_str() const;
  ::google::protobuf::RepeatedPtrField<std::string>* _internal_mutable_pb_v_tuple_str();

  public:
  // repeated float pb_v_tuple_float = 10;
  int pb_v_tuple_float_size() const;
  private:
  int _internal_pb_v_tuple_float_size() const;

  public:
  void clear_pb_v_tuple_float() ;
  float pb_v_tuple_float(int index) const;
  void set_pb_v_tuple_float(int index, float value);
  void add_pb_v_tuple_float(float value);
  const ::google::protobuf::RepeatedField<float>& pb_v_tuple_float() const;
  ::google::protobuf::RepeatedField<float>* mutable_pb_v_tuple_float();

  private:
  const ::google::protobuf::RepeatedField<float>& _internal_pb_v_tuple_float() const;
  ::google::protobuf::RepeatedField<float>* _internal_mutable_pb_v_tuple_float();

  public:
  // optional string pb_key = 3;
  bool has_pb_key() const;
  void clear_pb_key() ;
  const std::string& pb_key() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_pb_key(Arg_&& arg, Args_... args);
  std::string* mutable_pb_key();
  PROTOBUF_NODISCARD std::string* release_pb_key();
  void set_allocated_pb_key(std::string* value);

  private:
  const std::string& _internal_pb_key() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_pb_key(
      const std::string& value);
  std::string* _internal_mutable_pb_key();

  public:
  // optional string pb_desc = 4;
  bool has_pb_desc() const;
  void clear_pb_desc() ;
  const std::string& pb_desc() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_pb_desc(Arg_&& arg, Args_... args);
  std::string* mutable_pb_desc();
  PROTOBUF_NODISCARD std::string* release_pb_desc();
  void set_allocated_pb_desc(std::string* value);

  private:
  const std::string& _internal_pb_desc() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_pb_desc(
      const std::string& value);
  std::string* _internal_mutable_pb_desc();

  public:
  // optional string pb_v_str = 6;
  bool has_pb_v_str() const;
  void clear_pb_v_str() ;
  const std::string& pb_v_str() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_pb_v_str(Arg_&& arg, Args_... args);
  std::string* mutable_pb_v_str();
  PROTOBUF_NODISCARD std::string* release_pb_v_str();
  void set_allocated_pb_v_str(std::string* value);

  private:
  const std::string& _internal_pb_v_str() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_pb_v_str(
      const std::string& value);
  std::string* _internal_mutable_pb_v_str();

  public:
  // required int32 pb_id = 1;
  bool has_pb_id() const;
  void clear_pb_id() ;
  ::int32_t pb_id() const;
  void set_pb_id(::int32_t value);

  private:
  ::int32_t _internal_pb_id() const;
  void _internal_set_pb_id(::int32_t value);

  public:
  // optional int32 pb_type = 2;
  bool has_pb_type() const;
  void clear_pb_type() ;
  ::int32_t pb_type() const;
  void set_pb_type(::int32_t value);

  private:
  ::int32_t _internal_pb_type() const;
  void _internal_set_pb_type(::int32_t value);

  public:
  // optional int32 pb_v_int = 5;
  bool has_pb_v_int() const;
  void clear_pb_v_int() ;
  ::int32_t pb_v_int() const;
  void set_pb_v_int(::int32_t value);

  private:
  ::int32_t _internal_pb_v_int() const;
  void _internal_set_pb_v_int(::int32_t value);

  public:
  // optional float pb_v_float = 7;
  bool has_pb_v_float() const;
  void clear_pb_v_float() ;
  float pb_v_float() const;
  void set_pb_v_float(float value);

  private:
  float _internal_pb_v_float() const;
  void _internal_set_pb_v_float(float value);

  public:
  // @@protoc_insertion_point(class_scope:ExGameSet)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      4, 10, 0,
      61, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_ExGameSet_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const ExGameSet& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedField<::int32_t> pb_v_tuple_int_;
    ::google::protobuf::RepeatedPtrField<std::string> pb_v_tuple_str_;
    ::google::protobuf::RepeatedField<float> pb_v_tuple_float_;
    ::google::protobuf::internal::ArenaStringPtr pb_key_;
    ::google::protobuf::internal::ArenaStringPtr pb_desc_;
    ::google::protobuf::internal::ArenaStringPtr pb_v_str_;
    ::int32_t pb_id_;
    ::int32_t pb_type_;
    ::int32_t pb_v_int_;
    float pb_v_float_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ExGameSetData_2eproto;
};
// -------------------------------------------------------------------

class ExGameSetTable final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:ExGameSetTable) */ {
 public:
  inline ExGameSetTable() : ExGameSetTable(nullptr) {}
  ~ExGameSetTable() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ExGameSetTable(
      ::google::protobuf::internal::ConstantInitialized);

  inline ExGameSetTable(const ExGameSetTable& from) : ExGameSetTable(nullptr, from) {}
  inline ExGameSetTable(ExGameSetTable&& from) noexcept
      : ExGameSetTable(nullptr, std::move(from)) {}
  inline ExGameSetTable& operator=(const ExGameSetTable& from) {
    CopyFrom(from);
    return *this;
  }
  inline ExGameSetTable& operator=(ExGameSetTable&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ExGameSetTable& default_instance() {
    return *internal_default_instance();
  }
  static inline const ExGameSetTable* internal_default_instance() {
    return reinterpret_cast<const ExGameSetTable*>(
        &_ExGameSetTable_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(ExGameSetTable& a, ExGameSetTable& b) { a.Swap(&b); }
  inline void Swap(ExGameSetTable* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ExGameSetTable* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ExGameSetTable* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::Message::DefaultConstruct<ExGameSetTable>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ExGameSetTable& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const ExGameSetTable& from) { ExGameSetTable::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return IsInitializedImpl(*this);
  }

  private:
  static bool IsInitializedImpl(const MessageLite& msg);

  public:
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(ExGameSetTable* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "ExGameSetTable"; }

 protected:
  explicit ExGameSetTable(::google::protobuf::Arena* arena);
  ExGameSetTable(::google::protobuf::Arena* arena, const ExGameSetTable& from);
  ExGameSetTable(::google::protobuf::Arena* arena, ExGameSetTable&& from) noexcept
      : ExGameSetTable(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const final;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kPbTlistFieldNumber = 2,
    kPbTnameFieldNumber = 1,
  };
  // repeated .ExGameSet pb_tlist = 2;
  int pb_tlist_size() const;
  private:
  int _internal_pb_tlist_size() const;

  public:
  void clear_pb_tlist() ;
  ::ExGameSet* mutable_pb_tlist(int index);
  ::google::protobuf::RepeatedPtrField<::ExGameSet>* mutable_pb_tlist();

  private:
  const ::google::protobuf::RepeatedPtrField<::ExGameSet>& _internal_pb_tlist() const;
  ::google::protobuf::RepeatedPtrField<::ExGameSet>* _internal_mutable_pb_tlist();
  public:
  const ::ExGameSet& pb_tlist(int index) const;
  ::ExGameSet* add_pb_tlist();
  const ::google::protobuf::RepeatedPtrField<::ExGameSet>& pb_tlist() const;
  // optional string pb_tname = 1;
  bool has_pb_tname() const;
  void clear_pb_tname() ;
  const std::string& pb_tname() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_pb_tname(Arg_&& arg, Args_... args);
  std::string* mutable_pb_tname();
  PROTOBUF_NODISCARD std::string* release_pb_tname();
  void set_allocated_pb_tname(std::string* value);

  private:
  const std::string& _internal_pb_tname() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_pb_tname(
      const std::string& value);
  std::string* _internal_mutable_pb_tname();

  public:
  // @@protoc_insertion_point(class_scope:ExGameSetTable)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 1,
      31, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_ExGameSetTable_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const ExGameSetTable& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField< ::ExGameSet > pb_tlist_;
    ::google::protobuf::internal::ArenaStringPtr pb_tname_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ExGameSetData_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// ExGameSet

// required int32 pb_id = 1;
inline bool ExGameSet::has_pb_id() const {
  bool value = (_impl_._has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline void ExGameSet::clear_pb_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pb_id_ = 0;
  _impl_._has_bits_[0] &= ~0x00000008u;
}
inline ::int32_t ExGameSet::pb_id() const {
  // @@protoc_insertion_point(field_get:ExGameSet.pb_id)
  return _internal_pb_id();
}
inline void ExGameSet::set_pb_id(::int32_t value) {
  _internal_set_pb_id(value);
  _impl_._has_bits_[0] |= 0x00000008u;
  // @@protoc_insertion_point(field_set:ExGameSet.pb_id)
}
inline ::int32_t ExGameSet::_internal_pb_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.pb_id_;
}
inline void ExGameSet::_internal_set_pb_id(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pb_id_ = value;
}

// optional int32 pb_type = 2;
inline bool ExGameSet::has_pb_type() const {
  bool value = (_impl_._has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline void ExGameSet::clear_pb_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pb_type_ = 0;
  _impl_._has_bits_[0] &= ~0x00000010u;
}
inline ::int32_t ExGameSet::pb_type() const {
  // @@protoc_insertion_point(field_get:ExGameSet.pb_type)
  return _internal_pb_type();
}
inline void ExGameSet::set_pb_type(::int32_t value) {
  _internal_set_pb_type(value);
  _impl_._has_bits_[0] |= 0x00000010u;
  // @@protoc_insertion_point(field_set:ExGameSet.pb_type)
}
inline ::int32_t ExGameSet::_internal_pb_type() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.pb_type_;
}
inline void ExGameSet::_internal_set_pb_type(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pb_type_ = value;
}

// optional string pb_key = 3;
inline bool ExGameSet::has_pb_key() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void ExGameSet::clear_pb_key() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pb_key_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& ExGameSet::pb_key() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:ExGameSet.pb_key)
  return _internal_pb_key();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void ExGameSet::set_pb_key(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.pb_key_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:ExGameSet.pb_key)
}
inline std::string* ExGameSet::mutable_pb_key() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_pb_key();
  // @@protoc_insertion_point(field_mutable:ExGameSet.pb_key)
  return _s;
}
inline const std::string& ExGameSet::_internal_pb_key() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.pb_key_.Get();
}
inline void ExGameSet::_internal_set_pb_key(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.pb_key_.Set(value, GetArena());
}
inline std::string* ExGameSet::_internal_mutable_pb_key() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.pb_key_.Mutable( GetArena());
}
inline std::string* ExGameSet::release_pb_key() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:ExGameSet.pb_key)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.pb_key_.Release();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.pb_key_.Set("", GetArena());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return released;
}
inline void ExGameSet::set_allocated_pb_key(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.pb_key_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.pb_key_.IsDefault()) {
          _impl_.pb_key_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ExGameSet.pb_key)
}

// optional string pb_desc = 4;
inline bool ExGameSet::has_pb_desc() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline void ExGameSet::clear_pb_desc() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pb_desc_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const std::string& ExGameSet::pb_desc() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:ExGameSet.pb_desc)
  return _internal_pb_desc();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void ExGameSet::set_pb_desc(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.pb_desc_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:ExGameSet.pb_desc)
}
inline std::string* ExGameSet::mutable_pb_desc() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_pb_desc();
  // @@protoc_insertion_point(field_mutable:ExGameSet.pb_desc)
  return _s;
}
inline const std::string& ExGameSet::_internal_pb_desc() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.pb_desc_.Get();
}
inline void ExGameSet::_internal_set_pb_desc(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.pb_desc_.Set(value, GetArena());
}
inline std::string* ExGameSet::_internal_mutable_pb_desc() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  return _impl_.pb_desc_.Mutable( GetArena());
}
inline std::string* ExGameSet::release_pb_desc() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:ExGameSet.pb_desc)
  if ((_impl_._has_bits_[0] & 0x00000002u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000002u;
  auto* released = _impl_.pb_desc_.Release();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.pb_desc_.Set("", GetArena());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return released;
}
inline void ExGameSet::set_allocated_pb_desc(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  _impl_.pb_desc_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.pb_desc_.IsDefault()) {
          _impl_.pb_desc_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ExGameSet.pb_desc)
}

// optional int32 pb_v_int = 5;
inline bool ExGameSet::has_pb_v_int() const {
  bool value = (_impl_._has_bits_[0] & 0x00000020u) != 0;
  return value;
}
inline void ExGameSet::clear_pb_v_int() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pb_v_int_ = 0;
  _impl_._has_bits_[0] &= ~0x00000020u;
}
inline ::int32_t ExGameSet::pb_v_int() const {
  // @@protoc_insertion_point(field_get:ExGameSet.pb_v_int)
  return _internal_pb_v_int();
}
inline void ExGameSet::set_pb_v_int(::int32_t value) {
  _internal_set_pb_v_int(value);
  _impl_._has_bits_[0] |= 0x00000020u;
  // @@protoc_insertion_point(field_set:ExGameSet.pb_v_int)
}
inline ::int32_t ExGameSet::_internal_pb_v_int() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.pb_v_int_;
}
inline void ExGameSet::_internal_set_pb_v_int(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pb_v_int_ = value;
}

// optional string pb_v_str = 6;
inline bool ExGameSet::has_pb_v_str() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline void ExGameSet::clear_pb_v_str() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pb_v_str_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline const std::string& ExGameSet::pb_v_str() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:ExGameSet.pb_v_str)
  return _internal_pb_v_str();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void ExGameSet::set_pb_v_str(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.pb_v_str_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:ExGameSet.pb_v_str)
}
inline std::string* ExGameSet::mutable_pb_v_str() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_pb_v_str();
  // @@protoc_insertion_point(field_mutable:ExGameSet.pb_v_str)
  return _s;
}
inline const std::string& ExGameSet::_internal_pb_v_str() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.pb_v_str_.Get();
}
inline void ExGameSet::_internal_set_pb_v_str(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.pb_v_str_.Set(value, GetArena());
}
inline std::string* ExGameSet::_internal_mutable_pb_v_str() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000004u;
  return _impl_.pb_v_str_.Mutable( GetArena());
}
inline std::string* ExGameSet::release_pb_v_str() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:ExGameSet.pb_v_str)
  if ((_impl_._has_bits_[0] & 0x00000004u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000004u;
  auto* released = _impl_.pb_v_str_.Release();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.pb_v_str_.Set("", GetArena());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return released;
}
inline void ExGameSet::set_allocated_pb_v_str(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000004u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000004u;
  }
  _impl_.pb_v_str_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.pb_v_str_.IsDefault()) {
          _impl_.pb_v_str_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ExGameSet.pb_v_str)
}

// optional float pb_v_float = 7;
inline bool ExGameSet::has_pb_v_float() const {
  bool value = (_impl_._has_bits_[0] & 0x00000040u) != 0;
  return value;
}
inline void ExGameSet::clear_pb_v_float() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pb_v_float_ = 0;
  _impl_._has_bits_[0] &= ~0x00000040u;
}
inline float ExGameSet::pb_v_float() const {
  // @@protoc_insertion_point(field_get:ExGameSet.pb_v_float)
  return _internal_pb_v_float();
}
inline void ExGameSet::set_pb_v_float(float value) {
  _internal_set_pb_v_float(value);
  _impl_._has_bits_[0] |= 0x00000040u;
  // @@protoc_insertion_point(field_set:ExGameSet.pb_v_float)
}
inline float ExGameSet::_internal_pb_v_float() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.pb_v_float_;
}
inline void ExGameSet::_internal_set_pb_v_float(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pb_v_float_ = value;
}

// repeated int32 pb_v_tuple_int = 8;
inline int ExGameSet::_internal_pb_v_tuple_int_size() const {
  return _internal_pb_v_tuple_int().size();
}
inline int ExGameSet::pb_v_tuple_int_size() const {
  return _internal_pb_v_tuple_int_size();
}
inline void ExGameSet::clear_pb_v_tuple_int() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pb_v_tuple_int_.Clear();
}
inline ::int32_t ExGameSet::pb_v_tuple_int(int index) const {
  // @@protoc_insertion_point(field_get:ExGameSet.pb_v_tuple_int)
  return _internal_pb_v_tuple_int().Get(index);
}
inline void ExGameSet::set_pb_v_tuple_int(int index, ::int32_t value) {
  _internal_mutable_pb_v_tuple_int()->Set(index, value);
  // @@protoc_insertion_point(field_set:ExGameSet.pb_v_tuple_int)
}
inline void ExGameSet::add_pb_v_tuple_int(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_pb_v_tuple_int()->Add(value);
  // @@protoc_insertion_point(field_add:ExGameSet.pb_v_tuple_int)
}
inline const ::google::protobuf::RepeatedField<::int32_t>& ExGameSet::pb_v_tuple_int() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:ExGameSet.pb_v_tuple_int)
  return _internal_pb_v_tuple_int();
}
inline ::google::protobuf::RepeatedField<::int32_t>* ExGameSet::mutable_pb_v_tuple_int()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:ExGameSet.pb_v_tuple_int)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_pb_v_tuple_int();
}
inline const ::google::protobuf::RepeatedField<::int32_t>&
ExGameSet::_internal_pb_v_tuple_int() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.pb_v_tuple_int_;
}
inline ::google::protobuf::RepeatedField<::int32_t>* ExGameSet::_internal_mutable_pb_v_tuple_int() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.pb_v_tuple_int_;
}

// repeated string pb_v_tuple_str = 9;
inline int ExGameSet::_internal_pb_v_tuple_str_size() const {
  return _internal_pb_v_tuple_str().size();
}
inline int ExGameSet::pb_v_tuple_str_size() const {
  return _internal_pb_v_tuple_str_size();
}
inline void ExGameSet::clear_pb_v_tuple_str() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pb_v_tuple_str_.Clear();
}
inline std::string* ExGameSet::add_pb_v_tuple_str()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  std::string* _s = _internal_mutable_pb_v_tuple_str()->Add();
  // @@protoc_insertion_point(field_add_mutable:ExGameSet.pb_v_tuple_str)
  return _s;
}
inline const std::string& ExGameSet::pb_v_tuple_str(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:ExGameSet.pb_v_tuple_str)
  return _internal_pb_v_tuple_str().Get(index);
}
inline std::string* ExGameSet::mutable_pb_v_tuple_str(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:ExGameSet.pb_v_tuple_str)
  return _internal_mutable_pb_v_tuple_str()->Mutable(index);
}
inline void ExGameSet::set_pb_v_tuple_str(int index, const std::string& value) {
  _internal_mutable_pb_v_tuple_str()->Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set:ExGameSet.pb_v_tuple_str)
}
inline void ExGameSet::set_pb_v_tuple_str(int index, std::string&& value) {
  _internal_mutable_pb_v_tuple_str()->Mutable(index)->assign(std::move(value));
  // @@protoc_insertion_point(field_set:ExGameSet.pb_v_tuple_str)
}
inline void ExGameSet::set_pb_v_tuple_str(int index, const char* value) {
  ABSL_DCHECK(value != nullptr);
  _internal_mutable_pb_v_tuple_str()->Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:ExGameSet.pb_v_tuple_str)
}
inline void ExGameSet::set_pb_v_tuple_str(int index, const char* value,
                              std::size_t size) {
  _internal_mutable_pb_v_tuple_str()->Mutable(index)->assign(
      reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:ExGameSet.pb_v_tuple_str)
}
inline void ExGameSet::set_pb_v_tuple_str(int index, absl::string_view value) {
  _internal_mutable_pb_v_tuple_str()->Mutable(index)->assign(
      value.data(), value.size());
  // @@protoc_insertion_point(field_set_string_piece:ExGameSet.pb_v_tuple_str)
}
inline void ExGameSet::add_pb_v_tuple_str(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_pb_v_tuple_str()->Add()->assign(value);
  // @@protoc_insertion_point(field_add:ExGameSet.pb_v_tuple_str)
}
inline void ExGameSet::add_pb_v_tuple_str(std::string&& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_pb_v_tuple_str()->Add(std::move(value));
  // @@protoc_insertion_point(field_add:ExGameSet.pb_v_tuple_str)
}
inline void ExGameSet::add_pb_v_tuple_str(const char* value) {
  ABSL_DCHECK(value != nullptr);
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_pb_v_tuple_str()->Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:ExGameSet.pb_v_tuple_str)
}
inline void ExGameSet::add_pb_v_tuple_str(const char* value, std::size_t size) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_pb_v_tuple_str()->Add()->assign(
      reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:ExGameSet.pb_v_tuple_str)
}
inline void ExGameSet::add_pb_v_tuple_str(absl::string_view value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_pb_v_tuple_str()->Add()->assign(value.data(),
                                                     value.size());
  // @@protoc_insertion_point(field_add_string_piece:ExGameSet.pb_v_tuple_str)
}
inline const ::google::protobuf::RepeatedPtrField<std::string>&
ExGameSet::pb_v_tuple_str() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:ExGameSet.pb_v_tuple_str)
  return _internal_pb_v_tuple_str();
}
inline ::google::protobuf::RepeatedPtrField<std::string>*
ExGameSet::mutable_pb_v_tuple_str() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:ExGameSet.pb_v_tuple_str)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_pb_v_tuple_str();
}
inline const ::google::protobuf::RepeatedPtrField<std::string>&
ExGameSet::_internal_pb_v_tuple_str() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.pb_v_tuple_str_;
}
inline ::google::protobuf::RepeatedPtrField<std::string>*
ExGameSet::_internal_mutable_pb_v_tuple_str() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.pb_v_tuple_str_;
}

// repeated float pb_v_tuple_float = 10;
inline int ExGameSet::_internal_pb_v_tuple_float_size() const {
  return _internal_pb_v_tuple_float().size();
}
inline int ExGameSet::pb_v_tuple_float_size() const {
  return _internal_pb_v_tuple_float_size();
}
inline void ExGameSet::clear_pb_v_tuple_float() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pb_v_tuple_float_.Clear();
}
inline float ExGameSet::pb_v_tuple_float(int index) const {
  // @@protoc_insertion_point(field_get:ExGameSet.pb_v_tuple_float)
  return _internal_pb_v_tuple_float().Get(index);
}
inline void ExGameSet::set_pb_v_tuple_float(int index, float value) {
  _internal_mutable_pb_v_tuple_float()->Set(index, value);
  // @@protoc_insertion_point(field_set:ExGameSet.pb_v_tuple_float)
}
inline void ExGameSet::add_pb_v_tuple_float(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_pb_v_tuple_float()->Add(value);
  // @@protoc_insertion_point(field_add:ExGameSet.pb_v_tuple_float)
}
inline const ::google::protobuf::RepeatedField<float>& ExGameSet::pb_v_tuple_float() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:ExGameSet.pb_v_tuple_float)
  return _internal_pb_v_tuple_float();
}
inline ::google::protobuf::RepeatedField<float>* ExGameSet::mutable_pb_v_tuple_float()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:ExGameSet.pb_v_tuple_float)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_pb_v_tuple_float();
}
inline const ::google::protobuf::RepeatedField<float>&
ExGameSet::_internal_pb_v_tuple_float() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.pb_v_tuple_float_;
}
inline ::google::protobuf::RepeatedField<float>* ExGameSet::_internal_mutable_pb_v_tuple_float() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.pb_v_tuple_float_;
}

// -------------------------------------------------------------------

// ExGameSetTable

// optional string pb_tname = 1;
inline bool ExGameSetTable::has_pb_tname() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void ExGameSetTable::clear_pb_tname() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pb_tname_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& ExGameSetTable::pb_tname() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:ExGameSetTable.pb_tname)
  return _internal_pb_tname();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void ExGameSetTable::set_pb_tname(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.pb_tname_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:ExGameSetTable.pb_tname)
}
inline std::string* ExGameSetTable::mutable_pb_tname() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_pb_tname();
  // @@protoc_insertion_point(field_mutable:ExGameSetTable.pb_tname)
  return _s;
}
inline const std::string& ExGameSetTable::_internal_pb_tname() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.pb_tname_.Get();
}
inline void ExGameSetTable::_internal_set_pb_tname(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.pb_tname_.Set(value, GetArena());
}
inline std::string* ExGameSetTable::_internal_mutable_pb_tname() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.pb_tname_.Mutable( GetArena());
}
inline std::string* ExGameSetTable::release_pb_tname() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:ExGameSetTable.pb_tname)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.pb_tname_.Release();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.pb_tname_.Set("", GetArena());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return released;
}
inline void ExGameSetTable::set_allocated_pb_tname(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.pb_tname_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.pb_tname_.IsDefault()) {
          _impl_.pb_tname_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ExGameSetTable.pb_tname)
}

// repeated .ExGameSet pb_tlist = 2;
inline int ExGameSetTable::_internal_pb_tlist_size() const {
  return _internal_pb_tlist().size();
}
inline int ExGameSetTable::pb_tlist_size() const {
  return _internal_pb_tlist_size();
}
inline void ExGameSetTable::clear_pb_tlist() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pb_tlist_.Clear();
}
inline ::ExGameSet* ExGameSetTable::mutable_pb_tlist(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:ExGameSetTable.pb_tlist)
  return _internal_mutable_pb_tlist()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::ExGameSet>* ExGameSetTable::mutable_pb_tlist()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:ExGameSetTable.pb_tlist)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_pb_tlist();
}
inline const ::ExGameSet& ExGameSetTable::pb_tlist(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:ExGameSetTable.pb_tlist)
  return _internal_pb_tlist().Get(index);
}
inline ::ExGameSet* ExGameSetTable::add_pb_tlist() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::ExGameSet* _add = _internal_mutable_pb_tlist()->Add();
  // @@protoc_insertion_point(field_add:ExGameSetTable.pb_tlist)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::ExGameSet>& ExGameSetTable::pb_tlist() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:ExGameSetTable.pb_tlist)
  return _internal_pb_tlist();
}
inline const ::google::protobuf::RepeatedPtrField<::ExGameSet>&
ExGameSetTable::_internal_pb_tlist() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.pb_tlist_;
}
inline ::google::protobuf::RepeatedPtrField<::ExGameSet>*
ExGameSetTable::_internal_mutable_pb_tlist() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.pb_tlist_;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_ExGameSetData_2eproto_2epb_2eh
