// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ExGmtMsg.proto
// Protobuf C++ Version: 5.27.0

#include "ExGmtMsg.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;

inline constexpr ExGmtMsg::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        pb_args_{},
        pb_cmd_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        pb_sid_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        pb_uid_{::int64_t{0}},
        pb_nid_{::int64_t{0}},
        pb_srvid_{0},
        pb_ret_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ExGmtMsg::ExGmtMsg(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct ExGmtMsgDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ExGmtMsgDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ExGmtMsgDefaultTypeInternal() {}
  union {
    ExGmtMsg _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ExGmtMsgDefaultTypeInternal _ExGmtMsg_default_instance_;
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_ExGmtMsg_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_ExGmtMsg_2eproto = nullptr;
const ::uint32_t
    TableStruct_ExGmtMsg_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        PROTOBUF_FIELD_OFFSET(::ExGmtMsg, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::ExGmtMsg, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::ExGmtMsg, _impl_.pb_cmd_),
        PROTOBUF_FIELD_OFFSET(::ExGmtMsg, _impl_.pb_srvid_),
        PROTOBUF_FIELD_OFFSET(::ExGmtMsg, _impl_.pb_uid_),
        PROTOBUF_FIELD_OFFSET(::ExGmtMsg, _impl_.pb_args_),
        PROTOBUF_FIELD_OFFSET(::ExGmtMsg, _impl_.pb_sid_),
        PROTOBUF_FIELD_OFFSET(::ExGmtMsg, _impl_.pb_nid_),
        PROTOBUF_FIELD_OFFSET(::ExGmtMsg, _impl_.pb_ret_),
        0,
        4,
        2,
        ~0u,
        1,
        3,
        5,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, 15, -1, sizeof(::ExGmtMsg)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::_ExGmtMsg_default_instance_._instance,
};
const char descriptor_table_protodef_ExGmtMsg_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\016ExGmtMsg.proto\"}\n\010ExGmtMsg\022\016\n\006pb_cmd\030\001"
    " \001(\t\022\020\n\010pb_srvID\030\002 \001(\005\022\016\n\006pb_uid\030\003 \001(\003\022\017"
    "\n\007pb_args\030\004 \003(\t\022\016\n\006pb_sid\030\005 \001(\t\022\016\n\006pb_ni"
    "d\030\006 \001(\003\022\016\n\006pb_ret\030\n \001(\005"
};
static ::absl::once_flag descriptor_table_ExGmtMsg_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_ExGmtMsg_2eproto = {
    false,
    false,
    143,
    descriptor_table_protodef_ExGmtMsg_2eproto,
    "ExGmtMsg.proto",
    &descriptor_table_ExGmtMsg_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_ExGmtMsg_2eproto::offsets,
    file_level_enum_descriptors_ExGmtMsg_2eproto,
    file_level_service_descriptors_ExGmtMsg_2eproto,
};
// ===================================================================

class ExGmtMsg::_Internal {
 public:
  using HasBits =
      decltype(std::declval<ExGmtMsg>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(ExGmtMsg, _impl_._has_bits_);
};

ExGmtMsg::ExGmtMsg(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:ExGmtMsg)
}
inline PROTOBUF_NDEBUG_INLINE ExGmtMsg::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::ExGmtMsg& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        pb_args_{visibility, arena, from.pb_args_},
        pb_cmd_(arena, from.pb_cmd_),
        pb_sid_(arena, from.pb_sid_) {}

ExGmtMsg::ExGmtMsg(
    ::google::protobuf::Arena* arena,
    const ExGmtMsg& from)
    : ::google::protobuf::Message(arena) {
  ExGmtMsg* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, pb_uid_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, pb_uid_),
           offsetof(Impl_, pb_ret_) -
               offsetof(Impl_, pb_uid_) +
               sizeof(Impl_::pb_ret_));

  // @@protoc_insertion_point(copy_constructor:ExGmtMsg)
}
inline PROTOBUF_NDEBUG_INLINE ExGmtMsg::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        pb_args_{visibility, arena},
        pb_cmd_(arena),
        pb_sid_(arena) {}

inline void ExGmtMsg::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, pb_uid_),
           0,
           offsetof(Impl_, pb_ret_) -
               offsetof(Impl_, pb_uid_) +
               sizeof(Impl_::pb_ret_));
}
ExGmtMsg::~ExGmtMsg() {
  // @@protoc_insertion_point(destructor:ExGmtMsg)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void ExGmtMsg::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.pb_cmd_.Destroy();
  _impl_.pb_sid_.Destroy();
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
ExGmtMsg::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(ExGmtMsg, _impl_._cached_size_),
              false,
          },
          &ExGmtMsg::MergeImpl,
          &ExGmtMsg::kDescriptorMethods,
          &descriptor_table_ExGmtMsg_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 7, 0, 36, 2> ExGmtMsg::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(ExGmtMsg, _impl_._has_bits_),
    0, // no _extensions_
    10, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294966720,  // skipmap
    offsetof(decltype(_table_), field_entries),
    7,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_ExGmtMsg_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::ExGmtMsg>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // optional string pb_cmd = 1;
    {::_pbi::TcParser::FastSS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(ExGmtMsg, _impl_.pb_cmd_)}},
    // optional int32 pb_srvID = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ExGmtMsg, _impl_.pb_srvid_), 4>(),
     {16, 4, 0, PROTOBUF_FIELD_OFFSET(ExGmtMsg, _impl_.pb_srvid_)}},
    // optional int64 pb_uid = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(ExGmtMsg, _impl_.pb_uid_), 2>(),
     {24, 2, 0, PROTOBUF_FIELD_OFFSET(ExGmtMsg, _impl_.pb_uid_)}},
    // repeated string pb_args = 4;
    {::_pbi::TcParser::FastSR1,
     {34, 63, 0, PROTOBUF_FIELD_OFFSET(ExGmtMsg, _impl_.pb_args_)}},
    // optional string pb_sid = 5;
    {::_pbi::TcParser::FastSS1,
     {42, 1, 0, PROTOBUF_FIELD_OFFSET(ExGmtMsg, _impl_.pb_sid_)}},
    // optional int64 pb_nid = 6;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(ExGmtMsg, _impl_.pb_nid_), 3>(),
     {48, 3, 0, PROTOBUF_FIELD_OFFSET(ExGmtMsg, _impl_.pb_nid_)}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // optional string pb_cmd = 1;
    {PROTOBUF_FIELD_OFFSET(ExGmtMsg, _impl_.pb_cmd_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kRawString | ::_fl::kRepAString)},
    // optional int32 pb_srvID = 2;
    {PROTOBUF_FIELD_OFFSET(ExGmtMsg, _impl_.pb_srvid_), _Internal::kHasBitsOffset + 4, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // optional int64 pb_uid = 3;
    {PROTOBUF_FIELD_OFFSET(ExGmtMsg, _impl_.pb_uid_), _Internal::kHasBitsOffset + 2, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
    // repeated string pb_args = 4;
    {PROTOBUF_FIELD_OFFSET(ExGmtMsg, _impl_.pb_args_), -1, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kRawString | ::_fl::kRepSString)},
    // optional string pb_sid = 5;
    {PROTOBUF_FIELD_OFFSET(ExGmtMsg, _impl_.pb_sid_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kRawString | ::_fl::kRepAString)},
    // optional int64 pb_nid = 6;
    {PROTOBUF_FIELD_OFFSET(ExGmtMsg, _impl_.pb_nid_), _Internal::kHasBitsOffset + 3, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
    // optional int32 pb_ret = 10;
    {PROTOBUF_FIELD_OFFSET(ExGmtMsg, _impl_.pb_ret_), _Internal::kHasBitsOffset + 5, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
    "\10\6\0\0\7\6\0\0"
    "ExGmtMsg"
    "pb_cmd"
    "pb_args"
    "pb_sid"
  }},
};

PROTOBUF_NOINLINE void ExGmtMsg::Clear() {
// @@protoc_insertion_point(message_clear_start:ExGmtMsg)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.pb_args_.Clear();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _impl_.pb_cmd_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000002u) {
      _impl_.pb_sid_.ClearNonDefaultToEmpty();
    }
  }
  if (cached_has_bits & 0x0000003cu) {
    ::memset(&_impl_.pb_uid_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.pb_ret_) -
        reinterpret_cast<char*>(&_impl_.pb_uid_)) + sizeof(_impl_.pb_ret_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* ExGmtMsg::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ExGmtMsg)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // optional string pb_cmd = 1;
  if (cached_has_bits & 0x00000001u) {
    const std::string& _s = this->_internal_pb_cmd();
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(_s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormat::SERIALIZE,
                                "ExGmtMsg.pb_cmd");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // optional int32 pb_srvID = 2;
  if (cached_has_bits & 0x00000010u) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<2>(
            stream, this->_internal_pb_srvid(), target);
  }

  // optional int64 pb_uid = 3;
  if (cached_has_bits & 0x00000004u) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt64ToArrayWithField<3>(
            stream, this->_internal_pb_uid(), target);
  }

  // repeated string pb_args = 4;
  for (int i = 0, n = this->_internal_pb_args_size(); i < n; ++i) {
    const auto& s = this->_internal_pb_args().Get(i);
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(s.data(), static_cast<int>(s.length()), ::google::protobuf::internal::WireFormat::SERIALIZE,
                                "ExGmtMsg.pb_args");
    target = stream->WriteString(4, s, target);
  }

  // optional string pb_sid = 5;
  if (cached_has_bits & 0x00000002u) {
    const std::string& _s = this->_internal_pb_sid();
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(_s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormat::SERIALIZE,
                                "ExGmtMsg.pb_sid");
    target = stream->WriteStringMaybeAliased(5, _s, target);
  }

  // optional int64 pb_nid = 6;
  if (cached_has_bits & 0x00000008u) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt64ToArrayWithField<6>(
            stream, this->_internal_pb_nid(), target);
  }

  // optional int32 pb_ret = 10;
  if (cached_has_bits & 0x00000020u) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<10>(
            stream, this->_internal_pb_ret(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ExGmtMsg)
  return target;
}

::size_t ExGmtMsg::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ExGmtMsg)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(reinterpret_cast<const void*>(this));
  // repeated string pb_args = 4;
  total_size += 1 * ::google::protobuf::internal::FromIntSize(_internal_pb_args().size());
  for (int i = 0, n = _internal_pb_args().size(); i < n; ++i) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
        _internal_pb_args().Get(i));
  }
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x0000003fu) {
    // optional string pb_cmd = 1;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this->_internal_pb_cmd());
    }

    // optional string pb_sid = 5;
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this->_internal_pb_sid());
    }

    // optional int64 pb_uid = 3;
    if (cached_has_bits & 0x00000004u) {
      total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
          this->_internal_pb_uid());
    }

    // optional int64 pb_nid = 6;
    if (cached_has_bits & 0x00000008u) {
      total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
          this->_internal_pb_nid());
    }

    // optional int32 pb_srvID = 2;
    if (cached_has_bits & 0x00000010u) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
          this->_internal_pb_srvid());
    }

    // optional int32 pb_ret = 10;
    if (cached_has_bits & 0x00000020u) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
          this->_internal_pb_ret());
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void ExGmtMsg::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ExGmtMsg*>(&to_msg);
  auto& from = static_cast<const ExGmtMsg&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ExGmtMsg)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_pb_args()->MergeFrom(from._internal_pb_args());
  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x0000003fu) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_set_pb_cmd(from._internal_pb_cmd());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_internal_set_pb_sid(from._internal_pb_sid());
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_impl_.pb_uid_ = from._impl_.pb_uid_;
    }
    if (cached_has_bits & 0x00000008u) {
      _this->_impl_.pb_nid_ = from._impl_.pb_nid_;
    }
    if (cached_has_bits & 0x00000010u) {
      _this->_impl_.pb_srvid_ = from._impl_.pb_srvid_;
    }
    if (cached_has_bits & 0x00000020u) {
      _this->_impl_.pb_ret_ = from._impl_.pb_ret_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ExGmtMsg::CopyFrom(const ExGmtMsg& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ExGmtMsg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ExGmtMsg::InternalSwap(ExGmtMsg* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.pb_args_.InternalSwap(&other->_impl_.pb_args_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.pb_cmd_, &other->_impl_.pb_cmd_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.pb_sid_, &other->_impl_.pb_sid_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ExGmtMsg, _impl_.pb_ret_)
      + sizeof(ExGmtMsg::_impl_.pb_ret_)
      - PROTOBUF_FIELD_OFFSET(ExGmtMsg, _impl_.pb_uid_)>(
          reinterpret_cast<char*>(&_impl_.pb_uid_),
          reinterpret_cast<char*>(&other->_impl_.pb_uid_));
}

::google::protobuf::Metadata ExGmtMsg::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_ExGmtMsg_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
