// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ExGmtMsg.proto
// Protobuf C++ Version: 5.27.0

#ifndef GOOGLE_PROTOBUF_INCLUDED_ExGmtMsg_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_ExGmtMsg_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5027000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_ExGmtMsg_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_ExGmtMsg_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_ExGmtMsg_2eproto;
class ExGmtMsg;
struct ExGmtMsgDefaultTypeInternal;
extern ExGmtMsgDefaultTypeInternal _ExGmtMsg_default_instance_;
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google


// ===================================================================


// -------------------------------------------------------------------

class ExGmtMsg final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:ExGmtMsg) */ {
 public:
  inline ExGmtMsg() : ExGmtMsg(nullptr) {}
  ~ExGmtMsg() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ExGmtMsg(
      ::google::protobuf::internal::ConstantInitialized);

  inline ExGmtMsg(const ExGmtMsg& from) : ExGmtMsg(nullptr, from) {}
  inline ExGmtMsg(ExGmtMsg&& from) noexcept
      : ExGmtMsg(nullptr, std::move(from)) {}
  inline ExGmtMsg& operator=(const ExGmtMsg& from) {
    CopyFrom(from);
    return *this;
  }
  inline ExGmtMsg& operator=(ExGmtMsg&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ExGmtMsg& default_instance() {
    return *internal_default_instance();
  }
  static inline const ExGmtMsg* internal_default_instance() {
    return reinterpret_cast<const ExGmtMsg*>(
        &_ExGmtMsg_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(ExGmtMsg& a, ExGmtMsg& b) { a.Swap(&b); }
  inline void Swap(ExGmtMsg* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ExGmtMsg* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ExGmtMsg* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::Message::DefaultConstruct<ExGmtMsg>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ExGmtMsg& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const ExGmtMsg& from) { ExGmtMsg::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(ExGmtMsg* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "ExGmtMsg"; }

 protected:
  explicit ExGmtMsg(::google::protobuf::Arena* arena);
  ExGmtMsg(::google::protobuf::Arena* arena, const ExGmtMsg& from);
  ExGmtMsg(::google::protobuf::Arena* arena, ExGmtMsg&& from) noexcept
      : ExGmtMsg(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const final;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kPbArgsFieldNumber = 4,
    kPbCmdFieldNumber = 1,
    kPbSidFieldNumber = 5,
    kPbUidFieldNumber = 3,
    kPbNidFieldNumber = 6,
    kPbSrvIDFieldNumber = 2,
    kPbRetFieldNumber = 10,
  };
  // repeated string pb_args = 4;
  int pb_args_size() const;
  private:
  int _internal_pb_args_size() const;

  public:
  void clear_pb_args() ;
  const std::string& pb_args(int index) const;
  std::string* mutable_pb_args(int index);
  void set_pb_args(int index, const std::string& value);
  void set_pb_args(int index, std::string&& value);
  void set_pb_args(int index, const char* value);
  void set_pb_args(int index, const char* value, std::size_t size);
  void set_pb_args(int index, absl::string_view value);
  std::string* add_pb_args();
  void add_pb_args(const std::string& value);
  void add_pb_args(std::string&& value);
  void add_pb_args(const char* value);
  void add_pb_args(const char* value, std::size_t size);
  void add_pb_args(absl::string_view value);
  const ::google::protobuf::RepeatedPtrField<std::string>& pb_args() const;
  ::google::protobuf::RepeatedPtrField<std::string>* mutable_pb_args();

  private:
  const ::google::protobuf::RepeatedPtrField<std::string>& _internal_pb_args() const;
  ::google::protobuf::RepeatedPtrField<std::string>* _internal_mutable_pb_args();

  public:
  // optional string pb_cmd = 1;
  bool has_pb_cmd() const;
  void clear_pb_cmd() ;
  const std::string& pb_cmd() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_pb_cmd(Arg_&& arg, Args_... args);
  std::string* mutable_pb_cmd();
  PROTOBUF_NODISCARD std::string* release_pb_cmd();
  void set_allocated_pb_cmd(std::string* value);

  private:
  const std::string& _internal_pb_cmd() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_pb_cmd(
      const std::string& value);
  std::string* _internal_mutable_pb_cmd();

  public:
  // optional string pb_sid = 5;
  bool has_pb_sid() const;
  void clear_pb_sid() ;
  const std::string& pb_sid() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_pb_sid(Arg_&& arg, Args_... args);
  std::string* mutable_pb_sid();
  PROTOBUF_NODISCARD std::string* release_pb_sid();
  void set_allocated_pb_sid(std::string* value);

  private:
  const std::string& _internal_pb_sid() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_pb_sid(
      const std::string& value);
  std::string* _internal_mutable_pb_sid();

  public:
  // optional int64 pb_uid = 3;
  bool has_pb_uid() const;
  void clear_pb_uid() ;
  ::int64_t pb_uid() const;
  void set_pb_uid(::int64_t value);

  private:
  ::int64_t _internal_pb_uid() const;
  void _internal_set_pb_uid(::int64_t value);

  public:
  // optional int64 pb_nid = 6;
  bool has_pb_nid() const;
  void clear_pb_nid() ;
  ::int64_t pb_nid() const;
  void set_pb_nid(::int64_t value);

  private:
  ::int64_t _internal_pb_nid() const;
  void _internal_set_pb_nid(::int64_t value);

  public:
  // optional int32 pb_srvID = 2;
  bool has_pb_srvid() const;
  void clear_pb_srvid() ;
  ::int32_t pb_srvid() const;
  void set_pb_srvid(::int32_t value);

  private:
  ::int32_t _internal_pb_srvid() const;
  void _internal_set_pb_srvid(::int32_t value);

  public:
  // optional int32 pb_ret = 10;
  bool has_pb_ret() const;
  void clear_pb_ret() ;
  ::int32_t pb_ret() const;
  void set_pb_ret(::int32_t value);

  private:
  ::int32_t _internal_pb_ret() const;
  void _internal_set_pb_ret(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:ExGmtMsg)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      3, 7, 0,
      36, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_ExGmtMsg_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const ExGmtMsg& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField<std::string> pb_args_;
    ::google::protobuf::internal::ArenaStringPtr pb_cmd_;
    ::google::protobuf::internal::ArenaStringPtr pb_sid_;
    ::int64_t pb_uid_;
    ::int64_t pb_nid_;
    ::int32_t pb_srvid_;
    ::int32_t pb_ret_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ExGmtMsg_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// ExGmtMsg

// optional string pb_cmd = 1;
inline bool ExGmtMsg::has_pb_cmd() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void ExGmtMsg::clear_pb_cmd() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pb_cmd_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& ExGmtMsg::pb_cmd() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:ExGmtMsg.pb_cmd)
  return _internal_pb_cmd();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void ExGmtMsg::set_pb_cmd(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.pb_cmd_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:ExGmtMsg.pb_cmd)
}
inline std::string* ExGmtMsg::mutable_pb_cmd() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_pb_cmd();
  // @@protoc_insertion_point(field_mutable:ExGmtMsg.pb_cmd)
  return _s;
}
inline const std::string& ExGmtMsg::_internal_pb_cmd() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.pb_cmd_.Get();
}
inline void ExGmtMsg::_internal_set_pb_cmd(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.pb_cmd_.Set(value, GetArena());
}
inline std::string* ExGmtMsg::_internal_mutable_pb_cmd() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.pb_cmd_.Mutable( GetArena());
}
inline std::string* ExGmtMsg::release_pb_cmd() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:ExGmtMsg.pb_cmd)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.pb_cmd_.Release();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.pb_cmd_.Set("", GetArena());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return released;
}
inline void ExGmtMsg::set_allocated_pb_cmd(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.pb_cmd_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.pb_cmd_.IsDefault()) {
          _impl_.pb_cmd_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ExGmtMsg.pb_cmd)
}

// optional int32 pb_srvID = 2;
inline bool ExGmtMsg::has_pb_srvid() const {
  bool value = (_impl_._has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline void ExGmtMsg::clear_pb_srvid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pb_srvid_ = 0;
  _impl_._has_bits_[0] &= ~0x00000010u;
}
inline ::int32_t ExGmtMsg::pb_srvid() const {
  // @@protoc_insertion_point(field_get:ExGmtMsg.pb_srvID)
  return _internal_pb_srvid();
}
inline void ExGmtMsg::set_pb_srvid(::int32_t value) {
  _internal_set_pb_srvid(value);
  _impl_._has_bits_[0] |= 0x00000010u;
  // @@protoc_insertion_point(field_set:ExGmtMsg.pb_srvID)
}
inline ::int32_t ExGmtMsg::_internal_pb_srvid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.pb_srvid_;
}
inline void ExGmtMsg::_internal_set_pb_srvid(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pb_srvid_ = value;
}

// optional int64 pb_uid = 3;
inline bool ExGmtMsg::has_pb_uid() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline void ExGmtMsg::clear_pb_uid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pb_uid_ = ::int64_t{0};
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline ::int64_t ExGmtMsg::pb_uid() const {
  // @@protoc_insertion_point(field_get:ExGmtMsg.pb_uid)
  return _internal_pb_uid();
}
inline void ExGmtMsg::set_pb_uid(::int64_t value) {
  _internal_set_pb_uid(value);
  _impl_._has_bits_[0] |= 0x00000004u;
  // @@protoc_insertion_point(field_set:ExGmtMsg.pb_uid)
}
inline ::int64_t ExGmtMsg::_internal_pb_uid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.pb_uid_;
}
inline void ExGmtMsg::_internal_set_pb_uid(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pb_uid_ = value;
}

// repeated string pb_args = 4;
inline int ExGmtMsg::_internal_pb_args_size() const {
  return _internal_pb_args().size();
}
inline int ExGmtMsg::pb_args_size() const {
  return _internal_pb_args_size();
}
inline void ExGmtMsg::clear_pb_args() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pb_args_.Clear();
}
inline std::string* ExGmtMsg::add_pb_args()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  std::string* _s = _internal_mutable_pb_args()->Add();
  // @@protoc_insertion_point(field_add_mutable:ExGmtMsg.pb_args)
  return _s;
}
inline const std::string& ExGmtMsg::pb_args(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:ExGmtMsg.pb_args)
  return _internal_pb_args().Get(index);
}
inline std::string* ExGmtMsg::mutable_pb_args(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:ExGmtMsg.pb_args)
  return _internal_mutable_pb_args()->Mutable(index);
}
inline void ExGmtMsg::set_pb_args(int index, const std::string& value) {
  _internal_mutable_pb_args()->Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set:ExGmtMsg.pb_args)
}
inline void ExGmtMsg::set_pb_args(int index, std::string&& value) {
  _internal_mutable_pb_args()->Mutable(index)->assign(std::move(value));
  // @@protoc_insertion_point(field_set:ExGmtMsg.pb_args)
}
inline void ExGmtMsg::set_pb_args(int index, const char* value) {
  ABSL_DCHECK(value != nullptr);
  _internal_mutable_pb_args()->Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:ExGmtMsg.pb_args)
}
inline void ExGmtMsg::set_pb_args(int index, const char* value,
                              std::size_t size) {
  _internal_mutable_pb_args()->Mutable(index)->assign(
      reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:ExGmtMsg.pb_args)
}
inline void ExGmtMsg::set_pb_args(int index, absl::string_view value) {
  _internal_mutable_pb_args()->Mutable(index)->assign(
      value.data(), value.size());
  // @@protoc_insertion_point(field_set_string_piece:ExGmtMsg.pb_args)
}
inline void ExGmtMsg::add_pb_args(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_pb_args()->Add()->assign(value);
  // @@protoc_insertion_point(field_add:ExGmtMsg.pb_args)
}
inline void ExGmtMsg::add_pb_args(std::string&& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_pb_args()->Add(std::move(value));
  // @@protoc_insertion_point(field_add:ExGmtMsg.pb_args)
}
inline void ExGmtMsg::add_pb_args(const char* value) {
  ABSL_DCHECK(value != nullptr);
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_pb_args()->Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:ExGmtMsg.pb_args)
}
inline void ExGmtMsg::add_pb_args(const char* value, std::size_t size) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_pb_args()->Add()->assign(
      reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:ExGmtMsg.pb_args)
}
inline void ExGmtMsg::add_pb_args(absl::string_view value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_pb_args()->Add()->assign(value.data(),
                                                     value.size());
  // @@protoc_insertion_point(field_add_string_piece:ExGmtMsg.pb_args)
}
inline const ::google::protobuf::RepeatedPtrField<std::string>&
ExGmtMsg::pb_args() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:ExGmtMsg.pb_args)
  return _internal_pb_args();
}
inline ::google::protobuf::RepeatedPtrField<std::string>*
ExGmtMsg::mutable_pb_args() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:ExGmtMsg.pb_args)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_pb_args();
}
inline const ::google::protobuf::RepeatedPtrField<std::string>&
ExGmtMsg::_internal_pb_args() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.pb_args_;
}
inline ::google::protobuf::RepeatedPtrField<std::string>*
ExGmtMsg::_internal_mutable_pb_args() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.pb_args_;
}

// optional string pb_sid = 5;
inline bool ExGmtMsg::has_pb_sid() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline void ExGmtMsg::clear_pb_sid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pb_sid_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const std::string& ExGmtMsg::pb_sid() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:ExGmtMsg.pb_sid)
  return _internal_pb_sid();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void ExGmtMsg::set_pb_sid(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.pb_sid_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:ExGmtMsg.pb_sid)
}
inline std::string* ExGmtMsg::mutable_pb_sid() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_pb_sid();
  // @@protoc_insertion_point(field_mutable:ExGmtMsg.pb_sid)
  return _s;
}
inline const std::string& ExGmtMsg::_internal_pb_sid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.pb_sid_.Get();
}
inline void ExGmtMsg::_internal_set_pb_sid(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.pb_sid_.Set(value, GetArena());
}
inline std::string* ExGmtMsg::_internal_mutable_pb_sid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  return _impl_.pb_sid_.Mutable( GetArena());
}
inline std::string* ExGmtMsg::release_pb_sid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:ExGmtMsg.pb_sid)
  if ((_impl_._has_bits_[0] & 0x00000002u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000002u;
  auto* released = _impl_.pb_sid_.Release();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.pb_sid_.Set("", GetArena());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return released;
}
inline void ExGmtMsg::set_allocated_pb_sid(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  _impl_.pb_sid_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.pb_sid_.IsDefault()) {
          _impl_.pb_sid_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ExGmtMsg.pb_sid)
}

// optional int64 pb_nid = 6;
inline bool ExGmtMsg::has_pb_nid() const {
  bool value = (_impl_._has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline void ExGmtMsg::clear_pb_nid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pb_nid_ = ::int64_t{0};
  _impl_._has_bits_[0] &= ~0x00000008u;
}
inline ::int64_t ExGmtMsg::pb_nid() const {
  // @@protoc_insertion_point(field_get:ExGmtMsg.pb_nid)
  return _internal_pb_nid();
}
inline void ExGmtMsg::set_pb_nid(::int64_t value) {
  _internal_set_pb_nid(value);
  _impl_._has_bits_[0] |= 0x00000008u;
  // @@protoc_insertion_point(field_set:ExGmtMsg.pb_nid)
}
inline ::int64_t ExGmtMsg::_internal_pb_nid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.pb_nid_;
}
inline void ExGmtMsg::_internal_set_pb_nid(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pb_nid_ = value;
}

// optional int32 pb_ret = 10;
inline bool ExGmtMsg::has_pb_ret() const {
  bool value = (_impl_._has_bits_[0] & 0x00000020u) != 0;
  return value;
}
inline void ExGmtMsg::clear_pb_ret() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pb_ret_ = 0;
  _impl_._has_bits_[0] &= ~0x00000020u;
}
inline ::int32_t ExGmtMsg::pb_ret() const {
  // @@protoc_insertion_point(field_get:ExGmtMsg.pb_ret)
  return _internal_pb_ret();
}
inline void ExGmtMsg::set_pb_ret(::int32_t value) {
  _internal_set_pb_ret(value);
  _impl_._has_bits_[0] |= 0x00000020u;
  // @@protoc_insertion_point(field_set:ExGmtMsg.pb_ret)
}
inline ::int32_t ExGmtMsg::_internal_pb_ret() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.pb_ret_;
}
inline void ExGmtMsg::_internal_set_pb_ret(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pb_ret_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_ExGmtMsg_2eproto_2epb_2eh
