// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ExGmtCmd.proto
// Protobuf C++ Version: 5.27.0

#include "ExGmtCmd.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_ExGmtCmd_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_ExGmtCmd_2eproto = nullptr;
const ::uint32_t TableStruct_ExGmtCmd_2eproto::offsets[1] = {};
static constexpr ::_pbi::MigrationSchema* schemas = nullptr;
static constexpr ::_pb::Message* const* file_default_instances = nullptr;
const char descriptor_table_protodef_ExGmtCmd_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\016ExGmtCmd.proto*$\n\014ENUM_GMT_CMD\022\024\n\017SRV_"
    "ExGmtCommon\020\315\010"
};
static ::absl::once_flag descriptor_table_ExGmtCmd_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_ExGmtCmd_2eproto = {
    false,
    false,
    54,
    descriptor_table_protodef_ExGmtCmd_2eproto,
    "ExGmtCmd.proto",
    &descriptor_table_ExGmtCmd_2eproto_once,
    nullptr,
    0,
    0,
    schemas,
    file_default_instances,
    TableStruct_ExGmtCmd_2eproto::offsets,
    file_level_enum_descriptors_ExGmtCmd_2eproto,
    file_level_service_descriptors_ExGmtCmd_2eproto,
};
const ::google::protobuf::EnumDescriptor* ENUM_GMT_CMD_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_ExGmtCmd_2eproto);
  return file_level_enum_descriptors_ExGmtCmd_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t ENUM_GMT_CMD_internal_data_[] = {
    66637u, 0u, };
bool ENUM_GMT_CMD_IsValid(int value) {
  return 1101 <= value && value <= 1101;
}
// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_ExGmtCmd_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
