// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ExItemCmd.proto
// Protobuf C++ Version: 5.27.0

#include "ExItemCmd.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_ExItemCmd_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_ExItemCmd_2eproto = nullptr;
const ::uint32_t TableStruct_ExItemCmd_2eproto::offsets[1] = {};
static constexpr ::_pbi::MigrationSchema* schemas = nullptr;
static constexpr ::_pb::Message* const* file_default_instances = nullptr;
const char descriptor_table_protodef_ExItemCmd_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\017ExItemCmd.proto*\327\022\n\rENUM_ITEM_CMD\022\026\n\021C"
    "2S_DceBagItemLst\020\221N\022\031\n\024C2S_DceStaticComp"
    "ose\020\223N\022\030\n\023C2S_DceExchangeCoin\020\225N\022\023\n\016C2S_"
    "DceOpenBox\020\227N\022\034\n\027C2S_DceMultiPlanCompose"
    "\020\231N\022!\n\034C2S_DceObjDiamondPlanCompose\020\233N\022\036"
    "\n\031C2S_DceGetMaterialBagList\020\247N\022\026\n\021C2S_Dc"
    "eQueryTimer\020\251N\022\032\n\025C2S_DceChangeRoleName\020"
    "\247Q\022\032\n\025C2S_DceMountHeadFrame\020\251Q\022\033\n\026C2S_Dc"
    "eSetInstanceAttr\020\253Q\022#\n\036C2S_DceSetObjDiam"
    "ondLockStatus\020\255Q\022\033\n\026C2S_DceSettleGameEve"
    "nt\020\207R\022\034\n\027C2S_DceUpdateTaskStatus\020\217R\022\031\n\024C"
    "2S_DceGetTaskReward\020\221R\022\032\n\025C2S_DceTreatGa"
    "meEvent\020\223R\022 \n\033C2S_DceUpdateTaskListStatu"
    "s\020\225R\022\035\n\030C2S_DceGetTaskListReward\020\227R\022\027\n\022C"
    "2S_DceGetTreasury\020\315S\022\033\n\026C2S_DceTakeOutTr"
    "easure\020\317S\022\034\n\027C2S_DceRegisterActivity\020\321S\022"
    "\032\n\025C2S_DceSettleActivity\020\323S\022\033\n\026C2S_DceGe"
    "tActivityList\020\325S\022 \n\033C2S_DceRegisterActiv"
    "ityList\020\327S\022\036\n\031C2S_DceSettleActivityList\020"
    "\331S\022\034\n\027C2S_DceGetMilestoneList\020\333S\022\034\n\027C2S_"
    "DceGetGameSetRemote\020\335S\022\032\n\025C2S_DceGetLobb"
    "yRandom\020\337S\022\027\n\022C2S_DceSetPassWord\020\341S\022\032\n\025C"
    "2S_DceVerifyPassWord\020\343S\022\031\n\024C2S_DceResetP"
    "assWord\020\347S\022\037\n\032C2S_DceChangeTreasuryLayer"
    "\020\351S\022\032\n\025C2S_DceGetActivityCfg\020\353S\022\023\n\016S2C_D"
    "seRewards\020\220N\022\026\n\021S2C_DseBagItemLst\020\222N\022\031\n\024"
    "S2C_DseStaticCompose\020\224N\022\030\n\023S2C_DseExchan"
    "geCoin\020\226N\022\023\n\016S2C_DseOpenBox\020\230N\022\034\n\027S2C_Ds"
    "eMultiPlanCompose\020\232N\022!\n\034S2C_DseObjDiamon"
    "dPlanCompose\020\234N\022\036\n\031S2C_DseGetMaterialBag"
    "List\020\250N\022\026\n\021S2C_DseQueryTimer\020\252N\022\027\n\022S2C_D"
    "seAddInstance\020\364N\022\024\n\017S2C_DseAddSkill\020\372N\022\033"
    "\n\026S2C_DseUpdateRoleState\020\374N\022\032\n\025S2C_DseDe"
    "leteInstance\020\330O\022\036\n\031S2C_DseUpdateInstance"
    "Attr\020\274P\022\033\n\026S2C_DseUpdateGroupItem\020\300P\022\034\n\027"
    "S2C_DseUpdatePlayerAttr\020\302P\022\033\n\026S2C_DseUpd"
    "ateDressItem\020\306P\022!\n\034S2C_DseUpdateTimeLimi"
    "tedItem\020\310P\022!\n\034S2C_DseNotifyMilestoneUpda"
    "te\020\312P\022\035\n\030S2C_DseNotifyMatchResult\020\314P\022 \n\033"
    "S2C_DseNotifyPlayerLvUpdate\020\316P\022\032\n\025S2C_Ds"
    "eChangeRoleName\020\250Q\022\032\n\025S2C_DseMountHeadFr"
    "ame\020\252Q\022\033\n\026S2C_DseSetInstanceAttr\020\254Q\022#\n\036S"
    "2C_DseSetObjDiamondLockStatus\020\256Q\022\033\n\026S2C_"
    "DseSettleGameEvent\020\210R\022\030\n\023S2C_DseAddGameE"
    "vent\020\212R\022\033\n\026S2C_DseRemoveGameEvent\020\214R\022\033\n\026"
    "S2C_DseUpdateGameEvent\020\216R\022\034\n\027S2C_DseUpda"
    "teTaskStatus\020\220R\022\031\n\024S2C_DseGetTaskReward\020"
    "\222R\022\032\n\025S2C_DseTreatGameEvent\020\224R\022 \n\033S2C_Ds"
    "eUpdateTaskListStatus\020\226R\022\035\n\030S2C_DseGetTa"
    "skListReward\020\230R\022\027\n\022S2C_DseGetTreasury\020\316S"
    "\022\033\n\026S2C_DseTakeOutTreasure\020\320S\022\034\n\027S2C_Dse"
    "RegisterActivity\020\322S\022\032\n\025S2C_DseSettleActi"
    "vity\020\324S\022\033\n\026S2C_DseGetActivityList\020\326S\022 \n\033"
    "S2C_DseRegisterActivityList\020\330S\022\036\n\031S2C_Ds"
    "eSettleActivityList\020\332S\022\034\n\027S2C_DseGetMile"
    "stoneList\020\334S\022\034\n\027S2C_DseGetGameSetRemote\020"
    "\336S\022\032\n\025S2C_DseGetLobbyRandom\020\340S\022\027\n\022S2C_Ds"
    "eSetPassWord\020\342S\022\032\n\025S2C_DseVerifyPassWord"
    "\020\344S\022\031\n\024S2C_DseResetPassWord\020\350S\022\037\n\032S2C_Ds"
    "eChangeTreasuryLayer\020\352S\022\032\n\025S2C_DseGetAct"
    "ivityCfg\020\354S"
};
static ::absl::once_flag descriptor_table_ExItemCmd_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_ExItemCmd_2eproto = {
    false,
    false,
    2411,
    descriptor_table_protodef_ExItemCmd_2eproto,
    "ExItemCmd.proto",
    &descriptor_table_ExItemCmd_2eproto_once,
    nullptr,
    0,
    0,
    schemas,
    file_default_instances,
    TableStruct_ExItemCmd_2eproto::offsets,
    file_level_enum_descriptors_ExItemCmd_2eproto,
    file_level_service_descriptors_ExItemCmd_2eproto,
};
const ::google::protobuf::EnumDescriptor* ENUM_ITEM_CMD_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_ExItemCmd_2eproto);
  return file_level_enum_descriptors_ExItemCmd_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t ENUM_ITEM_CMD_internal_data_[] = {
    861968u, 736u, 15360u, 0u, 2692743168u, 0u, 0u, 134217728u, 0u, 0u, 2147483648u, 174632u, 0u, 0u, 261120u, 0u, 0u, 268348416u, 0u, 0u, 0u, 0u, 0u, 4294901760u, 64767u, };
bool ENUM_ITEM_CMD_IsValid(int value) {
  return ::_pbi::ValidateEnum(value, ENUM_ITEM_CMD_internal_data_);
}
// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_ExItemCmd_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
