// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ExItemCmd.proto
// Protobuf C++ Version: 5.27.0

#ifndef GOOGLE_PROTOBUF_INCLUDED_ExItemCmd_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_ExItemCmd_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5027000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_ExItemCmd_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_ExItemCmd_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_ExItemCmd_2eproto;
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

enum ENUM_ITEM_CMD : int {
  C2S_DceBagItemLst = 10001,
  C2S_DceStaticCompose = 10003,
  C2S_DceExchangeCoin = 10005,
  C2S_DceOpenBox = 10007,
  C2S_DceMultiPlanCompose = 10009,
  C2S_DceObjDiamondPlanCompose = 10011,
  C2S_DceGetMaterialBagList = 10023,
  C2S_DceQueryTimer = 10025,
  C2S_DceChangeRoleName = 10407,
  C2S_DceMountHeadFrame = 10409,
  C2S_DceSetInstanceAttr = 10411,
  C2S_DceSetObjDiamondLockStatus = 10413,
  C2S_DceSettleGameEvent = 10503,
  C2S_DceUpdateTaskStatus = 10511,
  C2S_DceGetTaskReward = 10513,
  C2S_DceTreatGameEvent = 10515,
  C2S_DceUpdateTaskListStatus = 10517,
  C2S_DceGetTaskListReward = 10519,
  C2S_DceGetTreasury = 10701,
  C2S_DceTakeOutTreasure = 10703,
  C2S_DceRegisterActivity = 10705,
  C2S_DceSettleActivity = 10707,
  C2S_DceGetActivityList = 10709,
  C2S_DceRegisterActivityList = 10711,
  C2S_DceSettleActivityList = 10713,
  C2S_DceGetMilestoneList = 10715,
  C2S_DceGetGameSetRemote = 10717,
  C2S_DceGetLobbyRandom = 10719,
  C2S_DceSetPassWord = 10721,
  C2S_DceVerifyPassWord = 10723,
  C2S_DceResetPassWord = 10727,
  C2S_DceChangeTreasuryLayer = 10729,
  C2S_DceGetActivityCfg = 10731,
  S2C_DseRewards = 10000,
  S2C_DseBagItemLst = 10002,
  S2C_DseStaticCompose = 10004,
  S2C_DseExchangeCoin = 10006,
  S2C_DseOpenBox = 10008,
  S2C_DseMultiPlanCompose = 10010,
  S2C_DseObjDiamondPlanCompose = 10012,
  S2C_DseGetMaterialBagList = 10024,
  S2C_DseQueryTimer = 10026,
  S2C_DseAddInstance = 10100,
  S2C_DseAddSkill = 10106,
  S2C_DseUpdateRoleState = 10108,
  S2C_DseDeleteInstance = 10200,
  S2C_DseUpdateInstanceAttr = 10300,
  S2C_DseUpdateGroupItem = 10304,
  S2C_DseUpdatePlayerAttr = 10306,
  S2C_DseUpdateDressItem = 10310,
  S2C_DseUpdateTimeLimitedItem = 10312,
  S2C_DseNotifyMilestoneUpdate = 10314,
  S2C_DseNotifyMatchResult = 10316,
  S2C_DseNotifyPlayerLvUpdate = 10318,
  S2C_DseChangeRoleName = 10408,
  S2C_DseMountHeadFrame = 10410,
  S2C_DseSetInstanceAttr = 10412,
  S2C_DseSetObjDiamondLockStatus = 10414,
  S2C_DseSettleGameEvent = 10504,
  S2C_DseAddGameEvent = 10506,
  S2C_DseRemoveGameEvent = 10508,
  S2C_DseUpdateGameEvent = 10510,
  S2C_DseUpdateTaskStatus = 10512,
  S2C_DseGetTaskReward = 10514,
  S2C_DseTreatGameEvent = 10516,
  S2C_DseUpdateTaskListStatus = 10518,
  S2C_DseGetTaskListReward = 10520,
  S2C_DseGetTreasury = 10702,
  S2C_DseTakeOutTreasure = 10704,
  S2C_DseRegisterActivity = 10706,
  S2C_DseSettleActivity = 10708,
  S2C_DseGetActivityList = 10710,
  S2C_DseRegisterActivityList = 10712,
  S2C_DseSettleActivityList = 10714,
  S2C_DseGetMilestoneList = 10716,
  S2C_DseGetGameSetRemote = 10718,
  S2C_DseGetLobbyRandom = 10720,
  S2C_DseSetPassWord = 10722,
  S2C_DseVerifyPassWord = 10724,
  S2C_DseResetPassWord = 10728,
  S2C_DseChangeTreasuryLayer = 10730,
  S2C_DseGetActivityCfg = 10732,
};

bool ENUM_ITEM_CMD_IsValid(int value);
extern const uint32_t ENUM_ITEM_CMD_internal_data_[];
constexpr ENUM_ITEM_CMD ENUM_ITEM_CMD_MIN = static_cast<ENUM_ITEM_CMD>(10000);
constexpr ENUM_ITEM_CMD ENUM_ITEM_CMD_MAX = static_cast<ENUM_ITEM_CMD>(10732);
constexpr int ENUM_ITEM_CMD_ARRAYSIZE = 10732 + 1;
const ::google::protobuf::EnumDescriptor*
ENUM_ITEM_CMD_descriptor();
template <typename T>
const std::string& ENUM_ITEM_CMD_Name(T value) {
  static_assert(std::is_same<T, ENUM_ITEM_CMD>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to ENUM_ITEM_CMD_Name().");
  return ::google::protobuf::internal::NameOfEnum(ENUM_ITEM_CMD_descriptor(), value);
}
inline bool ENUM_ITEM_CMD_Parse(absl::string_view name, ENUM_ITEM_CMD* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ENUM_ITEM_CMD>(
      ENUM_ITEM_CMD_descriptor(), name, value);
}

// ===================================================================



// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::ENUM_ITEM_CMD> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::ENUM_ITEM_CMD>() {
  return ::ENUM_ITEM_CMD_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_ExItemCmd_2eproto_2epb_2eh
