// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ExLoginCmd.proto
// Protobuf C++ Version: 5.27.0

#include "ExLoginCmd.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_ExLoginCmd_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_ExLoginCmd_2eproto = nullptr;
const ::uint32_t TableStruct_ExLoginCmd_2eproto::offsets[1] = {};
static constexpr ::_pbi::MigrationSchema* schemas = nullptr;
static constexpr ::_pb::Message* const* file_default_instances = nullptr;
const char descriptor_table_protodef_ExLoginCmd_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\020ExLoginCmd.proto*\264\004\n\016ENUM_LOGIN_CMD\022\026\n"
    "\022C2S_DceEnterServer\020i\022\025\n\021C2S_DceQuitServ"
    "er\020k\022\021\n\rC2S_DceLogout\020m\022\017\n\013C2S_DceAuth\020o"
    "\022\030\n\024C2S_DceActiveAccount\020q\022\032\n\026C2S_DceGet"
    "ServerNotice\020s\022\030\n\024C2S_DceGetServerList\020u"
    "\022\025\n\021C2S_DceCreateRole\020w\022\024\n\020C2S_DceGetRan"
    "dom\020y\022\024\n\020C2S_DceReconnect\020{\022\023\n\017C2S_DceAu"
    "thGate\020}\022\025\n\020C2S_DceHeartBeat\020\307\001\022\026\n\022S2C_D"
    "seEnterServer\020j\022\025\n\021S2C_DseQuitServer\020l\022\021"
    "\n\rS2C_DseLogout\020n\022\017\n\013S2C_DseAuth\020p\022\030\n\024S2"
    "C_DseActiveAccount\020r\022\032\n\026S2C_DseGetServer"
    "Notice\020t\022\030\n\024S2C_DseGetServerList\020v\022\025\n\021S2"
    "C_DseCreateRole\020x\022\024\n\020S2C_DseGetRandom\020z\022"
    "\024\n\020S2C_DseReconnect\020|\022\023\n\017S2C_DseAuthGate"
    "\020~\022\025\n\020S2C_DseHeartBeat\020\310\001"
};
static ::absl::once_flag descriptor_table_ExLoginCmd_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_ExLoginCmd_2eproto = {
    false,
    false,
    585,
    descriptor_table_protodef_ExLoginCmd_2eproto,
    "ExLoginCmd.proto",
    &descriptor_table_ExLoginCmd_2eproto_once,
    nullptr,
    0,
    0,
    schemas,
    file_default_instances,
    TableStruct_ExLoginCmd_2eproto::offsets,
    file_level_enum_descriptors_ExLoginCmd_2eproto,
    file_level_service_descriptors_ExLoginCmd_2eproto,
};
const ::google::protobuf::EnumDescriptor* ENUM_LOGIN_CMD_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_ExLoginCmd_2eproto);
  return file_level_enum_descriptors_ExLoginCmd_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t ENUM_LOGIN_CMD_internal_data_[] = {
    1441897u, 131072u, 200u, 199u, };
bool ENUM_LOGIN_CMD_IsValid(int value) {
  return ::_pbi::ValidateEnum(value, ENUM_LOGIN_CMD_internal_data_);
}
// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_ExLoginCmd_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
