// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ExLoginCmd.proto
// Protobuf C++ Version: 5.27.0

#ifndef GOOGLE_PROTOBUF_INCLUDED_ExLoginCmd_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_ExLoginCmd_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5027000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_ExLoginCmd_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_ExLoginCmd_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_ExLoginCmd_2eproto;
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

enum ENUM_LOGIN_CMD : int {
  C2S_DceEnterServer = 105,
  C2S_DceQuitServer = 107,
  C2S_DceLogout = 109,
  C2S_DceAuth = 111,
  C2S_DceActiveAccount = 113,
  C2S_DceGetServerNotice = 115,
  C2S_DceGetServerList = 117,
  C2S_DceCreateRole = 119,
  C2S_DceGetRandom = 121,
  C2S_DceReconnect = 123,
  C2S_DceAuthGate = 125,
  C2S_DceHeartBeat = 199,
  S2C_DseEnterServer = 106,
  S2C_DseQuitServer = 108,
  S2C_DseLogout = 110,
  S2C_DseAuth = 112,
  S2C_DseActiveAccount = 114,
  S2C_DseGetServerNotice = 116,
  S2C_DseGetServerList = 118,
  S2C_DseCreateRole = 120,
  S2C_DseGetRandom = 122,
  S2C_DseReconnect = 124,
  S2C_DseAuthGate = 126,
  S2C_DseHeartBeat = 200,
};

bool ENUM_LOGIN_CMD_IsValid(int value);
extern const uint32_t ENUM_LOGIN_CMD_internal_data_[];
constexpr ENUM_LOGIN_CMD ENUM_LOGIN_CMD_MIN = static_cast<ENUM_LOGIN_CMD>(105);
constexpr ENUM_LOGIN_CMD ENUM_LOGIN_CMD_MAX = static_cast<ENUM_LOGIN_CMD>(200);
constexpr int ENUM_LOGIN_CMD_ARRAYSIZE = 200 + 1;
const ::google::protobuf::EnumDescriptor*
ENUM_LOGIN_CMD_descriptor();
template <typename T>
const std::string& ENUM_LOGIN_CMD_Name(T value) {
  static_assert(std::is_same<T, ENUM_LOGIN_CMD>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to ENUM_LOGIN_CMD_Name().");
  return ::google::protobuf::internal::NameOfEnum(ENUM_LOGIN_CMD_descriptor(), value);
}
inline bool ENUM_LOGIN_CMD_Parse(absl::string_view name, ENUM_LOGIN_CMD* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ENUM_LOGIN_CMD>(
      ENUM_LOGIN_CMD_descriptor(), name, value);
}

// ===================================================================



// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::ENUM_LOGIN_CMD> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::ENUM_LOGIN_CMD>() {
  return ::ENUM_LOGIN_CMD_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_ExLoginCmd_2eproto_2epb_2eh
