// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ExMailCmd.proto
// Protobuf C++ Version: 5.27.0

#ifndef GOOGLE_PROTOBUF_INCLUDED_ExMailCmd_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_ExMailCmd_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5027000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_ExMailCmd_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_ExMailCmd_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_ExMailCmd_2eproto;
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

enum ENUM_MAIL_CMD : int {
  C2S_DceNewReadMail = 27001,
  C2S_DceNewDeleteMail = 27003,
  C2S_DceNewDeleteClaimedMail = 27005,
  C2S_DceNewGetAllMailAttach = 27007,
  C2S_DceNewGetMailList = 27009,
  C2S_DceNewClaimAttachment = 27011,
  C2S_DceNewUpdateMailSendTime = 27013,
  C2S_DceNewDeleteExpiredMails = 27015,
  S2C_DseNewReadMail = 27002,
  S2C_DseNewDeleteMail = 27004,
  S2C_DseNewDeleteClaimedMail = 27006,
  S2C_DseNewGetAllMailAttach = 27008,
  S2C_DseNewGetMailList = 27010,
  S2C_DseNewClaimAttachment = 27012,
  S2C_DseNewUpdateMailSendTime = 27014,
  S2C_DseNewDeleteExpiredMails = 27016,
  S2C_DseNewNotifyAddMail = 27100,
  S2C_DseNewNotifyDelMail = 27102,
};

bool ENUM_MAIL_CMD_IsValid(int value);
extern const uint32_t ENUM_MAIL_CMD_internal_data_[];
constexpr ENUM_MAIL_CMD ENUM_MAIL_CMD_MIN = static_cast<ENUM_MAIL_CMD>(27001);
constexpr ENUM_MAIL_CMD ENUM_MAIL_CMD_MAX = static_cast<ENUM_MAIL_CMD>(27102);
constexpr int ENUM_MAIL_CMD_ARRAYSIZE = 27102 + 1;
const ::google::protobuf::EnumDescriptor*
ENUM_MAIL_CMD_descriptor();
template <typename T>
const std::string& ENUM_MAIL_CMD_Name(T value) {
  static_assert(std::is_same<T, ENUM_MAIL_CMD>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to ENUM_MAIL_CMD_Name().");
  return ::google::protobuf::internal::NameOfEnum(ENUM_MAIL_CMD_descriptor(), value);
}
inline bool ENUM_MAIL_CMD_Parse(absl::string_view name, ENUM_MAIL_CMD* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ENUM_MAIL_CMD>(
      ENUM_MAIL_CMD_descriptor(), name, value);
}

// ===================================================================



// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::ENUM_MAIL_CMD> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::ENUM_MAIL_CMD>() {
  return ::ENUM_MAIL_CMD_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_ExMailCmd_2eproto_2epb_2eh
