// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ExMailCmd.proto
// Protobuf C++ Version: 5.27.0

#include "ExMailCmd.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_ExMailCmd_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_ExMailCmd_2eproto = nullptr;
const ::uint32_t TableStruct_ExMailCmd_2eproto::offsets[1] = {};
static constexpr ::_pbi::MigrationSchema* schemas = nullptr;
static constexpr ::_pb::Message* const* file_default_instances = nullptr;
const char descriptor_table_protodef_ExMailCmd_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\017ExMailCmd.proto*\317\004\n\rENUM_MAIL_CMD\022\030\n\022C"
    "2S_DceNewReadMail\020\371\322\001\022\032\n\024C2S_DceNewDelet"
    "eMail\020\373\322\001\022!\n\033C2S_DceNewDeleteClaimedMail"
    "\020\375\322\001\022 \n\032C2S_DceNewGetAllMailAttach\020\377\322\001\022\033"
    "\n\025C2S_DceNewGetMailList\020\201\323\001\022\037\n\031C2S_DceNe"
    "wClaimAttachment\020\203\323\001\022\"\n\034C2S_DceNewUpdate"
    "MailSendTime\020\205\323\001\022\"\n\034C2S_DceNewDeleteExpi"
    "redMails\020\207\323\001\022\030\n\022S2C_DseNewReadMail\020\372\322\001\022\032"
    "\n\024S2C_DseNewDeleteMail\020\374\322\001\022!\n\033S2C_DseNew"
    "DeleteClaimedMail\020\376\322\001\022 \n\032S2C_DseNewGetAl"
    "lMailAttach\020\200\323\001\022\033\n\025S2C_DseNewGetMailList"
    "\020\202\323\001\022\037\n\031S2C_DseNewClaimAttachment\020\204\323\001\022\"\n"
    "\034S2C_DseNewUpdateMailSendTime\020\206\323\001\022\"\n\034S2C"
    "_DseNewDeleteExpiredMails\020\210\323\001\022\035\n\027S2C_Dse"
    "NewNotifyAddMail\020\334\323\001\022\035\n\027S2C_DseNewNotify"
    "DelMail\020\336\323\001"
};
static ::absl::once_flag descriptor_table_ExMailCmd_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_ExMailCmd_2eproto = {
    false,
    false,
    611,
    descriptor_table_protodef_ExMailCmd_2eproto,
    "ExMailCmd.proto",
    &descriptor_table_ExMailCmd_2eproto_once,
    nullptr,
    0,
    0,
    schemas,
    file_default_instances,
    TableStruct_ExMailCmd_2eproto::offsets,
    file_level_enum_descriptors_ExMailCmd_2eproto,
    file_level_service_descriptors_ExMailCmd_2eproto,
};
const ::google::protobuf::EnumDescriptor* ENUM_MAIL_CMD_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_ExMailCmd_2eproto);
  return file_level_enum_descriptors_ExMailCmd_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t ENUM_MAIL_CMD_internal_data_[] = {
    1075577u, 131072u, 27102u, 27100u, };
bool ENUM_MAIL_CMD_IsValid(int value) {
  return ::_pbi::ValidateEnum(value, ENUM_MAIL_CMD_internal_data_);
}
// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_ExMailCmd_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
