// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ExMessageCmd.proto
// Protobuf C++ Version: 5.27.0

#include "ExMessageCmd.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_ExMessageCmd_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_ExMessageCmd_2eproto = nullptr;
const ::uint32_t TableStruct_ExMessageCmd_2eproto::offsets[1] = {};
static constexpr ::_pbi::MigrationSchema* schemas = nullptr;
static constexpr ::_pb::Message* const* file_default_instances = nullptr;
const char descriptor_table_protodef_ExMessageCmd_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\022ExMessageCmd.proto*\262\010\n\021ENUM_MSG_MSGD_C"
    "MD\022\021\n\013C2S_DceChat\020\327\206\003\022\025\n\017C2S_DceReadMail"
    "\020\331\206\003\022\027\n\021C2S_DceDeleteMail\020\333\206\003\022\035\n\027C2S_Dce"
    "DeleteReadedMail\020\335\206\003\022\035\n\027C2S_DceGetAllMai"
    "lAttach\020\337\206\003\022\030\n\022C2S_DceGetMailList\020\341\206\003\022\034\n"
    "\026C2S_DceGetMailsContent\020\343\206\003\022\033\n\025C2S_DceGe"
    "tPublishList\020\345\206\003\022\030\n\022C2S_DceJoinChannel\020\347"
    "\206\003\022\037\n\031C2S_DceGetRoleCommentInfo\020\351\206\003\022\030\n\022C"
    "2S_DceCommentRole\020\353\206\003\022\032\n\024C2S_DcePraiseCo"
    "mment\020\355\206\003\022\025\n\017C2S_DceLikeRole\020\357\206\003\022\033\n\025C2S_"
    "DceGetRoleLikeCnt\020\361\206\003\022\031\n\023C2S_DceLeaveCha"
    "nnel\020\363\206\003\022\021\n\013S2C_DseChat\020\330\206\003\022\025\n\017S2C_DseRe"
    "adMail\020\332\206\003\022\027\n\021S2C_DseDeleteMail\020\334\206\003\022\035\n\027S"
    "2C_DseDeleteReadedMail\020\336\206\003\022\035\n\027S2C_DseGet"
    "AllMailAttach\020\340\206\003\022\030\n\022S2C_DseGetMailList\020"
    "\342\206\003\022\034\n\026S2C_DseGetMailsContent\020\344\206\003\022\033\n\025S2C"
    "_DseGetPublishList\020\346\206\003\022\030\n\022S2C_DseJoinCha"
    "nnel\020\350\206\003\022\037\n\031S2C_DseGetRoleCommentInfo\020\352\206"
    "\003\022\030\n\022S2C_DseCommentRole\020\354\206\003\022\032\n\024S2C_DsePr"
    "aiseComment\020\356\206\003\022\025\n\017S2C_DseLikeRole\020\360\206\003\022\033"
    "\n\025S2C_DseGetRoleLikeCnt\020\362\206\003\022\031\n\023S2C_DseLe"
    "aveChannel\020\364\206\003\022\032\n\024S2C_DseNotifyAddMail\020\264"
    "\207\003\022\032\n\024S2C_DseNotifyDelMail\020\230\210\003\022\035\n\027S2C_Ds"
    "eNotifyAddPublish\020\232\210\003\022\035\n\027S2C_DseNotifyDe"
    "lPublish\020\234\210\003\022 \n\032S2C_DseNotifyUpdatePubli"
    "sh\020\236\210\003\022\027\n\021S2C_DseNotifyChat\020\240\210\003\022\037\n\031S2C_D"
    "seNotifyCurCHUserCnt\020\242\210\003\022\037\n\031S2C_DseNotif"
    "yLeaveChannel\020\244\210\003"
};
static ::absl::once_flag descriptor_table_ExMessageCmd_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_ExMessageCmd_2eproto = {
    false,
    false,
    1097,
    descriptor_table_protodef_ExMessageCmd_2eproto,
    "ExMessageCmd.proto",
    &descriptor_table_ExMessageCmd_2eproto_once,
    nullptr,
    0,
    0,
    schemas,
    file_default_instances,
    TableStruct_ExMessageCmd_2eproto::offsets,
    file_level_enum_descriptors_ExMessageCmd_2eproto,
    file_level_service_descriptors_ExMessageCmd_2eproto,
};
const ::google::protobuf::EnumDescriptor* ENUM_MSG_MSGD_CMD_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_ExMessageCmd_2eproto);
  return file_level_enum_descriptors_ExMessageCmd_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t ENUM_MSG_MSGD_CMD_internal_data_[] = {
    0u, 2490368u, 50029u, 50021u, 50100u, 50014u, 50025u, 50033u, 50206u, 50010u, 50018u, 50023u, 50027u, 50031u, 50035u, 50202u, 50210u, 50008u, 50012u, 50016u, 50020u, 50022u, 50024u, 50026u, 50028u, 50030u, 50032u, 50034u, 50036u, 50200u, 50204u, 50208u, 50212u, 50007u, 50009u, 50011u, 50013u, 50015u, 50017u, 50019u, };
bool ENUM_MSG_MSGD_CMD_IsValid(int value) {
  return ::_pbi::ValidateEnum(value, ENUM_MSG_MSGD_CMD_internal_data_);
}
// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_ExMessageCmd_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
