// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ExMessageCmd.proto
// Protobuf C++ Version: 5.27.0

#ifndef GOOGLE_PROTOBUF_INCLUDED_ExMessageCmd_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_ExMessageCmd_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5027000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_ExMessageCmd_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_ExMessageCmd_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_ExMessageCmd_2eproto;
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

enum ENUM_MSG_MSGD_CMD : int {
  C2S_DceChat = 50007,
  C2S_DceReadMail = 50009,
  C2S_DceDeleteMail = 50011,
  C2S_DceDeleteReadedMail = 50013,
  C2S_DceGetAllMailAttach = 50015,
  C2S_DceGetMailList = 50017,
  C2S_DceGetMailsContent = 50019,
  C2S_DceGetPublishList = 50021,
  C2S_DceJoinChannel = 50023,
  C2S_DceGetRoleCommentInfo = 50025,
  C2S_DceCommentRole = 50027,
  C2S_DcePraiseComment = 50029,
  C2S_DceLikeRole = 50031,
  C2S_DceGetRoleLikeCnt = 50033,
  C2S_DceLeaveChannel = 50035,
  S2C_DseChat = 50008,
  S2C_DseReadMail = 50010,
  S2C_DseDeleteMail = 50012,
  S2C_DseDeleteReadedMail = 50014,
  S2C_DseGetAllMailAttach = 50016,
  S2C_DseGetMailList = 50018,
  S2C_DseGetMailsContent = 50020,
  S2C_DseGetPublishList = 50022,
  S2C_DseJoinChannel = 50024,
  S2C_DseGetRoleCommentInfo = 50026,
  S2C_DseCommentRole = 50028,
  S2C_DsePraiseComment = 50030,
  S2C_DseLikeRole = 50032,
  S2C_DseGetRoleLikeCnt = 50034,
  S2C_DseLeaveChannel = 50036,
  S2C_DseNotifyAddMail = 50100,
  S2C_DseNotifyDelMail = 50200,
  S2C_DseNotifyAddPublish = 50202,
  S2C_DseNotifyDelPublish = 50204,
  S2C_DseNotifyUpdatePublish = 50206,
  S2C_DseNotifyChat = 50208,
  S2C_DseNotifyCurCHUserCnt = 50210,
  S2C_DseNotifyLeaveChannel = 50212,
};

bool ENUM_MSG_MSGD_CMD_IsValid(int value);
extern const uint32_t ENUM_MSG_MSGD_CMD_internal_data_[];
constexpr ENUM_MSG_MSGD_CMD ENUM_MSG_MSGD_CMD_MIN = static_cast<ENUM_MSG_MSGD_CMD>(50007);
constexpr ENUM_MSG_MSGD_CMD ENUM_MSG_MSGD_CMD_MAX = static_cast<ENUM_MSG_MSGD_CMD>(50212);
constexpr int ENUM_MSG_MSGD_CMD_ARRAYSIZE = 50212 + 1;
const ::google::protobuf::EnumDescriptor*
ENUM_MSG_MSGD_CMD_descriptor();
template <typename T>
const std::string& ENUM_MSG_MSGD_CMD_Name(T value) {
  static_assert(std::is_same<T, ENUM_MSG_MSGD_CMD>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to ENUM_MSG_MSGD_CMD_Name().");
  return ::google::protobuf::internal::NameOfEnum(ENUM_MSG_MSGD_CMD_descriptor(), value);
}
inline bool ENUM_MSG_MSGD_CMD_Parse(absl::string_view name, ENUM_MSG_MSGD_CMD* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ENUM_MSG_MSGD_CMD>(
      ENUM_MSG_MSGD_CMD_descriptor(), name, value);
}

// ===================================================================



// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::ENUM_MSG_MSGD_CMD> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::ENUM_MSG_MSGD_CMD>() {
  return ::ENUM_MSG_MSGD_CMD_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_ExMessageCmd_2eproto_2epb_2eh
