// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ExNewRankData.proto
// Protobuf C++ Version: 5.27.0

#ifndef GOOGLE_PROTOBUF_INCLUDED_ExNewRankData_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_ExNewRankData_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5027000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_ExNewRankData_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_ExNewRankData_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_ExNewRankData_2eproto;
class ExRankEntry;
struct ExRankEntryDefaultTypeInternal;
extern ExRankEntryDefaultTypeInternal _ExRankEntry_default_instance_;
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google


// ===================================================================


// -------------------------------------------------------------------

class ExRankEntry final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:ExRankEntry) */ {
 public:
  inline ExRankEntry() : ExRankEntry(nullptr) {}
  ~ExRankEntry() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ExRankEntry(
      ::google::protobuf::internal::ConstantInitialized);

  inline ExRankEntry(const ExRankEntry& from) : ExRankEntry(nullptr, from) {}
  inline ExRankEntry(ExRankEntry&& from) noexcept
      : ExRankEntry(nullptr, std::move(from)) {}
  inline ExRankEntry& operator=(const ExRankEntry& from) {
    CopyFrom(from);
    return *this;
  }
  inline ExRankEntry& operator=(ExRankEntry&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ExRankEntry& default_instance() {
    return *internal_default_instance();
  }
  static inline const ExRankEntry* internal_default_instance() {
    return reinterpret_cast<const ExRankEntry*>(
        &_ExRankEntry_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(ExRankEntry& a, ExRankEntry& b) { a.Swap(&b); }
  inline void Swap(ExRankEntry* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ExRankEntry* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ExRankEntry* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::Message::DefaultConstruct<ExRankEntry>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ExRankEntry& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const ExRankEntry& from) { ExRankEntry::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return IsInitializedImpl(*this);
  }

  private:
  static bool IsInitializedImpl(const MessageLite& msg);

  public:
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(ExRankEntry* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "ExRankEntry"; }

 protected:
  explicit ExRankEntry(::google::protobuf::Arena* arena);
  ExRankEntry(::google::protobuf::Arena* arena, const ExRankEntry& from);
  ExRankEntry(::google::protobuf::Arena* arena, ExRankEntry&& from) noexcept
      : ExRankEntry(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const final;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kPbNicknameFieldNumber = 5,
    kPbParam1FieldNumber = 7,
    kPbUidFieldNumber = 1,
    kPbRankTimeFieldNumber = 3,
    kPbRankValueFieldNumber = 2,
    kPbIconIdFieldNumber = 4,
    kPbTitleIdFieldNumber = 6,
    kPbLvFieldNumber = 8,
  };
  // required string pb_nickname = 5;
  bool has_pb_nickname() const;
  void clear_pb_nickname() ;
  const std::string& pb_nickname() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_pb_nickname(Arg_&& arg, Args_... args);
  std::string* mutable_pb_nickname();
  PROTOBUF_NODISCARD std::string* release_pb_nickname();
  void set_allocated_pb_nickname(std::string* value);

  private:
  const std::string& _internal_pb_nickname() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_pb_nickname(
      const std::string& value);
  std::string* _internal_mutable_pb_nickname();

  public:
  // optional string pb_param_1 = 7;
  bool has_pb_param_1() const;
  void clear_pb_param_1() ;
  const std::string& pb_param_1() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_pb_param_1(Arg_&& arg, Args_... args);
  std::string* mutable_pb_param_1();
  PROTOBUF_NODISCARD std::string* release_pb_param_1();
  void set_allocated_pb_param_1(std::string* value);

  private:
  const std::string& _internal_pb_param_1() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_pb_param_1(
      const std::string& value);
  std::string* _internal_mutable_pb_param_1();

  public:
  // required int64 pb_uid = 1;
  bool has_pb_uid() const;
  void clear_pb_uid() ;
  ::int64_t pb_uid() const;
  void set_pb_uid(::int64_t value);

  private:
  ::int64_t _internal_pb_uid() const;
  void _internal_set_pb_uid(::int64_t value);

  public:
  // required int64 pb_rank_time = 3;
  bool has_pb_rank_time() const;
  void clear_pb_rank_time() ;
  ::int64_t pb_rank_time() const;
  void set_pb_rank_time(::int64_t value);

  private:
  ::int64_t _internal_pb_rank_time() const;
  void _internal_set_pb_rank_time(::int64_t value);

  public:
  // required int32 pb_rank_value = 2;
  bool has_pb_rank_value() const;
  void clear_pb_rank_value() ;
  ::int32_t pb_rank_value() const;
  void set_pb_rank_value(::int32_t value);

  private:
  ::int32_t _internal_pb_rank_value() const;
  void _internal_set_pb_rank_value(::int32_t value);

  public:
  // required int32 pb_icon_id = 4;
  bool has_pb_icon_id() const;
  void clear_pb_icon_id() ;
  ::int32_t pb_icon_id() const;
  void set_pb_icon_id(::int32_t value);

  private:
  ::int32_t _internal_pb_icon_id() const;
  void _internal_set_pb_icon_id(::int32_t value);

  public:
  // optional int32 pb_title_id = 6;
  bool has_pb_title_id() const;
  void clear_pb_title_id() ;
  ::int32_t pb_title_id() const;
  void set_pb_title_id(::int32_t value);

  private:
  ::int32_t _internal_pb_title_id() const;
  void _internal_set_pb_title_id(::int32_t value);

  public:
  // optional int32 pb_lv = 8;
  bool has_pb_lv() const;
  void clear_pb_lv() ;
  ::int32_t pb_lv() const;
  void set_pb_lv(::int32_t value);

  private:
  ::int32_t _internal_pb_lv() const;
  void _internal_set_pb_lv(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:ExRankEntry)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      3, 8, 0,
      49, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_ExRankEntry_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const ExRankEntry& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr pb_nickname_;
    ::google::protobuf::internal::ArenaStringPtr pb_param_1_;
    ::int64_t pb_uid_;
    ::int64_t pb_rank_time_;
    ::int32_t pb_rank_value_;
    ::int32_t pb_icon_id_;
    ::int32_t pb_title_id_;
    ::int32_t pb_lv_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ExNewRankData_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// ExRankEntry

// required int64 pb_uid = 1;
inline bool ExRankEntry::has_pb_uid() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline void ExRankEntry::clear_pb_uid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pb_uid_ = ::int64_t{0};
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline ::int64_t ExRankEntry::pb_uid() const {
  // @@protoc_insertion_point(field_get:ExRankEntry.pb_uid)
  return _internal_pb_uid();
}
inline void ExRankEntry::set_pb_uid(::int64_t value) {
  _internal_set_pb_uid(value);
  _impl_._has_bits_[0] |= 0x00000004u;
  // @@protoc_insertion_point(field_set:ExRankEntry.pb_uid)
}
inline ::int64_t ExRankEntry::_internal_pb_uid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.pb_uid_;
}
inline void ExRankEntry::_internal_set_pb_uid(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pb_uid_ = value;
}

// required int32 pb_rank_value = 2;
inline bool ExRankEntry::has_pb_rank_value() const {
  bool value = (_impl_._has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline void ExRankEntry::clear_pb_rank_value() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pb_rank_value_ = 0;
  _impl_._has_bits_[0] &= ~0x00000010u;
}
inline ::int32_t ExRankEntry::pb_rank_value() const {
  // @@protoc_insertion_point(field_get:ExRankEntry.pb_rank_value)
  return _internal_pb_rank_value();
}
inline void ExRankEntry::set_pb_rank_value(::int32_t value) {
  _internal_set_pb_rank_value(value);
  _impl_._has_bits_[0] |= 0x00000010u;
  // @@protoc_insertion_point(field_set:ExRankEntry.pb_rank_value)
}
inline ::int32_t ExRankEntry::_internal_pb_rank_value() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.pb_rank_value_;
}
inline void ExRankEntry::_internal_set_pb_rank_value(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pb_rank_value_ = value;
}

// required int64 pb_rank_time = 3;
inline bool ExRankEntry::has_pb_rank_time() const {
  bool value = (_impl_._has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline void ExRankEntry::clear_pb_rank_time() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pb_rank_time_ = ::int64_t{0};
  _impl_._has_bits_[0] &= ~0x00000008u;
}
inline ::int64_t ExRankEntry::pb_rank_time() const {
  // @@protoc_insertion_point(field_get:ExRankEntry.pb_rank_time)
  return _internal_pb_rank_time();
}
inline void ExRankEntry::set_pb_rank_time(::int64_t value) {
  _internal_set_pb_rank_time(value);
  _impl_._has_bits_[0] |= 0x00000008u;
  // @@protoc_insertion_point(field_set:ExRankEntry.pb_rank_time)
}
inline ::int64_t ExRankEntry::_internal_pb_rank_time() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.pb_rank_time_;
}
inline void ExRankEntry::_internal_set_pb_rank_time(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pb_rank_time_ = value;
}

// required int32 pb_icon_id = 4;
inline bool ExRankEntry::has_pb_icon_id() const {
  bool value = (_impl_._has_bits_[0] & 0x00000020u) != 0;
  return value;
}
inline void ExRankEntry::clear_pb_icon_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pb_icon_id_ = 0;
  _impl_._has_bits_[0] &= ~0x00000020u;
}
inline ::int32_t ExRankEntry::pb_icon_id() const {
  // @@protoc_insertion_point(field_get:ExRankEntry.pb_icon_id)
  return _internal_pb_icon_id();
}
inline void ExRankEntry::set_pb_icon_id(::int32_t value) {
  _internal_set_pb_icon_id(value);
  _impl_._has_bits_[0] |= 0x00000020u;
  // @@protoc_insertion_point(field_set:ExRankEntry.pb_icon_id)
}
inline ::int32_t ExRankEntry::_internal_pb_icon_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.pb_icon_id_;
}
inline void ExRankEntry::_internal_set_pb_icon_id(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pb_icon_id_ = value;
}

// required string pb_nickname = 5;
inline bool ExRankEntry::has_pb_nickname() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void ExRankEntry::clear_pb_nickname() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pb_nickname_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& ExRankEntry::pb_nickname() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:ExRankEntry.pb_nickname)
  return _internal_pb_nickname();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void ExRankEntry::set_pb_nickname(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.pb_nickname_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:ExRankEntry.pb_nickname)
}
inline std::string* ExRankEntry::mutable_pb_nickname() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_pb_nickname();
  // @@protoc_insertion_point(field_mutable:ExRankEntry.pb_nickname)
  return _s;
}
inline const std::string& ExRankEntry::_internal_pb_nickname() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.pb_nickname_.Get();
}
inline void ExRankEntry::_internal_set_pb_nickname(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.pb_nickname_.Set(value, GetArena());
}
inline std::string* ExRankEntry::_internal_mutable_pb_nickname() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.pb_nickname_.Mutable( GetArena());
}
inline std::string* ExRankEntry::release_pb_nickname() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:ExRankEntry.pb_nickname)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.pb_nickname_.Release();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.pb_nickname_.Set("", GetArena());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return released;
}
inline void ExRankEntry::set_allocated_pb_nickname(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.pb_nickname_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.pb_nickname_.IsDefault()) {
          _impl_.pb_nickname_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ExRankEntry.pb_nickname)
}

// optional int32 pb_title_id = 6;
inline bool ExRankEntry::has_pb_title_id() const {
  bool value = (_impl_._has_bits_[0] & 0x00000040u) != 0;
  return value;
}
inline void ExRankEntry::clear_pb_title_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pb_title_id_ = 0;
  _impl_._has_bits_[0] &= ~0x00000040u;
}
inline ::int32_t ExRankEntry::pb_title_id() const {
  // @@protoc_insertion_point(field_get:ExRankEntry.pb_title_id)
  return _internal_pb_title_id();
}
inline void ExRankEntry::set_pb_title_id(::int32_t value) {
  _internal_set_pb_title_id(value);
  _impl_._has_bits_[0] |= 0x00000040u;
  // @@protoc_insertion_point(field_set:ExRankEntry.pb_title_id)
}
inline ::int32_t ExRankEntry::_internal_pb_title_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.pb_title_id_;
}
inline void ExRankEntry::_internal_set_pb_title_id(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pb_title_id_ = value;
}

// optional string pb_param_1 = 7;
inline bool ExRankEntry::has_pb_param_1() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline void ExRankEntry::clear_pb_param_1() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pb_param_1_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const std::string& ExRankEntry::pb_param_1() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:ExRankEntry.pb_param_1)
  return _internal_pb_param_1();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void ExRankEntry::set_pb_param_1(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.pb_param_1_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:ExRankEntry.pb_param_1)
}
inline std::string* ExRankEntry::mutable_pb_param_1() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_pb_param_1();
  // @@protoc_insertion_point(field_mutable:ExRankEntry.pb_param_1)
  return _s;
}
inline const std::string& ExRankEntry::_internal_pb_param_1() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.pb_param_1_.Get();
}
inline void ExRankEntry::_internal_set_pb_param_1(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.pb_param_1_.Set(value, GetArena());
}
inline std::string* ExRankEntry::_internal_mutable_pb_param_1() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  return _impl_.pb_param_1_.Mutable( GetArena());
}
inline std::string* ExRankEntry::release_pb_param_1() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:ExRankEntry.pb_param_1)
  if ((_impl_._has_bits_[0] & 0x00000002u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000002u;
  auto* released = _impl_.pb_param_1_.Release();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.pb_param_1_.Set("", GetArena());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return released;
}
inline void ExRankEntry::set_allocated_pb_param_1(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  _impl_.pb_param_1_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.pb_param_1_.IsDefault()) {
          _impl_.pb_param_1_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ExRankEntry.pb_param_1)
}

// optional int32 pb_lv = 8;
inline bool ExRankEntry::has_pb_lv() const {
  bool value = (_impl_._has_bits_[0] & 0x00000080u) != 0;
  return value;
}
inline void ExRankEntry::clear_pb_lv() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pb_lv_ = 0;
  _impl_._has_bits_[0] &= ~0x00000080u;
}
inline ::int32_t ExRankEntry::pb_lv() const {
  // @@protoc_insertion_point(field_get:ExRankEntry.pb_lv)
  return _internal_pb_lv();
}
inline void ExRankEntry::set_pb_lv(::int32_t value) {
  _internal_set_pb_lv(value);
  _impl_._has_bits_[0] |= 0x00000080u;
  // @@protoc_insertion_point(field_set:ExRankEntry.pb_lv)
}
inline ::int32_t ExRankEntry::_internal_pb_lv() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.pb_lv_;
}
inline void ExRankEntry::_internal_set_pb_lv(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pb_lv_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_ExNewRankData_2eproto_2epb_2eh
