// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ExNewRankMsg.proto
// Protobuf C++ Version: 5.27.0

#ifndef GOOGLE_PROTOBUF_INCLUDED_ExNewRankMsg_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_ExNewRankMsg_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5027000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "ExNewRankData.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_ExNewRankMsg_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_ExNewRankMsg_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_ExNewRankMsg_2eproto;
class DceGetRankListNew;
struct DceGetRankListNewDefaultTypeInternal;
extern DceGetRankListNewDefaultTypeInternal _DceGetRankListNew_default_instance_;
class DseGetRankListNew;
struct DseGetRankListNewDefaultTypeInternal;
extern DseGetRankListNewDefaultTypeInternal _DseGetRankListNew_default_instance_;
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google


// ===================================================================


// -------------------------------------------------------------------

class DceGetRankListNew final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:DceGetRankListNew) */ {
 public:
  inline DceGetRankListNew() : DceGetRankListNew(nullptr) {}
  ~DceGetRankListNew() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR DceGetRankListNew(
      ::google::protobuf::internal::ConstantInitialized);

  inline DceGetRankListNew(const DceGetRankListNew& from) : DceGetRankListNew(nullptr, from) {}
  inline DceGetRankListNew(DceGetRankListNew&& from) noexcept
      : DceGetRankListNew(nullptr, std::move(from)) {}
  inline DceGetRankListNew& operator=(const DceGetRankListNew& from) {
    CopyFrom(from);
    return *this;
  }
  inline DceGetRankListNew& operator=(DceGetRankListNew&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const DceGetRankListNew& default_instance() {
    return *internal_default_instance();
  }
  static inline const DceGetRankListNew* internal_default_instance() {
    return reinterpret_cast<const DceGetRankListNew*>(
        &_DceGetRankListNew_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(DceGetRankListNew& a, DceGetRankListNew& b) { a.Swap(&b); }
  inline void Swap(DceGetRankListNew* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(DceGetRankListNew* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  DceGetRankListNew* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::Message::DefaultConstruct<DceGetRankListNew>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const DceGetRankListNew& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const DceGetRankListNew& from) { DceGetRankListNew::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return IsInitializedImpl(*this);
  }

  private:
  static bool IsInitializedImpl(const MessageLite& msg);

  public:
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(DceGetRankListNew* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "DceGetRankListNew"; }

 protected:
  explicit DceGetRankListNew(::google::protobuf::Arena* arena);
  DceGetRankListNew(::google::protobuf::Arena* arena, const DceGetRankListNew& from);
  DceGetRankListNew(::google::protobuf::Arena* arena, DceGetRankListNew&& from) noexcept
      : DceGetRankListNew(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const final;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kPbRankTypeFieldNumber = 1,
  };
  // required int32 pb_rank_type = 1;
  bool has_pb_rank_type() const;
  void clear_pb_rank_type() ;
  ::int32_t pb_rank_type() const;
  void set_pb_rank_type(::int32_t value);

  private:
  ::int32_t _internal_pb_rank_type() const;
  void _internal_set_pb_rank_type(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:DceGetRankListNew)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 0,
      0, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_DceGetRankListNew_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const DceGetRankListNew& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    ::int32_t pb_rank_type_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ExNewRankMsg_2eproto;
};
// -------------------------------------------------------------------

class DseGetRankListNew final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:DseGetRankListNew) */ {
 public:
  inline DseGetRankListNew() : DseGetRankListNew(nullptr) {}
  ~DseGetRankListNew() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR DseGetRankListNew(
      ::google::protobuf::internal::ConstantInitialized);

  inline DseGetRankListNew(const DseGetRankListNew& from) : DseGetRankListNew(nullptr, from) {}
  inline DseGetRankListNew(DseGetRankListNew&& from) noexcept
      : DseGetRankListNew(nullptr, std::move(from)) {}
  inline DseGetRankListNew& operator=(const DseGetRankListNew& from) {
    CopyFrom(from);
    return *this;
  }
  inline DseGetRankListNew& operator=(DseGetRankListNew&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const DseGetRankListNew& default_instance() {
    return *internal_default_instance();
  }
  static inline const DseGetRankListNew* internal_default_instance() {
    return reinterpret_cast<const DseGetRankListNew*>(
        &_DseGetRankListNew_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(DseGetRankListNew& a, DseGetRankListNew& b) { a.Swap(&b); }
  inline void Swap(DseGetRankListNew* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(DseGetRankListNew* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  DseGetRankListNew* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::Message::DefaultConstruct<DseGetRankListNew>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const DseGetRankListNew& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const DseGetRankListNew& from) { DseGetRankListNew::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return IsInitializedImpl(*this);
  }

  private:
  static bool IsInitializedImpl(const MessageLite& msg);

  public:
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(DseGetRankListNew* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "DseGetRankListNew"; }

 protected:
  explicit DseGetRankListNew(::google::protobuf::Arena* arena);
  DseGetRankListNew(::google::protobuf::Arena* arena, const DseGetRankListNew& from);
  DseGetRankListNew(::google::protobuf::Arena* arena, DseGetRankListNew&& from) noexcept
      : DseGetRankListNew(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const final;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kPbRankListFieldNumber = 2,
    kPbRankTypeFieldNumber = 1,
  };
  // repeated .ExRankEntry pb_rank_list = 2;
  int pb_rank_list_size() const;
  private:
  int _internal_pb_rank_list_size() const;

  public:
  void clear_pb_rank_list() ;
  ::ExRankEntry* mutable_pb_rank_list(int index);
  ::google::protobuf::RepeatedPtrField<::ExRankEntry>* mutable_pb_rank_list();

  private:
  const ::google::protobuf::RepeatedPtrField<::ExRankEntry>& _internal_pb_rank_list() const;
  ::google::protobuf::RepeatedPtrField<::ExRankEntry>* _internal_mutable_pb_rank_list();
  public:
  const ::ExRankEntry& pb_rank_list(int index) const;
  ::ExRankEntry* add_pb_rank_list();
  const ::google::protobuf::RepeatedPtrField<::ExRankEntry>& pb_rank_list() const;
  // required int32 pb_rank_type = 1;
  bool has_pb_rank_type() const;
  void clear_pb_rank_type() ;
  ::int32_t pb_rank_type() const;
  void set_pb_rank_type(::int32_t value);

  private:
  ::int32_t _internal_pb_rank_type() const;
  void _internal_set_pb_rank_type(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:DseGetRankListNew)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 1,
      0, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_DseGetRankListNew_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const DseGetRankListNew& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField< ::ExRankEntry > pb_rank_list_;
    ::int32_t pb_rank_type_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ExNewRankMsg_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// DceGetRankListNew

// required int32 pb_rank_type = 1;
inline bool DceGetRankListNew::has_pb_rank_type() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void DceGetRankListNew::clear_pb_rank_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pb_rank_type_ = 0;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline ::int32_t DceGetRankListNew::pb_rank_type() const {
  // @@protoc_insertion_point(field_get:DceGetRankListNew.pb_rank_type)
  return _internal_pb_rank_type();
}
inline void DceGetRankListNew::set_pb_rank_type(::int32_t value) {
  _internal_set_pb_rank_type(value);
  _impl_._has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_set:DceGetRankListNew.pb_rank_type)
}
inline ::int32_t DceGetRankListNew::_internal_pb_rank_type() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.pb_rank_type_;
}
inline void DceGetRankListNew::_internal_set_pb_rank_type(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pb_rank_type_ = value;
}

// -------------------------------------------------------------------

// DseGetRankListNew

// required int32 pb_rank_type = 1;
inline bool DseGetRankListNew::has_pb_rank_type() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void DseGetRankListNew::clear_pb_rank_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pb_rank_type_ = 0;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline ::int32_t DseGetRankListNew::pb_rank_type() const {
  // @@protoc_insertion_point(field_get:DseGetRankListNew.pb_rank_type)
  return _internal_pb_rank_type();
}
inline void DseGetRankListNew::set_pb_rank_type(::int32_t value) {
  _internal_set_pb_rank_type(value);
  _impl_._has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_set:DseGetRankListNew.pb_rank_type)
}
inline ::int32_t DseGetRankListNew::_internal_pb_rank_type() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.pb_rank_type_;
}
inline void DseGetRankListNew::_internal_set_pb_rank_type(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pb_rank_type_ = value;
}

// repeated .ExRankEntry pb_rank_list = 2;
inline int DseGetRankListNew::_internal_pb_rank_list_size() const {
  return _internal_pb_rank_list().size();
}
inline int DseGetRankListNew::pb_rank_list_size() const {
  return _internal_pb_rank_list_size();
}
inline ::ExRankEntry* DseGetRankListNew::mutable_pb_rank_list(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:DseGetRankListNew.pb_rank_list)
  return _internal_mutable_pb_rank_list()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::ExRankEntry>* DseGetRankListNew::mutable_pb_rank_list()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:DseGetRankListNew.pb_rank_list)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_pb_rank_list();
}
inline const ::ExRankEntry& DseGetRankListNew::pb_rank_list(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:DseGetRankListNew.pb_rank_list)
  return _internal_pb_rank_list().Get(index);
}
inline ::ExRankEntry* DseGetRankListNew::add_pb_rank_list() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::ExRankEntry* _add = _internal_mutable_pb_rank_list()->Add();
  // @@protoc_insertion_point(field_add:DseGetRankListNew.pb_rank_list)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::ExRankEntry>& DseGetRankListNew::pb_rank_list() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:DseGetRankListNew.pb_rank_list)
  return _internal_pb_rank_list();
}
inline const ::google::protobuf::RepeatedPtrField<::ExRankEntry>&
DseGetRankListNew::_internal_pb_rank_list() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.pb_rank_list_;
}
inline ::google::protobuf::RepeatedPtrField<::ExRankEntry>*
DseGetRankListNew::_internal_mutable_pb_rank_list() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.pb_rank_list_;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_ExNewRankMsg_2eproto_2epb_2eh
