// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ExNewRankMsg.proto
// Protobuf C++ Version: 5.27.0

#include "ExNewRankMsg.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;

inline constexpr DceGetRankListNew::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        pb_rank_type_{0} {}

template <typename>
PROTOBUF_CONSTEXPR DceGetRankListNew::DceGetRankListNew(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct DceGetRankListNewDefaultTypeInternal {
  PROTOBUF_CONSTEXPR DceGetRankListNewDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~DceGetRankListNewDefaultTypeInternal() {}
  union {
    DceGetRankListNew _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 DceGetRankListNewDefaultTypeInternal _DceGetRankListNew_default_instance_;

inline constexpr DseGetRankListNew::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        pb_rank_list_{},
        pb_rank_type_{0} {}

template <typename>
PROTOBUF_CONSTEXPR DseGetRankListNew::DseGetRankListNew(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct DseGetRankListNewDefaultTypeInternal {
  PROTOBUF_CONSTEXPR DseGetRankListNewDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~DseGetRankListNewDefaultTypeInternal() {}
  union {
    DseGetRankListNew _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 DseGetRankListNewDefaultTypeInternal _DseGetRankListNew_default_instance_;
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_ExNewRankMsg_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_ExNewRankMsg_2eproto = nullptr;
const ::uint32_t
    TableStruct_ExNewRankMsg_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        PROTOBUF_FIELD_OFFSET(::DceGetRankListNew, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::DceGetRankListNew, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::DceGetRankListNew, _impl_.pb_rank_type_),
        0,
        PROTOBUF_FIELD_OFFSET(::DseGetRankListNew, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::DseGetRankListNew, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::DseGetRankListNew, _impl_.pb_rank_type_),
        PROTOBUF_FIELD_OFFSET(::DseGetRankListNew, _impl_.pb_rank_list_),
        0,
        ~0u,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, 9, -1, sizeof(::DceGetRankListNew)},
        {10, 20, -1, sizeof(::DseGetRankListNew)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::_DceGetRankListNew_default_instance_._instance,
    &::_DseGetRankListNew_default_instance_._instance,
};
const char descriptor_table_protodef_ExNewRankMsg_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\022ExNewRankMsg.proto\032\023ExNewRankData.prot"
    "o\")\n\021DceGetRankListNew\022\024\n\014pb_rank_type\030\001"
    " \002(\005\"M\n\021DseGetRankListNew\022\024\n\014pb_rank_typ"
    "e\030\001 \002(\005\022\"\n\014pb_rank_list\030\002 \003(\0132\014.ExRankEn"
    "try"
};
static const ::_pbi::DescriptorTable* const descriptor_table_ExNewRankMsg_2eproto_deps[1] =
    {
        &::descriptor_table_ExNewRankData_2eproto,
};
static ::absl::once_flag descriptor_table_ExNewRankMsg_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_ExNewRankMsg_2eproto = {
    false,
    false,
    163,
    descriptor_table_protodef_ExNewRankMsg_2eproto,
    "ExNewRankMsg.proto",
    &descriptor_table_ExNewRankMsg_2eproto_once,
    descriptor_table_ExNewRankMsg_2eproto_deps,
    1,
    2,
    schemas,
    file_default_instances,
    TableStruct_ExNewRankMsg_2eproto::offsets,
    file_level_enum_descriptors_ExNewRankMsg_2eproto,
    file_level_service_descriptors_ExNewRankMsg_2eproto,
};
// ===================================================================

class DceGetRankListNew::_Internal {
 public:
  using HasBits =
      decltype(std::declval<DceGetRankListNew>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(DceGetRankListNew, _impl_._has_bits_);
  static bool MissingRequiredFields(const HasBits& has_bits) {
    return ((has_bits[0] & 0x00000001) ^ 0x00000001) != 0;
  }
};

DceGetRankListNew::DceGetRankListNew(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:DceGetRankListNew)
}
DceGetRankListNew::DceGetRankListNew(
    ::google::protobuf::Arena* arena, const DceGetRankListNew& from)
    : DceGetRankListNew(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE DceGetRankListNew::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void DceGetRankListNew::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.pb_rank_type_ = {};
}
DceGetRankListNew::~DceGetRankListNew() {
  // @@protoc_insertion_point(destructor:DceGetRankListNew)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void DceGetRankListNew::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
DceGetRankListNew::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              DceGetRankListNew::IsInitializedImpl,
              PROTOBUF_FIELD_OFFSET(DceGetRankListNew, _impl_._cached_size_),
              false,
          },
          &DceGetRankListNew::MergeImpl,
          &DceGetRankListNew::kDescriptorMethods,
          &descriptor_table_ExNewRankMsg_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> DceGetRankListNew::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(DceGetRankListNew, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_DceGetRankListNew_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::DceGetRankListNew>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // required int32 pb_rank_type = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(DceGetRankListNew, _impl_.pb_rank_type_), 0>(),
     {8, 0, 0, PROTOBUF_FIELD_OFFSET(DceGetRankListNew, _impl_.pb_rank_type_)}},
  }}, {{
    65535, 65535
  }}, {{
    // required int32 pb_rank_type = 1;
    {PROTOBUF_FIELD_OFFSET(DceGetRankListNew, _impl_.pb_rank_type_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void DceGetRankListNew::Clear() {
// @@protoc_insertion_point(message_clear_start:DceGetRankListNew)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.pb_rank_type_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* DceGetRankListNew::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:DceGetRankListNew)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // required int32 pb_rank_type = 1;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<1>(
            stream, this->_internal_pb_rank_type(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:DceGetRankListNew)
  return target;
}

::size_t DceGetRankListNew::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:DceGetRankListNew)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // required int32 pb_rank_type = 1;
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_pb_rank_type());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void DceGetRankListNew::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<DceGetRankListNew*>(&to_msg);
  auto& from = static_cast<const DceGetRankListNew&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:DceGetRankListNew)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    _this->_impl_.pb_rank_type_ = from._impl_.pb_rank_type_;
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void DceGetRankListNew::CopyFrom(const DceGetRankListNew& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:DceGetRankListNew)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool DceGetRankListNew::IsInitializedImpl(
    const MessageLite& msg) {
  auto& this_ = static_cast<const DceGetRankListNew&>(msg);
  if (_Internal::MissingRequiredFields(this_._impl_._has_bits_)) {
    return false;
  }
  return true;
}

void DceGetRankListNew::InternalSwap(DceGetRankListNew* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
        swap(_impl_.pb_rank_type_, other->_impl_.pb_rank_type_);
}

::google::protobuf::Metadata DceGetRankListNew::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class DseGetRankListNew::_Internal {
 public:
  using HasBits =
      decltype(std::declval<DseGetRankListNew>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(DseGetRankListNew, _impl_._has_bits_);
  static bool MissingRequiredFields(const HasBits& has_bits) {
    return ((has_bits[0] & 0x00000001) ^ 0x00000001) != 0;
  }
};

void DseGetRankListNew::clear_pb_rank_list() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pb_rank_list_.Clear();
}
DseGetRankListNew::DseGetRankListNew(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:DseGetRankListNew)
}
inline PROTOBUF_NDEBUG_INLINE DseGetRankListNew::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::DseGetRankListNew& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        pb_rank_list_{visibility, arena, from.pb_rank_list_} {}

DseGetRankListNew::DseGetRankListNew(
    ::google::protobuf::Arena* arena,
    const DseGetRankListNew& from)
    : ::google::protobuf::Message(arena) {
  DseGetRankListNew* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.pb_rank_type_ = from._impl_.pb_rank_type_;

  // @@protoc_insertion_point(copy_constructor:DseGetRankListNew)
}
inline PROTOBUF_NDEBUG_INLINE DseGetRankListNew::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        pb_rank_list_{visibility, arena} {}

inline void DseGetRankListNew::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.pb_rank_type_ = {};
}
DseGetRankListNew::~DseGetRankListNew() {
  // @@protoc_insertion_point(destructor:DseGetRankListNew)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void DseGetRankListNew::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
DseGetRankListNew::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              DseGetRankListNew::IsInitializedImpl,
              PROTOBUF_FIELD_OFFSET(DseGetRankListNew, _impl_._cached_size_),
              false,
          },
          &DseGetRankListNew::MergeImpl,
          &DseGetRankListNew::kDescriptorMethods,
          &descriptor_table_ExNewRankMsg_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 1, 0, 2> DseGetRankListNew::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(DseGetRankListNew, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_DseGetRankListNew_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::DseGetRankListNew>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated .ExRankEntry pb_rank_list = 2;
    {::_pbi::TcParser::FastMtR1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(DseGetRankListNew, _impl_.pb_rank_list_)}},
    // required int32 pb_rank_type = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(DseGetRankListNew, _impl_.pb_rank_type_), 0>(),
     {8, 0, 0, PROTOBUF_FIELD_OFFSET(DseGetRankListNew, _impl_.pb_rank_type_)}},
  }}, {{
    65535, 65535
  }}, {{
    // required int32 pb_rank_type = 1;
    {PROTOBUF_FIELD_OFFSET(DseGetRankListNew, _impl_.pb_rank_type_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // repeated .ExRankEntry pb_rank_list = 2;
    {PROTOBUF_FIELD_OFFSET(DseGetRankListNew, _impl_.pb_rank_list_), -1, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::ExRankEntry>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void DseGetRankListNew::Clear() {
// @@protoc_insertion_point(message_clear_start:DseGetRankListNew)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.pb_rank_list_.Clear();
  _impl_.pb_rank_type_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* DseGetRankListNew::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:DseGetRankListNew)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // required int32 pb_rank_type = 1;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<1>(
            stream, this->_internal_pb_rank_type(), target);
  }

  // repeated .ExRankEntry pb_rank_list = 2;
  for (unsigned i = 0, n = static_cast<unsigned>(
                           this->_internal_pb_rank_list_size());
       i < n; i++) {
    const auto& repfield = this->_internal_pb_rank_list().Get(i);
    target =
        ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
            2, repfield, repfield.GetCachedSize(),
            target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:DseGetRankListNew)
  return target;
}

::size_t DseGetRankListNew::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:DseGetRankListNew)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(reinterpret_cast<const void*>(this));
  // repeated .ExRankEntry pb_rank_list = 2;
  total_size += 1UL * this->_internal_pb_rank_list_size();
  for (const auto& msg : this->_internal_pb_rank_list()) {
    total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
  }
  // required int32 pb_rank_type = 1;
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_pb_rank_type());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void DseGetRankListNew::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<DseGetRankListNew*>(&to_msg);
  auto& from = static_cast<const DseGetRankListNew&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:DseGetRankListNew)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_pb_rank_list()->MergeFrom(
      from._internal_pb_rank_list());
  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    _this->_impl_.pb_rank_type_ = from._impl_.pb_rank_type_;
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void DseGetRankListNew::CopyFrom(const DseGetRankListNew& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:DseGetRankListNew)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool DseGetRankListNew::IsInitializedImpl(
    const MessageLite& msg) {
  auto& this_ = static_cast<const DseGetRankListNew&>(msg);
  if (_Internal::MissingRequiredFields(this_._impl_._has_bits_)) {
    return false;
  }
  if (!::google::protobuf::internal::AllAreInitialized(this_._internal_pb_rank_list()))
    return false;
  return true;
}

void DseGetRankListNew::InternalSwap(DseGetRankListNew* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.pb_rank_list_.InternalSwap(&other->_impl_.pb_rank_list_);
        swap(_impl_.pb_rank_type_, other->_impl_.pb_rank_type_);
}

::google::protobuf::Metadata DseGetRankListNew::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_ExNewRankMsg_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
