// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ExNewRankData.proto
// Protobuf C++ Version: 5.27.0

#include "ExNewRankData.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;

inline constexpr ExRankEntry::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        pb_nickname_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        pb_param_1_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        pb_uid_{::int64_t{0}},
        pb_rank_time_{::int64_t{0}},
        pb_rank_value_{0},
        pb_icon_id_{0},
        pb_title_id_{0},
        pb_lv_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ExRankEntry::ExRankEntry(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct ExRankEntryDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ExRankEntryDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ExRankEntryDefaultTypeInternal() {}
  union {
    ExRankEntry _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ExRankEntryDefaultTypeInternal _ExRankEntry_default_instance_;
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_ExNewRankData_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_ExNewRankData_2eproto = nullptr;
const ::uint32_t
    TableStruct_ExNewRankData_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        PROTOBUF_FIELD_OFFSET(::ExRankEntry, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::ExRankEntry, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::ExRankEntry, _impl_.pb_uid_),
        PROTOBUF_FIELD_OFFSET(::ExRankEntry, _impl_.pb_rank_value_),
        PROTOBUF_FIELD_OFFSET(::ExRankEntry, _impl_.pb_rank_time_),
        PROTOBUF_FIELD_OFFSET(::ExRankEntry, _impl_.pb_icon_id_),
        PROTOBUF_FIELD_OFFSET(::ExRankEntry, _impl_.pb_nickname_),
        PROTOBUF_FIELD_OFFSET(::ExRankEntry, _impl_.pb_title_id_),
        PROTOBUF_FIELD_OFFSET(::ExRankEntry, _impl_.pb_param_1_),
        PROTOBUF_FIELD_OFFSET(::ExRankEntry, _impl_.pb_lv_),
        2,
        4,
        3,
        5,
        0,
        6,
        1,
        7,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, 16, -1, sizeof(::ExRankEntry)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::_ExRankEntry_default_instance_._instance,
};
const char descriptor_table_protodef_ExNewRankData_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\023ExNewRankData.proto\"\253\001\n\013ExRankEntry\022\016\n"
    "\006pb_uid\030\001 \002(\003\022\025\n\rpb_rank_value\030\002 \002(\005\022\024\n\014"
    "pb_rank_time\030\003 \002(\003\022\022\n\npb_icon_id\030\004 \002(\005\022\023"
    "\n\013pb_nickname\030\005 \002(\t\022\023\n\013pb_title_id\030\006 \001(\005"
    "\022\022\n\npb_param_1\030\007 \001(\t\022\r\n\005pb_lv\030\010 \001(\005"
};
static ::absl::once_flag descriptor_table_ExNewRankData_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_ExNewRankData_2eproto = {
    false,
    false,
    195,
    descriptor_table_protodef_ExNewRankData_2eproto,
    "ExNewRankData.proto",
    &descriptor_table_ExNewRankData_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_ExNewRankData_2eproto::offsets,
    file_level_enum_descriptors_ExNewRankData_2eproto,
    file_level_service_descriptors_ExNewRankData_2eproto,
};
// ===================================================================

class ExRankEntry::_Internal {
 public:
  using HasBits =
      decltype(std::declval<ExRankEntry>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(ExRankEntry, _impl_._has_bits_);
  static bool MissingRequiredFields(const HasBits& has_bits) {
    return ((has_bits[0] & 0x0000003d) ^ 0x0000003d) != 0;
  }
};

ExRankEntry::ExRankEntry(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:ExRankEntry)
}
inline PROTOBUF_NDEBUG_INLINE ExRankEntry::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::ExRankEntry& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        pb_nickname_(arena, from.pb_nickname_),
        pb_param_1_(arena, from.pb_param_1_) {}

ExRankEntry::ExRankEntry(
    ::google::protobuf::Arena* arena,
    const ExRankEntry& from)
    : ::google::protobuf::Message(arena) {
  ExRankEntry* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, pb_uid_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, pb_uid_),
           offsetof(Impl_, pb_lv_) -
               offsetof(Impl_, pb_uid_) +
               sizeof(Impl_::pb_lv_));

  // @@protoc_insertion_point(copy_constructor:ExRankEntry)
}
inline PROTOBUF_NDEBUG_INLINE ExRankEntry::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        pb_nickname_(arena),
        pb_param_1_(arena) {}

inline void ExRankEntry::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, pb_uid_),
           0,
           offsetof(Impl_, pb_lv_) -
               offsetof(Impl_, pb_uid_) +
               sizeof(Impl_::pb_lv_));
}
ExRankEntry::~ExRankEntry() {
  // @@protoc_insertion_point(destructor:ExRankEntry)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void ExRankEntry::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.pb_nickname_.Destroy();
  _impl_.pb_param_1_.Destroy();
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
ExRankEntry::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              ExRankEntry::IsInitializedImpl,
              PROTOBUF_FIELD_OFFSET(ExRankEntry, _impl_._cached_size_),
              false,
          },
          &ExRankEntry::MergeImpl,
          &ExRankEntry::kDescriptorMethods,
          &descriptor_table_ExNewRankData_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 8, 0, 49, 2> ExRankEntry::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(ExRankEntry, _impl_._has_bits_),
    0, // no _extensions_
    8, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967040,  // skipmap
    offsetof(decltype(_table_), field_entries),
    8,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_ExRankEntry_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::ExRankEntry>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // optional int32 pb_lv = 8;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ExRankEntry, _impl_.pb_lv_), 7>(),
     {64, 7, 0, PROTOBUF_FIELD_OFFSET(ExRankEntry, _impl_.pb_lv_)}},
    // required int64 pb_uid = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(ExRankEntry, _impl_.pb_uid_), 2>(),
     {8, 2, 0, PROTOBUF_FIELD_OFFSET(ExRankEntry, _impl_.pb_uid_)}},
    // required int32 pb_rank_value = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ExRankEntry, _impl_.pb_rank_value_), 4>(),
     {16, 4, 0, PROTOBUF_FIELD_OFFSET(ExRankEntry, _impl_.pb_rank_value_)}},
    // required int64 pb_rank_time = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(ExRankEntry, _impl_.pb_rank_time_), 3>(),
     {24, 3, 0, PROTOBUF_FIELD_OFFSET(ExRankEntry, _impl_.pb_rank_time_)}},
    // required int32 pb_icon_id = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ExRankEntry, _impl_.pb_icon_id_), 5>(),
     {32, 5, 0, PROTOBUF_FIELD_OFFSET(ExRankEntry, _impl_.pb_icon_id_)}},
    // required string pb_nickname = 5;
    {::_pbi::TcParser::FastSS1,
     {42, 0, 0, PROTOBUF_FIELD_OFFSET(ExRankEntry, _impl_.pb_nickname_)}},
    // optional int32 pb_title_id = 6;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ExRankEntry, _impl_.pb_title_id_), 6>(),
     {48, 6, 0, PROTOBUF_FIELD_OFFSET(ExRankEntry, _impl_.pb_title_id_)}},
    // optional string pb_param_1 = 7;
    {::_pbi::TcParser::FastSS1,
     {58, 1, 0, PROTOBUF_FIELD_OFFSET(ExRankEntry, _impl_.pb_param_1_)}},
  }}, {{
    65535, 65535
  }}, {{
    // required int64 pb_uid = 1;
    {PROTOBUF_FIELD_OFFSET(ExRankEntry, _impl_.pb_uid_), _Internal::kHasBitsOffset + 2, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
    // required int32 pb_rank_value = 2;
    {PROTOBUF_FIELD_OFFSET(ExRankEntry, _impl_.pb_rank_value_), _Internal::kHasBitsOffset + 4, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // required int64 pb_rank_time = 3;
    {PROTOBUF_FIELD_OFFSET(ExRankEntry, _impl_.pb_rank_time_), _Internal::kHasBitsOffset + 3, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
    // required int32 pb_icon_id = 4;
    {PROTOBUF_FIELD_OFFSET(ExRankEntry, _impl_.pb_icon_id_), _Internal::kHasBitsOffset + 5, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // required string pb_nickname = 5;
    {PROTOBUF_FIELD_OFFSET(ExRankEntry, _impl_.pb_nickname_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kRawString | ::_fl::kRepAString)},
    // optional int32 pb_title_id = 6;
    {PROTOBUF_FIELD_OFFSET(ExRankEntry, _impl_.pb_title_id_), _Internal::kHasBitsOffset + 6, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // optional string pb_param_1 = 7;
    {PROTOBUF_FIELD_OFFSET(ExRankEntry, _impl_.pb_param_1_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kRawString | ::_fl::kRepAString)},
    // optional int32 pb_lv = 8;
    {PROTOBUF_FIELD_OFFSET(ExRankEntry, _impl_.pb_lv_), _Internal::kHasBitsOffset + 7, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
    "\13\0\0\0\0\13\0\12\0\0\0\0\0\0\0\0"
    "ExRankEntry"
    "pb_nickname"
    "pb_param_1"
  }},
};

PROTOBUF_NOINLINE void ExRankEntry::Clear() {
// @@protoc_insertion_point(message_clear_start:ExRankEntry)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _impl_.pb_nickname_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000002u) {
      _impl_.pb_param_1_.ClearNonDefaultToEmpty();
    }
  }
  if (cached_has_bits & 0x000000fcu) {
    ::memset(&_impl_.pb_uid_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.pb_lv_) -
        reinterpret_cast<char*>(&_impl_.pb_uid_)) + sizeof(_impl_.pb_lv_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* ExRankEntry::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ExRankEntry)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // required int64 pb_uid = 1;
  if (cached_has_bits & 0x00000004u) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt64ToArrayWithField<1>(
            stream, this->_internal_pb_uid(), target);
  }

  // required int32 pb_rank_value = 2;
  if (cached_has_bits & 0x00000010u) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<2>(
            stream, this->_internal_pb_rank_value(), target);
  }

  // required int64 pb_rank_time = 3;
  if (cached_has_bits & 0x00000008u) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt64ToArrayWithField<3>(
            stream, this->_internal_pb_rank_time(), target);
  }

  // required int32 pb_icon_id = 4;
  if (cached_has_bits & 0x00000020u) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<4>(
            stream, this->_internal_pb_icon_id(), target);
  }

  // required string pb_nickname = 5;
  if (cached_has_bits & 0x00000001u) {
    const std::string& _s = this->_internal_pb_nickname();
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(_s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormat::SERIALIZE,
                                "ExRankEntry.pb_nickname");
    target = stream->WriteStringMaybeAliased(5, _s, target);
  }

  // optional int32 pb_title_id = 6;
  if (cached_has_bits & 0x00000040u) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<6>(
            stream, this->_internal_pb_title_id(), target);
  }

  // optional string pb_param_1 = 7;
  if (cached_has_bits & 0x00000002u) {
    const std::string& _s = this->_internal_pb_param_1();
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(_s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormat::SERIALIZE,
                                "ExRankEntry.pb_param_1");
    target = stream->WriteStringMaybeAliased(7, _s, target);
  }

  // optional int32 pb_lv = 8;
  if (cached_has_bits & 0x00000080u) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<8>(
            stream, this->_internal_pb_lv(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ExRankEntry)
  return target;
}

::size_t ExRankEntry::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ExRankEntry)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(reinterpret_cast<const void*>(this));
  // required string pb_nickname = 5;
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_pb_nickname());
  }

  // optional string pb_param_1 = 7;
  if (cached_has_bits & 0x00000002u) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_pb_param_1());
  }

  if (cached_has_bits & 0x0000003cu) {
    // required int64 pb_uid = 1;
    if (cached_has_bits & 0x00000004u) {
      total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
          this->_internal_pb_uid());
    }

    // required int64 pb_rank_time = 3;
    if (cached_has_bits & 0x00000008u) {
      total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
          this->_internal_pb_rank_time());
    }

    // required int32 pb_rank_value = 2;
    if (cached_has_bits & 0x00000010u) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
          this->_internal_pb_rank_value());
    }

    // required int32 pb_icon_id = 4;
    if (cached_has_bits & 0x00000020u) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
          this->_internal_pb_icon_id());
    }

  }
  if (cached_has_bits & 0x000000c0u) {
    // optional int32 pb_title_id = 6;
    if (cached_has_bits & 0x00000040u) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
          this->_internal_pb_title_id());
    }

    // optional int32 pb_lv = 8;
    if (cached_has_bits & 0x00000080u) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
          this->_internal_pb_lv());
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void ExRankEntry::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ExRankEntry*>(&to_msg);
  auto& from = static_cast<const ExRankEntry&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ExRankEntry)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x000000ffu) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_set_pb_nickname(from._internal_pb_nickname());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_internal_set_pb_param_1(from._internal_pb_param_1());
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_impl_.pb_uid_ = from._impl_.pb_uid_;
    }
    if (cached_has_bits & 0x00000008u) {
      _this->_impl_.pb_rank_time_ = from._impl_.pb_rank_time_;
    }
    if (cached_has_bits & 0x00000010u) {
      _this->_impl_.pb_rank_value_ = from._impl_.pb_rank_value_;
    }
    if (cached_has_bits & 0x00000020u) {
      _this->_impl_.pb_icon_id_ = from._impl_.pb_icon_id_;
    }
    if (cached_has_bits & 0x00000040u) {
      _this->_impl_.pb_title_id_ = from._impl_.pb_title_id_;
    }
    if (cached_has_bits & 0x00000080u) {
      _this->_impl_.pb_lv_ = from._impl_.pb_lv_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ExRankEntry::CopyFrom(const ExRankEntry& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ExRankEntry)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool ExRankEntry::IsInitializedImpl(
    const MessageLite& msg) {
  auto& this_ = static_cast<const ExRankEntry&>(msg);
  if (_Internal::MissingRequiredFields(this_._impl_._has_bits_)) {
    return false;
  }
  return true;
}

void ExRankEntry::InternalSwap(ExRankEntry* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.pb_nickname_, &other->_impl_.pb_nickname_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.pb_param_1_, &other->_impl_.pb_param_1_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ExRankEntry, _impl_.pb_lv_)
      + sizeof(ExRankEntry::_impl_.pb_lv_)
      - PROTOBUF_FIELD_OFFSET(ExRankEntry, _impl_.pb_uid_)>(
          reinterpret_cast<char*>(&_impl_.pb_uid_),
          reinterpret_cast<char*>(&other->_impl_.pb_uid_));
}

::google::protobuf::Metadata ExRankEntry::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_ExNewRankData_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
