// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ExPlayerCmd.proto
// Protobuf C++ Version: 5.27.0

#ifndef GOOGLE_PROTOBUF_INCLUDED_ExPlayerCmd_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_ExPlayerCmd_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5027000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_ExPlayerCmd_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_ExPlayerCmd_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_ExPlayerCmd_2eproto;
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

enum ENUM_PLAYER_CMD : int {
  C2S_DceChangeNickName = 11001,
  C2S_DceGetPlayerBaseInfo = 11003,
  C2S_DceSetRoleOnBoard = 11005,
  C2S_DceInitModuleData = 11007,
  C2S_DceUpdateFightValue = 11009,
  C2S_DceChangeSign = 11011,
  C2S_DceClientLog = 11013,
  C2S_DceSetBackground = 11019,
  C2S_DceSetPersonalSetting = 11021,
  C2S_DceCreateCampaign = 11023,
  C2S_DceSettleCampaign = 11025,
  C2S_DceMarkGuideChain = 11027,
  C2S_DceApplyBattleField = 11029,
  C2S_DceConfirmBFResource = 11031,
  C2S_DceRefreshBFMission = 11033,
  C2S_DceSweepCampaign = 11035,
  C2S_DceUnlockAdvanceTreeNode = 11037,
  C2S_DceCreatePVPCampaign = 11039,
  C2S_DceBattleLog = 11041,
  C2S_DceChallengeTower = 11043,
  C2S_DceGetTowerDailyReward = 11045,
  S2C_DseChangeNickName = 11002,
  S2C_DseGetPlayerBaseInfo = 11004,
  S2C_DseSetRoleOnBoard = 11006,
  S2C_DseInitModuleData = 11008,
  S2C_DseUpdateFightValue = 11010,
  S2C_DseChangeSign = 11012,
  S2C_DseClientLog = 11014,
  S2C_DseSetBackground = 11020,
  S2C_DseSetPersonalSetting = 11022,
  S2C_DseCreateCampaign = 11024,
  S2C_DseSettleCampaign = 11026,
  S2C_DseMarkGuideChain = 11028,
  S2C_DseApplyBattleField = 11030,
  S2C_DseConfirmBFResource = 11032,
  S2C_DseRefreshBFMission = 11034,
  S2C_DseSweepCampaign = 11036,
  S2C_DseUnlockAdvanceTreeNode = 11038,
  S2C_DseCreatePVPCampaign = 11040,
  S2C_DseBattleLog = 11042,
  S2C_DseChallengeTower = 11044,
  S2C_DseGetTowerDailyReward = 11046,
};

bool ENUM_PLAYER_CMD_IsValid(int value);
extern const uint32_t ENUM_PLAYER_CMD_internal_data_[];
constexpr ENUM_PLAYER_CMD ENUM_PLAYER_CMD_MIN = static_cast<ENUM_PLAYER_CMD>(11001);
constexpr ENUM_PLAYER_CMD ENUM_PLAYER_CMD_MAX = static_cast<ENUM_PLAYER_CMD>(11046);
constexpr int ENUM_PLAYER_CMD_ARRAYSIZE = 11046 + 1;
const ::google::protobuf::EnumDescriptor*
ENUM_PLAYER_CMD_descriptor();
template <typename T>
const std::string& ENUM_PLAYER_CMD_Name(T value) {
  static_assert(std::is_same<T, ENUM_PLAYER_CMD>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to ENUM_PLAYER_CMD_Name().");
  return ENUM_PLAYER_CMD_Name(static_cast<ENUM_PLAYER_CMD>(value));
}
template <>
inline const std::string& ENUM_PLAYER_CMD_Name(ENUM_PLAYER_CMD value) {
  return ::google::protobuf::internal::NameOfDenseEnum<ENUM_PLAYER_CMD_descriptor,
                                                 11001, 11046>(
      static_cast<int>(value));
}
inline bool ENUM_PLAYER_CMD_Parse(absl::string_view name, ENUM_PLAYER_CMD* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ENUM_PLAYER_CMD>(
      ENUM_PLAYER_CMD_descriptor(), name, value);
}

// ===================================================================



// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::ENUM_PLAYER_CMD> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::ENUM_PLAYER_CMD>() {
  return ::ENUM_PLAYER_CMD_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_ExPlayerCmd_2eproto_2epb_2eh
