// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ExPlayerCmd.proto
// Protobuf C++ Version: 5.27.0

#include "ExPlayerCmd.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_ExPlayerCmd_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_ExPlayerCmd_2eproto = nullptr;
const ::uint32_t TableStruct_ExPlayerCmd_2eproto::offsets[1] = {};
static constexpr ::_pbi::MigrationSchema* schemas = nullptr;
static constexpr ::_pb::Message* const* file_default_instances = nullptr;
const char descriptor_table_protodef_ExPlayerCmd_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\021ExPlayerCmd.proto*\307\t\n\017ENUM_PLAYER_CMD\022"
    "\032\n\025C2S_DceChangeNickName\020\371U\022\035\n\030C2S_DceGe"
    "tPlayerBaseInfo\020\373U\022\032\n\025C2S_DceSetRoleOnBo"
    "ard\020\375U\022\032\n\025C2S_DceInitModuleData\020\377U\022\034\n\027C2"
    "S_DceUpdateFightValue\020\201V\022\026\n\021C2S_DceChang"
    "eSign\020\203V\022\025\n\020C2S_DceClientLog\020\205V\022\031\n\024C2S_D"
    "ceSetBackground\020\213V\022\036\n\031C2S_DceSetPersonal"
    "Setting\020\215V\022\032\n\025C2S_DceCreateCampaign\020\217V\022\032"
    "\n\025C2S_DceSettleCampaign\020\221V\022\032\n\025C2S_DceMar"
    "kGuideChain\020\223V\022\034\n\027C2S_DceApplyBattleFiel"
    "d\020\225V\022\035\n\030C2S_DceConfirmBFResource\020\227V\022\034\n\027C"
    "2S_DceRefreshBFMission\020\231V\022\031\n\024C2S_DceSwee"
    "pCampaign\020\233V\022!\n\034C2S_DceUnlockAdvanceTree"
    "Node\020\235V\022\035\n\030C2S_DceCreatePVPCampaign\020\237V\022\025"
    "\n\020C2S_DceBattleLog\020\241V\022\032\n\025C2S_DceChalleng"
    "eTower\020\243V\022\037\n\032C2S_DceGetTowerDailyReward\020"
    "\245V\022\032\n\025S2C_DseChangeNickName\020\372U\022\035\n\030S2C_Ds"
    "eGetPlayerBaseInfo\020\374U\022\032\n\025S2C_DseSetRoleO"
    "nBoard\020\376U\022\032\n\025S2C_DseInitModuleData\020\200V\022\034\n"
    "\027S2C_DseUpdateFightValue\020\202V\022\026\n\021S2C_DseCh"
    "angeSign\020\204V\022\025\n\020S2C_DseClientLog\020\206V\022\031\n\024S2"
    "C_DseSetBackground\020\214V\022\036\n\031S2C_DseSetPerso"
    "nalSetting\020\216V\022\032\n\025S2C_DseCreateCampaign\020\220"
    "V\022\032\n\025S2C_DseSettleCampaign\020\222V\022\032\n\025S2C_Dse"
    "MarkGuideChain\020\224V\022\034\n\027S2C_DseApplyBattleF"
    "ield\020\226V\022\035\n\030S2C_DseConfirmBFResource\020\230V\022\034"
    "\n\027S2C_DseRefreshBFMission\020\232V\022\031\n\024S2C_DseS"
    "weepCampaign\020\234V\022!\n\034S2C_DseUnlockAdvanceT"
    "reeNode\020\236V\022\035\n\030S2C_DseCreatePVPCampaign\020\240"
    "V\022\025\n\020S2C_DseBattleLog\020\242V\022\032\n\025S2C_DseChall"
    "engeTower\020\244V\022\037\n\032S2C_DseGetTowerDailyRewa"
    "rd\020\246V"
};
static ::absl::once_flag descriptor_table_ExPlayerCmd_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_ExPlayerCmd_2eproto = {
    false,
    false,
    1245,
    descriptor_table_protodef_ExPlayerCmd_2eproto,
    "ExPlayerCmd.proto",
    &descriptor_table_ExPlayerCmd_2eproto_once,
    nullptr,
    0,
    0,
    schemas,
    file_default_instances,
    TableStruct_ExPlayerCmd_2eproto::offsets,
    file_level_enum_descriptors_ExPlayerCmd_2eproto,
    file_level_service_descriptors_ExPlayerCmd_2eproto,
};
const ::google::protobuf::EnumDescriptor* ENUM_PLAYER_CMD_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_ExPlayerCmd_2eproto);
  return file_level_enum_descriptors_ExPlayerCmd_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t ENUM_PLAYER_CMD_internal_data_[] = {
    928505u, 32u, 4294967280u, };
bool ENUM_PLAYER_CMD_IsValid(int value) {
  return ::_pbi::ValidateEnum(value, ENUM_PLAYER_CMD_internal_data_);
}
// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_ExPlayerCmd_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
