// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ExShopCmd.proto
// Protobuf C++ Version: 5.27.0

#ifndef GOOGLE_PROTOBUF_INCLUDED_ExShopCmd_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_ExShopCmd_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5027000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_ExShopCmd_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_ExShopCmd_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_ExShopCmd_2eproto;
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

enum ENUM_SHOP_CMD : int {
  C2S_DceGetShopSaleList = 10801,
  C2S_DceBuy = 10803,
  C2S_DceRefreshShop = 10805,
  S2C_DseGetShopSaleList = 10802,
  S2C_DseBuy = 10804,
  S2C_DseRefreshShop = 10806,
};

bool ENUM_SHOP_CMD_IsValid(int value);
extern const uint32_t ENUM_SHOP_CMD_internal_data_[];
constexpr ENUM_SHOP_CMD ENUM_SHOP_CMD_MIN = static_cast<ENUM_SHOP_CMD>(10801);
constexpr ENUM_SHOP_CMD ENUM_SHOP_CMD_MAX = static_cast<ENUM_SHOP_CMD>(10806);
constexpr int ENUM_SHOP_CMD_ARRAYSIZE = 10806 + 1;
const ::google::protobuf::EnumDescriptor*
ENUM_SHOP_CMD_descriptor();
template <typename T>
const std::string& ENUM_SHOP_CMD_Name(T value) {
  static_assert(std::is_same<T, ENUM_SHOP_CMD>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to ENUM_SHOP_CMD_Name().");
  return ENUM_SHOP_CMD_Name(static_cast<ENUM_SHOP_CMD>(value));
}
template <>
inline const std::string& ENUM_SHOP_CMD_Name(ENUM_SHOP_CMD value) {
  return ::google::protobuf::internal::NameOfDenseEnum<ENUM_SHOP_CMD_descriptor,
                                                 10801, 10806>(
      static_cast<int>(value));
}
inline bool ENUM_SHOP_CMD_Parse(absl::string_view name, ENUM_SHOP_CMD* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ENUM_SHOP_CMD>(
      ENUM_SHOP_CMD_descriptor(), name, value);
}

// ===================================================================



// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::ENUM_SHOP_CMD> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::ENUM_SHOP_CMD>() {
  return ::ENUM_SHOP_CMD_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_ExShopCmd_2eproto_2epb_2eh
