// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ExStatMsg.proto
// Protobuf C++ Version: 5.27.0

#ifndef GOOGLE_PROTOBUF_INCLUDED_ExStatMsg_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_ExStatMsg_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5027000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_ExStatMsg_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_ExStatMsg_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_ExStatMsg_2eproto;
class ExStatLog;
struct ExStatLogDefaultTypeInternal;
extern ExStatLogDefaultTypeInternal _ExStatLog_default_instance_;
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google


// ===================================================================


// -------------------------------------------------------------------

class ExStatLog final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:ExStatLog) */ {
 public:
  inline ExStatLog() : ExStatLog(nullptr) {}
  ~ExStatLog() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ExStatLog(
      ::google::protobuf::internal::ConstantInitialized);

  inline ExStatLog(const ExStatLog& from) : ExStatLog(nullptr, from) {}
  inline ExStatLog(ExStatLog&& from) noexcept
      : ExStatLog(nullptr, std::move(from)) {}
  inline ExStatLog& operator=(const ExStatLog& from) {
    CopyFrom(from);
    return *this;
  }
  inline ExStatLog& operator=(ExStatLog&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ExStatLog& default_instance() {
    return *internal_default_instance();
  }
  static inline const ExStatLog* internal_default_instance() {
    return reinterpret_cast<const ExStatLog*>(
        &_ExStatLog_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(ExStatLog& a, ExStatLog& b) { a.Swap(&b); }
  inline void Swap(ExStatLog* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ExStatLog* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ExStatLog* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::Message::DefaultConstruct<ExStatLog>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ExStatLog& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const ExStatLog& from) { ExStatLog::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(ExStatLog* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "ExStatLog"; }

 protected:
  explicit ExStatLog(::google::protobuf::Arena* arena);
  ExStatLog(::google::protobuf::Arena* arena, const ExStatLog& from);
  ExStatLog(::google::protobuf::Arena* arena, ExStatLog&& from) noexcept
      : ExStatLog(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const final;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kPbOtherFieldNumber = 15,
    kPbDateFieldNumber = 1,
    kPbSrvIDFieldNumber = 2,
    kPbUidFieldNumber = 3,
    kPbTypeFieldNumber = 4,
    kPbLevelFieldNumber = 5,
    kPbPlatidFieldNumber = 6,
    kPbHaspayFieldNumber = 7,
    kPbRegtimeFieldNumber = 8,
    kPbPaygoldFieldNumber = 9,
    kPbFreegoldFieldNumber = 10,
    kPbChannelFieldNumber = 11,
    kPbRegionFieldNumber = 12,
    kPbViplvFieldNumber = 13,
    kPbDevicemumFieldNumber = 14,
  };
  // repeated string pb_other = 15;
  int pb_other_size() const;
  private:
  int _internal_pb_other_size() const;

  public:
  void clear_pb_other() ;
  const std::string& pb_other(int index) const;
  std::string* mutable_pb_other(int index);
  void set_pb_other(int index, const std::string& value);
  void set_pb_other(int index, std::string&& value);
  void set_pb_other(int index, const char* value);
  void set_pb_other(int index, const char* value, std::size_t size);
  void set_pb_other(int index, absl::string_view value);
  std::string* add_pb_other();
  void add_pb_other(const std::string& value);
  void add_pb_other(std::string&& value);
  void add_pb_other(const char* value);
  void add_pb_other(const char* value, std::size_t size);
  void add_pb_other(absl::string_view value);
  const ::google::protobuf::RepeatedPtrField<std::string>& pb_other() const;
  ::google::protobuf::RepeatedPtrField<std::string>* mutable_pb_other();

  private:
  const ::google::protobuf::RepeatedPtrField<std::string>& _internal_pb_other() const;
  ::google::protobuf::RepeatedPtrField<std::string>* _internal_mutable_pb_other();

  public:
  // optional string pb_date = 1;
  bool has_pb_date() const;
  void clear_pb_date() ;
  const std::string& pb_date() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_pb_date(Arg_&& arg, Args_... args);
  std::string* mutable_pb_date();
  PROTOBUF_NODISCARD std::string* release_pb_date();
  void set_allocated_pb_date(std::string* value);

  private:
  const std::string& _internal_pb_date() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_pb_date(
      const std::string& value);
  std::string* _internal_mutable_pb_date();

  public:
  // optional string pb_srvID = 2;
  bool has_pb_srvid() const;
  void clear_pb_srvid() ;
  const std::string& pb_srvid() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_pb_srvid(Arg_&& arg, Args_... args);
  std::string* mutable_pb_srvid();
  PROTOBUF_NODISCARD std::string* release_pb_srvid();
  void set_allocated_pb_srvid(std::string* value);

  private:
  const std::string& _internal_pb_srvid() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_pb_srvid(
      const std::string& value);
  std::string* _internal_mutable_pb_srvid();

  public:
  // optional string pb_uid = 3;
  bool has_pb_uid() const;
  void clear_pb_uid() ;
  const std::string& pb_uid() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_pb_uid(Arg_&& arg, Args_... args);
  std::string* mutable_pb_uid();
  PROTOBUF_NODISCARD std::string* release_pb_uid();
  void set_allocated_pb_uid(std::string* value);

  private:
  const std::string& _internal_pb_uid() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_pb_uid(
      const std::string& value);
  std::string* _internal_mutable_pb_uid();

  public:
  // optional string pb_type = 4;
  bool has_pb_type() const;
  void clear_pb_type() ;
  const std::string& pb_type() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_pb_type(Arg_&& arg, Args_... args);
  std::string* mutable_pb_type();
  PROTOBUF_NODISCARD std::string* release_pb_type();
  void set_allocated_pb_type(std::string* value);

  private:
  const std::string& _internal_pb_type() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_pb_type(
      const std::string& value);
  std::string* _internal_mutable_pb_type();

  public:
  // optional string pb_level = 5;
  bool has_pb_level() const;
  void clear_pb_level() ;
  const std::string& pb_level() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_pb_level(Arg_&& arg, Args_... args);
  std::string* mutable_pb_level();
  PROTOBUF_NODISCARD std::string* release_pb_level();
  void set_allocated_pb_level(std::string* value);

  private:
  const std::string& _internal_pb_level() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_pb_level(
      const std::string& value);
  std::string* _internal_mutable_pb_level();

  public:
  // optional string pb_platid = 6;
  bool has_pb_platid() const;
  void clear_pb_platid() ;
  const std::string& pb_platid() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_pb_platid(Arg_&& arg, Args_... args);
  std::string* mutable_pb_platid();
  PROTOBUF_NODISCARD std::string* release_pb_platid();
  void set_allocated_pb_platid(std::string* value);

  private:
  const std::string& _internal_pb_platid() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_pb_platid(
      const std::string& value);
  std::string* _internal_mutable_pb_platid();

  public:
  // optional string pb_haspay = 7;
  bool has_pb_haspay() const;
  void clear_pb_haspay() ;
  const std::string& pb_haspay() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_pb_haspay(Arg_&& arg, Args_... args);
  std::string* mutable_pb_haspay();
  PROTOBUF_NODISCARD std::string* release_pb_haspay();
  void set_allocated_pb_haspay(std::string* value);

  private:
  const std::string& _internal_pb_haspay() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_pb_haspay(
      const std::string& value);
  std::string* _internal_mutable_pb_haspay();

  public:
  // optional string pb_regtime = 8;
  bool has_pb_regtime() const;
  void clear_pb_regtime() ;
  const std::string& pb_regtime() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_pb_regtime(Arg_&& arg, Args_... args);
  std::string* mutable_pb_regtime();
  PROTOBUF_NODISCARD std::string* release_pb_regtime();
  void set_allocated_pb_regtime(std::string* value);

  private:
  const std::string& _internal_pb_regtime() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_pb_regtime(
      const std::string& value);
  std::string* _internal_mutable_pb_regtime();

  public:
  // optional string pb_paygold = 9;
  bool has_pb_paygold() const;
  void clear_pb_paygold() ;
  const std::string& pb_paygold() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_pb_paygold(Arg_&& arg, Args_... args);
  std::string* mutable_pb_paygold();
  PROTOBUF_NODISCARD std::string* release_pb_paygold();
  void set_allocated_pb_paygold(std::string* value);

  private:
  const std::string& _internal_pb_paygold() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_pb_paygold(
      const std::string& value);
  std::string* _internal_mutable_pb_paygold();

  public:
  // optional string pb_freegold = 10;
  bool has_pb_freegold() const;
  void clear_pb_freegold() ;
  const std::string& pb_freegold() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_pb_freegold(Arg_&& arg, Args_... args);
  std::string* mutable_pb_freegold();
  PROTOBUF_NODISCARD std::string* release_pb_freegold();
  void set_allocated_pb_freegold(std::string* value);

  private:
  const std::string& _internal_pb_freegold() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_pb_freegold(
      const std::string& value);
  std::string* _internal_mutable_pb_freegold();

  public:
  // optional string pb_channel = 11;
  bool has_pb_channel() const;
  void clear_pb_channel() ;
  const std::string& pb_channel() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_pb_channel(Arg_&& arg, Args_... args);
  std::string* mutable_pb_channel();
  PROTOBUF_NODISCARD std::string* release_pb_channel();
  void set_allocated_pb_channel(std::string* value);

  private:
  const std::string& _internal_pb_channel() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_pb_channel(
      const std::string& value);
  std::string* _internal_mutable_pb_channel();

  public:
  // optional string pb_region = 12;
  bool has_pb_region() const;
  void clear_pb_region() ;
  const std::string& pb_region() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_pb_region(Arg_&& arg, Args_... args);
  std::string* mutable_pb_region();
  PROTOBUF_NODISCARD std::string* release_pb_region();
  void set_allocated_pb_region(std::string* value);

  private:
  const std::string& _internal_pb_region() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_pb_region(
      const std::string& value);
  std::string* _internal_mutable_pb_region();

  public:
  // optional string pb_viplv = 13;
  bool has_pb_viplv() const;
  void clear_pb_viplv() ;
  const std::string& pb_viplv() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_pb_viplv(Arg_&& arg, Args_... args);
  std::string* mutable_pb_viplv();
  PROTOBUF_NODISCARD std::string* release_pb_viplv();
  void set_allocated_pb_viplv(std::string* value);

  private:
  const std::string& _internal_pb_viplv() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_pb_viplv(
      const std::string& value);
  std::string* _internal_mutable_pb_viplv();

  public:
  // optional string pb_devicemum = 14;
  bool has_pb_devicemum() const;
  void clear_pb_devicemum() ;
  const std::string& pb_devicemum() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_pb_devicemum(Arg_&& arg, Args_... args);
  std::string* mutable_pb_devicemum();
  PROTOBUF_NODISCARD std::string* release_pb_devicemum();
  void set_allocated_pb_devicemum(std::string* value);

  private:
  const std::string& _internal_pb_devicemum() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_pb_devicemum(
      const std::string& value);
  std::string* _internal_mutable_pb_devicemum();

  public:
  // @@protoc_insertion_point(class_scope:ExStatLog)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      4, 15, 0,
      158, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_ExStatLog_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const ExStatLog& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField<std::string> pb_other_;
    ::google::protobuf::internal::ArenaStringPtr pb_date_;
    ::google::protobuf::internal::ArenaStringPtr pb_srvid_;
    ::google::protobuf::internal::ArenaStringPtr pb_uid_;
    ::google::protobuf::internal::ArenaStringPtr pb_type_;
    ::google::protobuf::internal::ArenaStringPtr pb_level_;
    ::google::protobuf::internal::ArenaStringPtr pb_platid_;
    ::google::protobuf::internal::ArenaStringPtr pb_haspay_;
    ::google::protobuf::internal::ArenaStringPtr pb_regtime_;
    ::google::protobuf::internal::ArenaStringPtr pb_paygold_;
    ::google::protobuf::internal::ArenaStringPtr pb_freegold_;
    ::google::protobuf::internal::ArenaStringPtr pb_channel_;
    ::google::protobuf::internal::ArenaStringPtr pb_region_;
    ::google::protobuf::internal::ArenaStringPtr pb_viplv_;
    ::google::protobuf::internal::ArenaStringPtr pb_devicemum_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ExStatMsg_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// ExStatLog

// optional string pb_date = 1;
inline bool ExStatLog::has_pb_date() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void ExStatLog::clear_pb_date() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pb_date_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& ExStatLog::pb_date() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:ExStatLog.pb_date)
  return _internal_pb_date();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void ExStatLog::set_pb_date(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.pb_date_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:ExStatLog.pb_date)
}
inline std::string* ExStatLog::mutable_pb_date() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_pb_date();
  // @@protoc_insertion_point(field_mutable:ExStatLog.pb_date)
  return _s;
}
inline const std::string& ExStatLog::_internal_pb_date() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.pb_date_.Get();
}
inline void ExStatLog::_internal_set_pb_date(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.pb_date_.Set(value, GetArena());
}
inline std::string* ExStatLog::_internal_mutable_pb_date() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.pb_date_.Mutable( GetArena());
}
inline std::string* ExStatLog::release_pb_date() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:ExStatLog.pb_date)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.pb_date_.Release();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.pb_date_.Set("", GetArena());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return released;
}
inline void ExStatLog::set_allocated_pb_date(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.pb_date_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.pb_date_.IsDefault()) {
          _impl_.pb_date_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ExStatLog.pb_date)
}

// optional string pb_srvID = 2;
inline bool ExStatLog::has_pb_srvid() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline void ExStatLog::clear_pb_srvid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pb_srvid_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const std::string& ExStatLog::pb_srvid() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:ExStatLog.pb_srvID)
  return _internal_pb_srvid();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void ExStatLog::set_pb_srvid(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.pb_srvid_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:ExStatLog.pb_srvID)
}
inline std::string* ExStatLog::mutable_pb_srvid() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_pb_srvid();
  // @@protoc_insertion_point(field_mutable:ExStatLog.pb_srvID)
  return _s;
}
inline const std::string& ExStatLog::_internal_pb_srvid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.pb_srvid_.Get();
}
inline void ExStatLog::_internal_set_pb_srvid(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.pb_srvid_.Set(value, GetArena());
}
inline std::string* ExStatLog::_internal_mutable_pb_srvid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  return _impl_.pb_srvid_.Mutable( GetArena());
}
inline std::string* ExStatLog::release_pb_srvid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:ExStatLog.pb_srvID)
  if ((_impl_._has_bits_[0] & 0x00000002u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000002u;
  auto* released = _impl_.pb_srvid_.Release();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.pb_srvid_.Set("", GetArena());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return released;
}
inline void ExStatLog::set_allocated_pb_srvid(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  _impl_.pb_srvid_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.pb_srvid_.IsDefault()) {
          _impl_.pb_srvid_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ExStatLog.pb_srvID)
}

// optional string pb_uid = 3;
inline bool ExStatLog::has_pb_uid() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline void ExStatLog::clear_pb_uid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pb_uid_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline const std::string& ExStatLog::pb_uid() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:ExStatLog.pb_uid)
  return _internal_pb_uid();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void ExStatLog::set_pb_uid(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.pb_uid_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:ExStatLog.pb_uid)
}
inline std::string* ExStatLog::mutable_pb_uid() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_pb_uid();
  // @@protoc_insertion_point(field_mutable:ExStatLog.pb_uid)
  return _s;
}
inline const std::string& ExStatLog::_internal_pb_uid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.pb_uid_.Get();
}
inline void ExStatLog::_internal_set_pb_uid(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.pb_uid_.Set(value, GetArena());
}
inline std::string* ExStatLog::_internal_mutable_pb_uid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000004u;
  return _impl_.pb_uid_.Mutable( GetArena());
}
inline std::string* ExStatLog::release_pb_uid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:ExStatLog.pb_uid)
  if ((_impl_._has_bits_[0] & 0x00000004u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000004u;
  auto* released = _impl_.pb_uid_.Release();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.pb_uid_.Set("", GetArena());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return released;
}
inline void ExStatLog::set_allocated_pb_uid(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000004u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000004u;
  }
  _impl_.pb_uid_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.pb_uid_.IsDefault()) {
          _impl_.pb_uid_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ExStatLog.pb_uid)
}

// optional string pb_type = 4;
inline bool ExStatLog::has_pb_type() const {
  bool value = (_impl_._has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline void ExStatLog::clear_pb_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pb_type_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000008u;
}
inline const std::string& ExStatLog::pb_type() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:ExStatLog.pb_type)
  return _internal_pb_type();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void ExStatLog::set_pb_type(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000008u;
  _impl_.pb_type_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:ExStatLog.pb_type)
}
inline std::string* ExStatLog::mutable_pb_type() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_pb_type();
  // @@protoc_insertion_point(field_mutable:ExStatLog.pb_type)
  return _s;
}
inline const std::string& ExStatLog::_internal_pb_type() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.pb_type_.Get();
}
inline void ExStatLog::_internal_set_pb_type(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000008u;
  _impl_.pb_type_.Set(value, GetArena());
}
inline std::string* ExStatLog::_internal_mutable_pb_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000008u;
  return _impl_.pb_type_.Mutable( GetArena());
}
inline std::string* ExStatLog::release_pb_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:ExStatLog.pb_type)
  if ((_impl_._has_bits_[0] & 0x00000008u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000008u;
  auto* released = _impl_.pb_type_.Release();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.pb_type_.Set("", GetArena());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return released;
}
inline void ExStatLog::set_allocated_pb_type(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000008u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000008u;
  }
  _impl_.pb_type_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.pb_type_.IsDefault()) {
          _impl_.pb_type_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ExStatLog.pb_type)
}

// optional string pb_level = 5;
inline bool ExStatLog::has_pb_level() const {
  bool value = (_impl_._has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline void ExStatLog::clear_pb_level() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pb_level_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000010u;
}
inline const std::string& ExStatLog::pb_level() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:ExStatLog.pb_level)
  return _internal_pb_level();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void ExStatLog::set_pb_level(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000010u;
  _impl_.pb_level_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:ExStatLog.pb_level)
}
inline std::string* ExStatLog::mutable_pb_level() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_pb_level();
  // @@protoc_insertion_point(field_mutable:ExStatLog.pb_level)
  return _s;
}
inline const std::string& ExStatLog::_internal_pb_level() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.pb_level_.Get();
}
inline void ExStatLog::_internal_set_pb_level(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000010u;
  _impl_.pb_level_.Set(value, GetArena());
}
inline std::string* ExStatLog::_internal_mutable_pb_level() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000010u;
  return _impl_.pb_level_.Mutable( GetArena());
}
inline std::string* ExStatLog::release_pb_level() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:ExStatLog.pb_level)
  if ((_impl_._has_bits_[0] & 0x00000010u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000010u;
  auto* released = _impl_.pb_level_.Release();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.pb_level_.Set("", GetArena());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return released;
}
inline void ExStatLog::set_allocated_pb_level(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000010u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000010u;
  }
  _impl_.pb_level_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.pb_level_.IsDefault()) {
          _impl_.pb_level_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ExStatLog.pb_level)
}

// optional string pb_platid = 6;
inline bool ExStatLog::has_pb_platid() const {
  bool value = (_impl_._has_bits_[0] & 0x00000020u) != 0;
  return value;
}
inline void ExStatLog::clear_pb_platid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pb_platid_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000020u;
}
inline const std::string& ExStatLog::pb_platid() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:ExStatLog.pb_platid)
  return _internal_pb_platid();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void ExStatLog::set_pb_platid(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000020u;
  _impl_.pb_platid_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:ExStatLog.pb_platid)
}
inline std::string* ExStatLog::mutable_pb_platid() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_pb_platid();
  // @@protoc_insertion_point(field_mutable:ExStatLog.pb_platid)
  return _s;
}
inline const std::string& ExStatLog::_internal_pb_platid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.pb_platid_.Get();
}
inline void ExStatLog::_internal_set_pb_platid(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000020u;
  _impl_.pb_platid_.Set(value, GetArena());
}
inline std::string* ExStatLog::_internal_mutable_pb_platid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000020u;
  return _impl_.pb_platid_.Mutable( GetArena());
}
inline std::string* ExStatLog::release_pb_platid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:ExStatLog.pb_platid)
  if ((_impl_._has_bits_[0] & 0x00000020u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000020u;
  auto* released = _impl_.pb_platid_.Release();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.pb_platid_.Set("", GetArena());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return released;
}
inline void ExStatLog::set_allocated_pb_platid(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000020u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000020u;
  }
  _impl_.pb_platid_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.pb_platid_.IsDefault()) {
          _impl_.pb_platid_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ExStatLog.pb_platid)
}

// optional string pb_haspay = 7;
inline bool ExStatLog::has_pb_haspay() const {
  bool value = (_impl_._has_bits_[0] & 0x00000040u) != 0;
  return value;
}
inline void ExStatLog::clear_pb_haspay() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pb_haspay_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000040u;
}
inline const std::string& ExStatLog::pb_haspay() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:ExStatLog.pb_haspay)
  return _internal_pb_haspay();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void ExStatLog::set_pb_haspay(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000040u;
  _impl_.pb_haspay_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:ExStatLog.pb_haspay)
}
inline std::string* ExStatLog::mutable_pb_haspay() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_pb_haspay();
  // @@protoc_insertion_point(field_mutable:ExStatLog.pb_haspay)
  return _s;
}
inline const std::string& ExStatLog::_internal_pb_haspay() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.pb_haspay_.Get();
}
inline void ExStatLog::_internal_set_pb_haspay(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000040u;
  _impl_.pb_haspay_.Set(value, GetArena());
}
inline std::string* ExStatLog::_internal_mutable_pb_haspay() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000040u;
  return _impl_.pb_haspay_.Mutable( GetArena());
}
inline std::string* ExStatLog::release_pb_haspay() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:ExStatLog.pb_haspay)
  if ((_impl_._has_bits_[0] & 0x00000040u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000040u;
  auto* released = _impl_.pb_haspay_.Release();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.pb_haspay_.Set("", GetArena());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return released;
}
inline void ExStatLog::set_allocated_pb_haspay(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000040u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000040u;
  }
  _impl_.pb_haspay_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.pb_haspay_.IsDefault()) {
          _impl_.pb_haspay_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ExStatLog.pb_haspay)
}

// optional string pb_regtime = 8;
inline bool ExStatLog::has_pb_regtime() const {
  bool value = (_impl_._has_bits_[0] & 0x00000080u) != 0;
  return value;
}
inline void ExStatLog::clear_pb_regtime() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pb_regtime_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000080u;
}
inline const std::string& ExStatLog::pb_regtime() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:ExStatLog.pb_regtime)
  return _internal_pb_regtime();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void ExStatLog::set_pb_regtime(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000080u;
  _impl_.pb_regtime_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:ExStatLog.pb_regtime)
}
inline std::string* ExStatLog::mutable_pb_regtime() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_pb_regtime();
  // @@protoc_insertion_point(field_mutable:ExStatLog.pb_regtime)
  return _s;
}
inline const std::string& ExStatLog::_internal_pb_regtime() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.pb_regtime_.Get();
}
inline void ExStatLog::_internal_set_pb_regtime(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000080u;
  _impl_.pb_regtime_.Set(value, GetArena());
}
inline std::string* ExStatLog::_internal_mutable_pb_regtime() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000080u;
  return _impl_.pb_regtime_.Mutable( GetArena());
}
inline std::string* ExStatLog::release_pb_regtime() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:ExStatLog.pb_regtime)
  if ((_impl_._has_bits_[0] & 0x00000080u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000080u;
  auto* released = _impl_.pb_regtime_.Release();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.pb_regtime_.Set("", GetArena());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return released;
}
inline void ExStatLog::set_allocated_pb_regtime(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000080u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000080u;
  }
  _impl_.pb_regtime_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.pb_regtime_.IsDefault()) {
          _impl_.pb_regtime_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ExStatLog.pb_regtime)
}

// optional string pb_paygold = 9;
inline bool ExStatLog::has_pb_paygold() const {
  bool value = (_impl_._has_bits_[0] & 0x00000100u) != 0;
  return value;
}
inline void ExStatLog::clear_pb_paygold() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pb_paygold_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000100u;
}
inline const std::string& ExStatLog::pb_paygold() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:ExStatLog.pb_paygold)
  return _internal_pb_paygold();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void ExStatLog::set_pb_paygold(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000100u;
  _impl_.pb_paygold_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:ExStatLog.pb_paygold)
}
inline std::string* ExStatLog::mutable_pb_paygold() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_pb_paygold();
  // @@protoc_insertion_point(field_mutable:ExStatLog.pb_paygold)
  return _s;
}
inline const std::string& ExStatLog::_internal_pb_paygold() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.pb_paygold_.Get();
}
inline void ExStatLog::_internal_set_pb_paygold(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000100u;
  _impl_.pb_paygold_.Set(value, GetArena());
}
inline std::string* ExStatLog::_internal_mutable_pb_paygold() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000100u;
  return _impl_.pb_paygold_.Mutable( GetArena());
}
inline std::string* ExStatLog::release_pb_paygold() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:ExStatLog.pb_paygold)
  if ((_impl_._has_bits_[0] & 0x00000100u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000100u;
  auto* released = _impl_.pb_paygold_.Release();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.pb_paygold_.Set("", GetArena());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return released;
}
inline void ExStatLog::set_allocated_pb_paygold(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000100u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000100u;
  }
  _impl_.pb_paygold_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.pb_paygold_.IsDefault()) {
          _impl_.pb_paygold_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ExStatLog.pb_paygold)
}

// optional string pb_freegold = 10;
inline bool ExStatLog::has_pb_freegold() const {
  bool value = (_impl_._has_bits_[0] & 0x00000200u) != 0;
  return value;
}
inline void ExStatLog::clear_pb_freegold() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pb_freegold_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000200u;
}
inline const std::string& ExStatLog::pb_freegold() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:ExStatLog.pb_freegold)
  return _internal_pb_freegold();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void ExStatLog::set_pb_freegold(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000200u;
  _impl_.pb_freegold_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:ExStatLog.pb_freegold)
}
inline std::string* ExStatLog::mutable_pb_freegold() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_pb_freegold();
  // @@protoc_insertion_point(field_mutable:ExStatLog.pb_freegold)
  return _s;
}
inline const std::string& ExStatLog::_internal_pb_freegold() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.pb_freegold_.Get();
}
inline void ExStatLog::_internal_set_pb_freegold(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000200u;
  _impl_.pb_freegold_.Set(value, GetArena());
}
inline std::string* ExStatLog::_internal_mutable_pb_freegold() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000200u;
  return _impl_.pb_freegold_.Mutable( GetArena());
}
inline std::string* ExStatLog::release_pb_freegold() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:ExStatLog.pb_freegold)
  if ((_impl_._has_bits_[0] & 0x00000200u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000200u;
  auto* released = _impl_.pb_freegold_.Release();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.pb_freegold_.Set("", GetArena());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return released;
}
inline void ExStatLog::set_allocated_pb_freegold(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000200u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000200u;
  }
  _impl_.pb_freegold_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.pb_freegold_.IsDefault()) {
          _impl_.pb_freegold_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ExStatLog.pb_freegold)
}

// optional string pb_channel = 11;
inline bool ExStatLog::has_pb_channel() const {
  bool value = (_impl_._has_bits_[0] & 0x00000400u) != 0;
  return value;
}
inline void ExStatLog::clear_pb_channel() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pb_channel_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000400u;
}
inline const std::string& ExStatLog::pb_channel() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:ExStatLog.pb_channel)
  return _internal_pb_channel();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void ExStatLog::set_pb_channel(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000400u;
  _impl_.pb_channel_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:ExStatLog.pb_channel)
}
inline std::string* ExStatLog::mutable_pb_channel() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_pb_channel();
  // @@protoc_insertion_point(field_mutable:ExStatLog.pb_channel)
  return _s;
}
inline const std::string& ExStatLog::_internal_pb_channel() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.pb_channel_.Get();
}
inline void ExStatLog::_internal_set_pb_channel(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000400u;
  _impl_.pb_channel_.Set(value, GetArena());
}
inline std::string* ExStatLog::_internal_mutable_pb_channel() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000400u;
  return _impl_.pb_channel_.Mutable( GetArena());
}
inline std::string* ExStatLog::release_pb_channel() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:ExStatLog.pb_channel)
  if ((_impl_._has_bits_[0] & 0x00000400u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000400u;
  auto* released = _impl_.pb_channel_.Release();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.pb_channel_.Set("", GetArena());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return released;
}
inline void ExStatLog::set_allocated_pb_channel(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000400u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000400u;
  }
  _impl_.pb_channel_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.pb_channel_.IsDefault()) {
          _impl_.pb_channel_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ExStatLog.pb_channel)
}

// optional string pb_region = 12;
inline bool ExStatLog::has_pb_region() const {
  bool value = (_impl_._has_bits_[0] & 0x00000800u) != 0;
  return value;
}
inline void ExStatLog::clear_pb_region() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pb_region_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000800u;
}
inline const std::string& ExStatLog::pb_region() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:ExStatLog.pb_region)
  return _internal_pb_region();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void ExStatLog::set_pb_region(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000800u;
  _impl_.pb_region_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:ExStatLog.pb_region)
}
inline std::string* ExStatLog::mutable_pb_region() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_pb_region();
  // @@protoc_insertion_point(field_mutable:ExStatLog.pb_region)
  return _s;
}
inline const std::string& ExStatLog::_internal_pb_region() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.pb_region_.Get();
}
inline void ExStatLog::_internal_set_pb_region(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000800u;
  _impl_.pb_region_.Set(value, GetArena());
}
inline std::string* ExStatLog::_internal_mutable_pb_region() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000800u;
  return _impl_.pb_region_.Mutable( GetArena());
}
inline std::string* ExStatLog::release_pb_region() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:ExStatLog.pb_region)
  if ((_impl_._has_bits_[0] & 0x00000800u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000800u;
  auto* released = _impl_.pb_region_.Release();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.pb_region_.Set("", GetArena());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return released;
}
inline void ExStatLog::set_allocated_pb_region(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000800u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000800u;
  }
  _impl_.pb_region_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.pb_region_.IsDefault()) {
          _impl_.pb_region_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ExStatLog.pb_region)
}

// optional string pb_viplv = 13;
inline bool ExStatLog::has_pb_viplv() const {
  bool value = (_impl_._has_bits_[0] & 0x00001000u) != 0;
  return value;
}
inline void ExStatLog::clear_pb_viplv() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pb_viplv_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00001000u;
}
inline const std::string& ExStatLog::pb_viplv() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:ExStatLog.pb_viplv)
  return _internal_pb_viplv();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void ExStatLog::set_pb_viplv(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00001000u;
  _impl_.pb_viplv_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:ExStatLog.pb_viplv)
}
inline std::string* ExStatLog::mutable_pb_viplv() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_pb_viplv();
  // @@protoc_insertion_point(field_mutable:ExStatLog.pb_viplv)
  return _s;
}
inline const std::string& ExStatLog::_internal_pb_viplv() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.pb_viplv_.Get();
}
inline void ExStatLog::_internal_set_pb_viplv(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00001000u;
  _impl_.pb_viplv_.Set(value, GetArena());
}
inline std::string* ExStatLog::_internal_mutable_pb_viplv() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00001000u;
  return _impl_.pb_viplv_.Mutable( GetArena());
}
inline std::string* ExStatLog::release_pb_viplv() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:ExStatLog.pb_viplv)
  if ((_impl_._has_bits_[0] & 0x00001000u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00001000u;
  auto* released = _impl_.pb_viplv_.Release();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.pb_viplv_.Set("", GetArena());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return released;
}
inline void ExStatLog::set_allocated_pb_viplv(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00001000u;
  } else {
    _impl_._has_bits_[0] &= ~0x00001000u;
  }
  _impl_.pb_viplv_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.pb_viplv_.IsDefault()) {
          _impl_.pb_viplv_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ExStatLog.pb_viplv)
}

// optional string pb_devicemum = 14;
inline bool ExStatLog::has_pb_devicemum() const {
  bool value = (_impl_._has_bits_[0] & 0x00002000u) != 0;
  return value;
}
inline void ExStatLog::clear_pb_devicemum() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pb_devicemum_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00002000u;
}
inline const std::string& ExStatLog::pb_devicemum() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:ExStatLog.pb_devicemum)
  return _internal_pb_devicemum();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void ExStatLog::set_pb_devicemum(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00002000u;
  _impl_.pb_devicemum_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:ExStatLog.pb_devicemum)
}
inline std::string* ExStatLog::mutable_pb_devicemum() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_pb_devicemum();
  // @@protoc_insertion_point(field_mutable:ExStatLog.pb_devicemum)
  return _s;
}
inline const std::string& ExStatLog::_internal_pb_devicemum() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.pb_devicemum_.Get();
}
inline void ExStatLog::_internal_set_pb_devicemum(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00002000u;
  _impl_.pb_devicemum_.Set(value, GetArena());
}
inline std::string* ExStatLog::_internal_mutable_pb_devicemum() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00002000u;
  return _impl_.pb_devicemum_.Mutable( GetArena());
}
inline std::string* ExStatLog::release_pb_devicemum() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:ExStatLog.pb_devicemum)
  if ((_impl_._has_bits_[0] & 0x00002000u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00002000u;
  auto* released = _impl_.pb_devicemum_.Release();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.pb_devicemum_.Set("", GetArena());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return released;
}
inline void ExStatLog::set_allocated_pb_devicemum(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00002000u;
  } else {
    _impl_._has_bits_[0] &= ~0x00002000u;
  }
  _impl_.pb_devicemum_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.pb_devicemum_.IsDefault()) {
          _impl_.pb_devicemum_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ExStatLog.pb_devicemum)
}

// repeated string pb_other = 15;
inline int ExStatLog::_internal_pb_other_size() const {
  return _internal_pb_other().size();
}
inline int ExStatLog::pb_other_size() const {
  return _internal_pb_other_size();
}
inline void ExStatLog::clear_pb_other() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pb_other_.Clear();
}
inline std::string* ExStatLog::add_pb_other()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  std::string* _s = _internal_mutable_pb_other()->Add();
  // @@protoc_insertion_point(field_add_mutable:ExStatLog.pb_other)
  return _s;
}
inline const std::string& ExStatLog::pb_other(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:ExStatLog.pb_other)
  return _internal_pb_other().Get(index);
}
inline std::string* ExStatLog::mutable_pb_other(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:ExStatLog.pb_other)
  return _internal_mutable_pb_other()->Mutable(index);
}
inline void ExStatLog::set_pb_other(int index, const std::string& value) {
  _internal_mutable_pb_other()->Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set:ExStatLog.pb_other)
}
inline void ExStatLog::set_pb_other(int index, std::string&& value) {
  _internal_mutable_pb_other()->Mutable(index)->assign(std::move(value));
  // @@protoc_insertion_point(field_set:ExStatLog.pb_other)
}
inline void ExStatLog::set_pb_other(int index, const char* value) {
  ABSL_DCHECK(value != nullptr);
  _internal_mutable_pb_other()->Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:ExStatLog.pb_other)
}
inline void ExStatLog::set_pb_other(int index, const char* value,
                              std::size_t size) {
  _internal_mutable_pb_other()->Mutable(index)->assign(
      reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:ExStatLog.pb_other)
}
inline void ExStatLog::set_pb_other(int index, absl::string_view value) {
  _internal_mutable_pb_other()->Mutable(index)->assign(
      value.data(), value.size());
  // @@protoc_insertion_point(field_set_string_piece:ExStatLog.pb_other)
}
inline void ExStatLog::add_pb_other(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_pb_other()->Add()->assign(value);
  // @@protoc_insertion_point(field_add:ExStatLog.pb_other)
}
inline void ExStatLog::add_pb_other(std::string&& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_pb_other()->Add(std::move(value));
  // @@protoc_insertion_point(field_add:ExStatLog.pb_other)
}
inline void ExStatLog::add_pb_other(const char* value) {
  ABSL_DCHECK(value != nullptr);
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_pb_other()->Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:ExStatLog.pb_other)
}
inline void ExStatLog::add_pb_other(const char* value, std::size_t size) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_pb_other()->Add()->assign(
      reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:ExStatLog.pb_other)
}
inline void ExStatLog::add_pb_other(absl::string_view value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_pb_other()->Add()->assign(value.data(),
                                                     value.size());
  // @@protoc_insertion_point(field_add_string_piece:ExStatLog.pb_other)
}
inline const ::google::protobuf::RepeatedPtrField<std::string>&
ExStatLog::pb_other() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:ExStatLog.pb_other)
  return _internal_pb_other();
}
inline ::google::protobuf::RepeatedPtrField<std::string>*
ExStatLog::mutable_pb_other() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:ExStatLog.pb_other)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_pb_other();
}
inline const ::google::protobuf::RepeatedPtrField<std::string>&
ExStatLog::_internal_pb_other() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.pb_other_;
}
inline ::google::protobuf::RepeatedPtrField<std::string>*
ExStatLog::_internal_mutable_pb_other() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.pb_other_;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_ExStatMsg_2eproto_2epb_2eh
