// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ExStatMsg.proto
// Protobuf C++ Version: 5.27.0

#include "ExStatMsg.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;

inline constexpr ExStatLog::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        pb_other_{},
        pb_date_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        pb_srvid_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        pb_uid_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        pb_type_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        pb_level_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        pb_platid_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        pb_haspay_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        pb_regtime_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        pb_paygold_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        pb_freegold_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        pb_channel_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        pb_region_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        pb_viplv_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        pb_devicemum_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()) {}

template <typename>
PROTOBUF_CONSTEXPR ExStatLog::ExStatLog(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct ExStatLogDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ExStatLogDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ExStatLogDefaultTypeInternal() {}
  union {
    ExStatLog _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ExStatLogDefaultTypeInternal _ExStatLog_default_instance_;
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_ExStatMsg_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_ExStatMsg_2eproto = nullptr;
const ::uint32_t
    TableStruct_ExStatMsg_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        PROTOBUF_FIELD_OFFSET(::ExStatLog, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::ExStatLog, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::ExStatLog, _impl_.pb_date_),
        PROTOBUF_FIELD_OFFSET(::ExStatLog, _impl_.pb_srvid_),
        PROTOBUF_FIELD_OFFSET(::ExStatLog, _impl_.pb_uid_),
        PROTOBUF_FIELD_OFFSET(::ExStatLog, _impl_.pb_type_),
        PROTOBUF_FIELD_OFFSET(::ExStatLog, _impl_.pb_level_),
        PROTOBUF_FIELD_OFFSET(::ExStatLog, _impl_.pb_platid_),
        PROTOBUF_FIELD_OFFSET(::ExStatLog, _impl_.pb_haspay_),
        PROTOBUF_FIELD_OFFSET(::ExStatLog, _impl_.pb_regtime_),
        PROTOBUF_FIELD_OFFSET(::ExStatLog, _impl_.pb_paygold_),
        PROTOBUF_FIELD_OFFSET(::ExStatLog, _impl_.pb_freegold_),
        PROTOBUF_FIELD_OFFSET(::ExStatLog, _impl_.pb_channel_),
        PROTOBUF_FIELD_OFFSET(::ExStatLog, _impl_.pb_region_),
        PROTOBUF_FIELD_OFFSET(::ExStatLog, _impl_.pb_viplv_),
        PROTOBUF_FIELD_OFFSET(::ExStatLog, _impl_.pb_devicemum_),
        PROTOBUF_FIELD_OFFSET(::ExStatLog, _impl_.pb_other_),
        0,
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
        10,
        11,
        12,
        13,
        ~0u,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, 23, -1, sizeof(::ExStatLog)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::_ExStatLog_default_instance_._instance,
};
const char descriptor_table_protodef_ExStatMsg_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\017ExStatMsg.proto\"\245\002\n\tExStatLog\022\017\n\007pb_da"
    "te\030\001 \001(\t\022\020\n\010pb_srvID\030\002 \001(\t\022\016\n\006pb_uid\030\003 \001"
    "(\t\022\017\n\007pb_type\030\004 \001(\t\022\020\n\010pb_level\030\005 \001(\t\022\021\n"
    "\tpb_platid\030\006 \001(\t\022\021\n\tpb_haspay\030\007 \001(\t\022\022\n\np"
    "b_regtime\030\010 \001(\t\022\022\n\npb_paygold\030\t \001(\t\022\023\n\013p"
    "b_freegold\030\n \001(\t\022\022\n\npb_channel\030\013 \001(\t\022\021\n\t"
    "pb_region\030\014 \001(\t\022\020\n\010pb_viplv\030\r \001(\t\022\024\n\014pb_"
    "devicemum\030\016 \001(\t\022\020\n\010pb_other\030\017 \003(\t"
};
static ::absl::once_flag descriptor_table_ExStatMsg_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_ExStatMsg_2eproto = {
    false,
    false,
    313,
    descriptor_table_protodef_ExStatMsg_2eproto,
    "ExStatMsg.proto",
    &descriptor_table_ExStatMsg_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_ExStatMsg_2eproto::offsets,
    file_level_enum_descriptors_ExStatMsg_2eproto,
    file_level_service_descriptors_ExStatMsg_2eproto,
};
// ===================================================================

class ExStatLog::_Internal {
 public:
  using HasBits =
      decltype(std::declval<ExStatLog>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(ExStatLog, _impl_._has_bits_);
};

ExStatLog::ExStatLog(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:ExStatLog)
}
inline PROTOBUF_NDEBUG_INLINE ExStatLog::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::ExStatLog& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        pb_other_{visibility, arena, from.pb_other_},
        pb_date_(arena, from.pb_date_),
        pb_srvid_(arena, from.pb_srvid_),
        pb_uid_(arena, from.pb_uid_),
        pb_type_(arena, from.pb_type_),
        pb_level_(arena, from.pb_level_),
        pb_platid_(arena, from.pb_platid_),
        pb_haspay_(arena, from.pb_haspay_),
        pb_regtime_(arena, from.pb_regtime_),
        pb_paygold_(arena, from.pb_paygold_),
        pb_freegold_(arena, from.pb_freegold_),
        pb_channel_(arena, from.pb_channel_),
        pb_region_(arena, from.pb_region_),
        pb_viplv_(arena, from.pb_viplv_),
        pb_devicemum_(arena, from.pb_devicemum_) {}

ExStatLog::ExStatLog(
    ::google::protobuf::Arena* arena,
    const ExStatLog& from)
    : ::google::protobuf::Message(arena) {
  ExStatLog* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:ExStatLog)
}
inline PROTOBUF_NDEBUG_INLINE ExStatLog::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        pb_other_{visibility, arena},
        pb_date_(arena),
        pb_srvid_(arena),
        pb_uid_(arena),
        pb_type_(arena),
        pb_level_(arena),
        pb_platid_(arena),
        pb_haspay_(arena),
        pb_regtime_(arena),
        pb_paygold_(arena),
        pb_freegold_(arena),
        pb_channel_(arena),
        pb_region_(arena),
        pb_viplv_(arena),
        pb_devicemum_(arena) {}

inline void ExStatLog::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
ExStatLog::~ExStatLog() {
  // @@protoc_insertion_point(destructor:ExStatLog)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void ExStatLog::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.pb_date_.Destroy();
  _impl_.pb_srvid_.Destroy();
  _impl_.pb_uid_.Destroy();
  _impl_.pb_type_.Destroy();
  _impl_.pb_level_.Destroy();
  _impl_.pb_platid_.Destroy();
  _impl_.pb_haspay_.Destroy();
  _impl_.pb_regtime_.Destroy();
  _impl_.pb_paygold_.Destroy();
  _impl_.pb_freegold_.Destroy();
  _impl_.pb_channel_.Destroy();
  _impl_.pb_region_.Destroy();
  _impl_.pb_viplv_.Destroy();
  _impl_.pb_devicemum_.Destroy();
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
ExStatLog::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(ExStatLog, _impl_._cached_size_),
              false,
          },
          &ExStatLog::MergeImpl,
          &ExStatLog::kDescriptorMethods,
          &descriptor_table_ExStatMsg_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<4, 15, 0, 158, 2> ExStatLog::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(ExStatLog, _impl_._has_bits_),
    0, // no _extensions_
    15, 120,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294934528,  // skipmap
    offsetof(decltype(_table_), field_entries),
    15,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_ExStatLog_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::ExStatLog>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // optional string pb_date = 1;
    {::_pbi::TcParser::FastSS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(ExStatLog, _impl_.pb_date_)}},
    // optional string pb_srvID = 2;
    {::_pbi::TcParser::FastSS1,
     {18, 1, 0, PROTOBUF_FIELD_OFFSET(ExStatLog, _impl_.pb_srvid_)}},
    // optional string pb_uid = 3;
    {::_pbi::TcParser::FastSS1,
     {26, 2, 0, PROTOBUF_FIELD_OFFSET(ExStatLog, _impl_.pb_uid_)}},
    // optional string pb_type = 4;
    {::_pbi::TcParser::FastSS1,
     {34, 3, 0, PROTOBUF_FIELD_OFFSET(ExStatLog, _impl_.pb_type_)}},
    // optional string pb_level = 5;
    {::_pbi::TcParser::FastSS1,
     {42, 4, 0, PROTOBUF_FIELD_OFFSET(ExStatLog, _impl_.pb_level_)}},
    // optional string pb_platid = 6;
    {::_pbi::TcParser::FastSS1,
     {50, 5, 0, PROTOBUF_FIELD_OFFSET(ExStatLog, _impl_.pb_platid_)}},
    // optional string pb_haspay = 7;
    {::_pbi::TcParser::FastSS1,
     {58, 6, 0, PROTOBUF_FIELD_OFFSET(ExStatLog, _impl_.pb_haspay_)}},
    // optional string pb_regtime = 8;
    {::_pbi::TcParser::FastSS1,
     {66, 7, 0, PROTOBUF_FIELD_OFFSET(ExStatLog, _impl_.pb_regtime_)}},
    // optional string pb_paygold = 9;
    {::_pbi::TcParser::FastSS1,
     {74, 8, 0, PROTOBUF_FIELD_OFFSET(ExStatLog, _impl_.pb_paygold_)}},
    // optional string pb_freegold = 10;
    {::_pbi::TcParser::FastSS1,
     {82, 9, 0, PROTOBUF_FIELD_OFFSET(ExStatLog, _impl_.pb_freegold_)}},
    // optional string pb_channel = 11;
    {::_pbi::TcParser::FastSS1,
     {90, 10, 0, PROTOBUF_FIELD_OFFSET(ExStatLog, _impl_.pb_channel_)}},
    // optional string pb_region = 12;
    {::_pbi::TcParser::FastSS1,
     {98, 11, 0, PROTOBUF_FIELD_OFFSET(ExStatLog, _impl_.pb_region_)}},
    // optional string pb_viplv = 13;
    {::_pbi::TcParser::FastSS1,
     {106, 12, 0, PROTOBUF_FIELD_OFFSET(ExStatLog, _impl_.pb_viplv_)}},
    // optional string pb_devicemum = 14;
    {::_pbi::TcParser::FastSS1,
     {114, 13, 0, PROTOBUF_FIELD_OFFSET(ExStatLog, _impl_.pb_devicemum_)}},
    // repeated string pb_other = 15;
    {::_pbi::TcParser::FastSR1,
     {122, 63, 0, PROTOBUF_FIELD_OFFSET(ExStatLog, _impl_.pb_other_)}},
  }}, {{
    65535, 65535
  }}, {{
    // optional string pb_date = 1;
    {PROTOBUF_FIELD_OFFSET(ExStatLog, _impl_.pb_date_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kRawString | ::_fl::kRepAString)},
    // optional string pb_srvID = 2;
    {PROTOBUF_FIELD_OFFSET(ExStatLog, _impl_.pb_srvid_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kRawString | ::_fl::kRepAString)},
    // optional string pb_uid = 3;
    {PROTOBUF_FIELD_OFFSET(ExStatLog, _impl_.pb_uid_), _Internal::kHasBitsOffset + 2, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kRawString | ::_fl::kRepAString)},
    // optional string pb_type = 4;
    {PROTOBUF_FIELD_OFFSET(ExStatLog, _impl_.pb_type_), _Internal::kHasBitsOffset + 3, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kRawString | ::_fl::kRepAString)},
    // optional string pb_level = 5;
    {PROTOBUF_FIELD_OFFSET(ExStatLog, _impl_.pb_level_), _Internal::kHasBitsOffset + 4, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kRawString | ::_fl::kRepAString)},
    // optional string pb_platid = 6;
    {PROTOBUF_FIELD_OFFSET(ExStatLog, _impl_.pb_platid_), _Internal::kHasBitsOffset + 5, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kRawString | ::_fl::kRepAString)},
    // optional string pb_haspay = 7;
    {PROTOBUF_FIELD_OFFSET(ExStatLog, _impl_.pb_haspay_), _Internal::kHasBitsOffset + 6, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kRawString | ::_fl::kRepAString)},
    // optional string pb_regtime = 8;
    {PROTOBUF_FIELD_OFFSET(ExStatLog, _impl_.pb_regtime_), _Internal::kHasBitsOffset + 7, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kRawString | ::_fl::kRepAString)},
    // optional string pb_paygold = 9;
    {PROTOBUF_FIELD_OFFSET(ExStatLog, _impl_.pb_paygold_), _Internal::kHasBitsOffset + 8, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kRawString | ::_fl::kRepAString)},
    // optional string pb_freegold = 10;
    {PROTOBUF_FIELD_OFFSET(ExStatLog, _impl_.pb_freegold_), _Internal::kHasBitsOffset + 9, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kRawString | ::_fl::kRepAString)},
    // optional string pb_channel = 11;
    {PROTOBUF_FIELD_OFFSET(ExStatLog, _impl_.pb_channel_), _Internal::kHasBitsOffset + 10, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kRawString | ::_fl::kRepAString)},
    // optional string pb_region = 12;
    {PROTOBUF_FIELD_OFFSET(ExStatLog, _impl_.pb_region_), _Internal::kHasBitsOffset + 11, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kRawString | ::_fl::kRepAString)},
    // optional string pb_viplv = 13;
    {PROTOBUF_FIELD_OFFSET(ExStatLog, _impl_.pb_viplv_), _Internal::kHasBitsOffset + 12, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kRawString | ::_fl::kRepAString)},
    // optional string pb_devicemum = 14;
    {PROTOBUF_FIELD_OFFSET(ExStatLog, _impl_.pb_devicemum_), _Internal::kHasBitsOffset + 13, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kRawString | ::_fl::kRepAString)},
    // repeated string pb_other = 15;
    {PROTOBUF_FIELD_OFFSET(ExStatLog, _impl_.pb_other_), -1, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kRawString | ::_fl::kRepSString)},
  }},
  // no aux_entries
  {{
    "\11\7\10\6\7\10\11\11\12\12\13\12\11\10\14\10"
    "ExStatLog"
    "pb_date"
    "pb_srvID"
    "pb_uid"
    "pb_type"
    "pb_level"
    "pb_platid"
    "pb_haspay"
    "pb_regtime"
    "pb_paygold"
    "pb_freegold"
    "pb_channel"
    "pb_region"
    "pb_viplv"
    "pb_devicemum"
    "pb_other"
  }},
};

PROTOBUF_NOINLINE void ExStatLog::Clear() {
// @@protoc_insertion_point(message_clear_start:ExStatLog)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.pb_other_.Clear();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x000000ffu) {
    if (cached_has_bits & 0x00000001u) {
      _impl_.pb_date_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000002u) {
      _impl_.pb_srvid_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000004u) {
      _impl_.pb_uid_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000008u) {
      _impl_.pb_type_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000010u) {
      _impl_.pb_level_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000020u) {
      _impl_.pb_platid_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000040u) {
      _impl_.pb_haspay_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000080u) {
      _impl_.pb_regtime_.ClearNonDefaultToEmpty();
    }
  }
  if (cached_has_bits & 0x00003f00u) {
    if (cached_has_bits & 0x00000100u) {
      _impl_.pb_paygold_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000200u) {
      _impl_.pb_freegold_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000400u) {
      _impl_.pb_channel_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000800u) {
      _impl_.pb_region_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00001000u) {
      _impl_.pb_viplv_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00002000u) {
      _impl_.pb_devicemum_.ClearNonDefaultToEmpty();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* ExStatLog::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ExStatLog)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // optional string pb_date = 1;
  if (cached_has_bits & 0x00000001u) {
    const std::string& _s = this->_internal_pb_date();
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(_s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormat::SERIALIZE,
                                "ExStatLog.pb_date");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // optional string pb_srvID = 2;
  if (cached_has_bits & 0x00000002u) {
    const std::string& _s = this->_internal_pb_srvid();
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(_s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormat::SERIALIZE,
                                "ExStatLog.pb_srvID");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  // optional string pb_uid = 3;
  if (cached_has_bits & 0x00000004u) {
    const std::string& _s = this->_internal_pb_uid();
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(_s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormat::SERIALIZE,
                                "ExStatLog.pb_uid");
    target = stream->WriteStringMaybeAliased(3, _s, target);
  }

  // optional string pb_type = 4;
  if (cached_has_bits & 0x00000008u) {
    const std::string& _s = this->_internal_pb_type();
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(_s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormat::SERIALIZE,
                                "ExStatLog.pb_type");
    target = stream->WriteStringMaybeAliased(4, _s, target);
  }

  // optional string pb_level = 5;
  if (cached_has_bits & 0x00000010u) {
    const std::string& _s = this->_internal_pb_level();
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(_s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormat::SERIALIZE,
                                "ExStatLog.pb_level");
    target = stream->WriteStringMaybeAliased(5, _s, target);
  }

  // optional string pb_platid = 6;
  if (cached_has_bits & 0x00000020u) {
    const std::string& _s = this->_internal_pb_platid();
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(_s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormat::SERIALIZE,
                                "ExStatLog.pb_platid");
    target = stream->WriteStringMaybeAliased(6, _s, target);
  }

  // optional string pb_haspay = 7;
  if (cached_has_bits & 0x00000040u) {
    const std::string& _s = this->_internal_pb_haspay();
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(_s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormat::SERIALIZE,
                                "ExStatLog.pb_haspay");
    target = stream->WriteStringMaybeAliased(7, _s, target);
  }

  // optional string pb_regtime = 8;
  if (cached_has_bits & 0x00000080u) {
    const std::string& _s = this->_internal_pb_regtime();
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(_s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormat::SERIALIZE,
                                "ExStatLog.pb_regtime");
    target = stream->WriteStringMaybeAliased(8, _s, target);
  }

  // optional string pb_paygold = 9;
  if (cached_has_bits & 0x00000100u) {
    const std::string& _s = this->_internal_pb_paygold();
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(_s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormat::SERIALIZE,
                                "ExStatLog.pb_paygold");
    target = stream->WriteStringMaybeAliased(9, _s, target);
  }

  // optional string pb_freegold = 10;
  if (cached_has_bits & 0x00000200u) {
    const std::string& _s = this->_internal_pb_freegold();
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(_s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormat::SERIALIZE,
                                "ExStatLog.pb_freegold");
    target = stream->WriteStringMaybeAliased(10, _s, target);
  }

  // optional string pb_channel = 11;
  if (cached_has_bits & 0x00000400u) {
    const std::string& _s = this->_internal_pb_channel();
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(_s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormat::SERIALIZE,
                                "ExStatLog.pb_channel");
    target = stream->WriteStringMaybeAliased(11, _s, target);
  }

  // optional string pb_region = 12;
  if (cached_has_bits & 0x00000800u) {
    const std::string& _s = this->_internal_pb_region();
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(_s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormat::SERIALIZE,
                                "ExStatLog.pb_region");
    target = stream->WriteStringMaybeAliased(12, _s, target);
  }

  // optional string pb_viplv = 13;
  if (cached_has_bits & 0x00001000u) {
    const std::string& _s = this->_internal_pb_viplv();
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(_s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormat::SERIALIZE,
                                "ExStatLog.pb_viplv");
    target = stream->WriteStringMaybeAliased(13, _s, target);
  }

  // optional string pb_devicemum = 14;
  if (cached_has_bits & 0x00002000u) {
    const std::string& _s = this->_internal_pb_devicemum();
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(_s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormat::SERIALIZE,
                                "ExStatLog.pb_devicemum");
    target = stream->WriteStringMaybeAliased(14, _s, target);
  }

  // repeated string pb_other = 15;
  for (int i = 0, n = this->_internal_pb_other_size(); i < n; ++i) {
    const auto& s = this->_internal_pb_other().Get(i);
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(s.data(), static_cast<int>(s.length()), ::google::protobuf::internal::WireFormat::SERIALIZE,
                                "ExStatLog.pb_other");
    target = stream->WriteString(15, s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ExStatLog)
  return target;
}

::size_t ExStatLog::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ExStatLog)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(reinterpret_cast<const void*>(this));
  // repeated string pb_other = 15;
  total_size += 1 * ::google::protobuf::internal::FromIntSize(_internal_pb_other().size());
  for (int i = 0, n = _internal_pb_other().size(); i < n; ++i) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
        _internal_pb_other().Get(i));
  }
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x000000ffu) {
    // optional string pb_date = 1;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this->_internal_pb_date());
    }

    // optional string pb_srvID = 2;
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this->_internal_pb_srvid());
    }

    // optional string pb_uid = 3;
    if (cached_has_bits & 0x00000004u) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this->_internal_pb_uid());
    }

    // optional string pb_type = 4;
    if (cached_has_bits & 0x00000008u) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this->_internal_pb_type());
    }

    // optional string pb_level = 5;
    if (cached_has_bits & 0x00000010u) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this->_internal_pb_level());
    }

    // optional string pb_platid = 6;
    if (cached_has_bits & 0x00000020u) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this->_internal_pb_platid());
    }

    // optional string pb_haspay = 7;
    if (cached_has_bits & 0x00000040u) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this->_internal_pb_haspay());
    }

    // optional string pb_regtime = 8;
    if (cached_has_bits & 0x00000080u) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this->_internal_pb_regtime());
    }

  }
  if (cached_has_bits & 0x00003f00u) {
    // optional string pb_paygold = 9;
    if (cached_has_bits & 0x00000100u) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this->_internal_pb_paygold());
    }

    // optional string pb_freegold = 10;
    if (cached_has_bits & 0x00000200u) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this->_internal_pb_freegold());
    }

    // optional string pb_channel = 11;
    if (cached_has_bits & 0x00000400u) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this->_internal_pb_channel());
    }

    // optional string pb_region = 12;
    if (cached_has_bits & 0x00000800u) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this->_internal_pb_region());
    }

    // optional string pb_viplv = 13;
    if (cached_has_bits & 0x00001000u) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this->_internal_pb_viplv());
    }

    // optional string pb_devicemum = 14;
    if (cached_has_bits & 0x00002000u) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this->_internal_pb_devicemum());
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void ExStatLog::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ExStatLog*>(&to_msg);
  auto& from = static_cast<const ExStatLog&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ExStatLog)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_pb_other()->MergeFrom(from._internal_pb_other());
  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x000000ffu) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_set_pb_date(from._internal_pb_date());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_internal_set_pb_srvid(from._internal_pb_srvid());
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_internal_set_pb_uid(from._internal_pb_uid());
    }
    if (cached_has_bits & 0x00000008u) {
      _this->_internal_set_pb_type(from._internal_pb_type());
    }
    if (cached_has_bits & 0x00000010u) {
      _this->_internal_set_pb_level(from._internal_pb_level());
    }
    if (cached_has_bits & 0x00000020u) {
      _this->_internal_set_pb_platid(from._internal_pb_platid());
    }
    if (cached_has_bits & 0x00000040u) {
      _this->_internal_set_pb_haspay(from._internal_pb_haspay());
    }
    if (cached_has_bits & 0x00000080u) {
      _this->_internal_set_pb_regtime(from._internal_pb_regtime());
    }
  }
  if (cached_has_bits & 0x00003f00u) {
    if (cached_has_bits & 0x00000100u) {
      _this->_internal_set_pb_paygold(from._internal_pb_paygold());
    }
    if (cached_has_bits & 0x00000200u) {
      _this->_internal_set_pb_freegold(from._internal_pb_freegold());
    }
    if (cached_has_bits & 0x00000400u) {
      _this->_internal_set_pb_channel(from._internal_pb_channel());
    }
    if (cached_has_bits & 0x00000800u) {
      _this->_internal_set_pb_region(from._internal_pb_region());
    }
    if (cached_has_bits & 0x00001000u) {
      _this->_internal_set_pb_viplv(from._internal_pb_viplv());
    }
    if (cached_has_bits & 0x00002000u) {
      _this->_internal_set_pb_devicemum(from._internal_pb_devicemum());
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ExStatLog::CopyFrom(const ExStatLog& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ExStatLog)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ExStatLog::InternalSwap(ExStatLog* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.pb_other_.InternalSwap(&other->_impl_.pb_other_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.pb_date_, &other->_impl_.pb_date_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.pb_srvid_, &other->_impl_.pb_srvid_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.pb_uid_, &other->_impl_.pb_uid_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.pb_type_, &other->_impl_.pb_type_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.pb_level_, &other->_impl_.pb_level_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.pb_platid_, &other->_impl_.pb_platid_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.pb_haspay_, &other->_impl_.pb_haspay_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.pb_regtime_, &other->_impl_.pb_regtime_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.pb_paygold_, &other->_impl_.pb_paygold_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.pb_freegold_, &other->_impl_.pb_freegold_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.pb_channel_, &other->_impl_.pb_channel_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.pb_region_, &other->_impl_.pb_region_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.pb_viplv_, &other->_impl_.pb_viplv_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.pb_devicemum_, &other->_impl_.pb_devicemum_, arena);
}

::google::protobuf::Metadata ExStatLog::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_ExStatMsg_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
