// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ExStatCmd.proto
// Protobuf C++ Version: 5.27.0

#ifndef GOOGLE_PROTOBUF_INCLUDED_ExStatCmd_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_ExStatCmd_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5027000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_ExStatCmd_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_ExStatCmd_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_ExStatCmd_2eproto;
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

enum ENUM_COMMON_CMD : int {
  SRV_ExStatLog = 1001,
};

bool ENUM_COMMON_CMD_IsValid(int value);
extern const uint32_t ENUM_COMMON_CMD_internal_data_[];
constexpr ENUM_COMMON_CMD ENUM_COMMON_CMD_MIN = static_cast<ENUM_COMMON_CMD>(1001);
constexpr ENUM_COMMON_CMD ENUM_COMMON_CMD_MAX = static_cast<ENUM_COMMON_CMD>(1001);
constexpr int ENUM_COMMON_CMD_ARRAYSIZE = 1001 + 1;
const ::google::protobuf::EnumDescriptor*
ENUM_COMMON_CMD_descriptor();
template <typename T>
const std::string& ENUM_COMMON_CMD_Name(T value) {
  static_assert(std::is_same<T, ENUM_COMMON_CMD>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to ENUM_COMMON_CMD_Name().");
  return ENUM_COMMON_CMD_Name(static_cast<ENUM_COMMON_CMD>(value));
}
template <>
inline const std::string& ENUM_COMMON_CMD_Name(ENUM_COMMON_CMD value) {
  return ::google::protobuf::internal::NameOfDenseEnum<ENUM_COMMON_CMD_descriptor,
                                                 1001, 1001>(
      static_cast<int>(value));
}
inline bool ENUM_COMMON_CMD_Parse(absl::string_view name, ENUM_COMMON_CMD* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ENUM_COMMON_CMD>(
      ENUM_COMMON_CMD_descriptor(), name, value);
}

// ===================================================================



// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::ENUM_COMMON_CMD> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::ENUM_COMMON_CMD>() {
  return ::ENUM_COMMON_CMD_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_ExStatCmd_2eproto_2epb_2eh
